//---------------------------------------------------------------------
// <copyright file="ODataSimplifiedOptions.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

using System;

namespace Microsoft.OData
{
    /// <summary>
    /// Options which used to control the behaviour related odata simplified.
    /// </summary>
    public sealed class ODataSimplifiedOptions
    {
        /// <summary>
        /// Instance for <see cref="ODataSimplifiedOptions"/>.
        /// </summary>
        private static readonly ODataSimplifiedOptions DefaultOptions = new ODataSimplifiedOptions();

        /// <summary>
        /// Gets or sets a value that indicates whether the reader should put key values in their own URI segment when automatically building URIs.
        /// If this value is false, automatically-generated URLs will take the form "../EntitySet('KeyValue')/..".
        /// If this value is true, automatically-generated URLs will take the form "../EntitySet/KeyValue/..".
        /// If this value is not set (null), decision will be made based on the "Com.Microsoft.OData.Service.Conventions.V1.UrlConventions" vocabulary
        /// annotation on the IEdmEntityContainer, if available. The default behavior is to put key values inside parentheses and not a distinct URL segments.
        /// This setting only applies to URLs that are automatically generated by the <see cref="ODataMessageReader" /> and the URLs explicitly provided by the server won't be modified.
        /// </summary>
        public bool? EnableReadingKeyAsSegment { get; set; }

        /// <summary>
        /// True if can read reserved annotation name without prefix 'odata.', otherwise false. The default value is false.
        /// The option is applied during deserialization.
        /// </summary>
        public bool EnableReadingODataAnnotationWithoutPrefix { get; set; }

        /// <summary>
        /// Gets or sets a value that indicates whether the writer should put key values in their own URI segment when automatically building URIs.
        /// If this value is false, automatically-generated URLs will take the form "../EntitySet('KeyValue')/..".
        /// If this value is true, automatically-generated URLs will take the form "../EntitySet/KeyValue/..".
        /// If this value is not set (null), decision will be made based on the "Com.Microsoft.OData.Service.Conventions.V1.UrlConventions" vocabulary
        /// annotation on the IEdmEntityContainer, if available. The default behavior is to put key values inside parentheses and not a distinct URL segments.
        /// This setting only applies to URLs that are automatically generated by the <see cref="ODataMessageWriter" /> and does not modify URLs explicitly provided by the user.
        /// </summary>
        public bool? EnableWritingKeyAsSegment { get; set; }

        /// <summary>
        /// True if write reserved annotation name without prefix 'odata.', otherwise false. The default value is false.
        /// The option is applied during serialization.
        /// </summary>
        public bool EnableWritingODataAnnotationWithoutPrefix { get; set; }

        /// <summary>
        /// Return the instatnce of ODataSimplifiedOptions from container if it container not null.
        /// Otherwise return the static instance of ODataSimplifiedOptions.
        /// </summary>
        /// <param name="container">Container</param>
        /// <returns>Instance of GetODataSimplifiedOptions</returns>
        public static ODataSimplifiedOptions GetODataSimplifiedOptions(IServiceProvider container)
        {
            if (container == null)
            {
                return DefaultOptions;
            }

            return container.GetRequiredService<ODataSimplifiedOptions>();
        }
    }
}
