//---------------------------------------------------------------------
// <copyright file="SRResourcesTests.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace Microsoft.OData.Core.Tests.Resources;

public class SRResourcesTests
{
    [Theory]
    [InlineData("AggregateTransformationNode_UnsupportedAggregateExpressions", new object[] { })]
    [InlineData("AnnotationFilterPattern_InvalidPatternEmptySegment", new object[] { "Namespace.Name" })]
    [InlineData("AnnotationFilterPattern_InvalidPatternMissingDot", new object[] { "NamespaceName" })]
    [InlineData("AnnotationFilterPattern_InvalidPatternWildCardInSegment", new object[] { "Namespace.*.Name" })]
    [InlineData("AnnotationFilterPattern_InvalidPatternWildCardMustBeInLastSegment", new object[] { "Namespace.Name.*" })]
    [InlineData("ApplyBinder_AggregateExpressionIncompatibleTypeForMethod", new object[] { "Sum", "String" })]
    [InlineData("ApplyBinder_AggregateExpressionNotSingleValue", new object[] { "Expression" })]
    [InlineData("ApplyBinder_GroupByPropertyNotPropertyAccessValue", new object[] { "Property" })]
    [InlineData("ApplyBinder_UnsupportedAggregateKind", new object[] { "AggregateKind" })]
    [InlineData("ApplyBinder_UnsupportedAggregateMethod", new object[] { "MethodName" })]
    [InlineData("ApplyBinder_UnsupportedGroupByChild", new object[] { "ChildTransformation" })]
    [InlineData("ApplyBinder_UnsupportedType", new object[] { "UnsupportedType" })]
    [InlineData("AsyncBufferedStream_WriterDisposedWithoutFlush", new object[] { })]
    [InlineData("BadRequest_KeyCountMismatch", new object[] { "ResourceName" })]
    [InlineData("BadRequest_KeyMismatch", new object[] { "ResourceName" })]
    [InlineData("BadRequest_KeyOrAlternateKeyMismatch", new object[] { "ResourceName" })]
    [InlineData("BadRequest_ResourceCanBeCrossReferencedOnlyForBindOperation", new object[] { })]
    [InlineData("BatchReferenceSegment_InvalidContentID", new object[] { "ContentID" })]
    [InlineData("Binder_IsNotValidEnumConstant", new object[] { "EnumValue" })]
    [InlineData("BufferUtils_InvalidBufferOrSize", new object[] { 1024 })]
    [InlineData("CastBinder_ChildTypeIsNotEntity", new object[] { "ChildType" })]
    [InlineData("CastBinder_EnumOnlyCastToOrFromString", new object[] { })]
    [InlineData("CollectionWithoutExpectedTypeValidator_IncompatibleItemTypeKind", new object[] { "Primitive", "Complex" })]
    [InlineData("CollectionWithoutExpectedTypeValidator_IncompatibleItemTypeName", new object[] { "TypeName1", "TypeName2" })]
    [InlineData("CollectionWithoutExpectedTypeValidator_InvalidItemTypeKind", new object[] { "InvalidTypeKind" })]
    [InlineData("CustomUriFunctions_AddCustomUriFunction_BuiltInExistsFullSignature", new object[] { "FunctionName" })]
    [InlineData("CustomUriFunctions_AddCustomUriFunction_BuiltInExistsNotAddingAsOverload", new object[] { "FunctionName" })]
    [InlineData("CustomUriFunctions_AddCustomUriFunction_CustomFunctionOverloadExists", new object[] { "FunctionName" })]
    [InlineData("CustomUriTypePrefixLiterals_AddCustomUriTypePrefixLiteralAlreadyExists", new object[] { "TypePrefix" })]
    [InlineData("DataServiceConfiguration_ResponseVersionIsBiggerThanProtocolVersion", new object[] { "4.0", "3.0" })]
    [InlineData("DuplicateAnnotationForInstanceAnnotationNotAllowed", new object[] { "AnnotationName", "InstanceName" })]
    [InlineData("DuplicateAnnotationForPropertyNotAllowed", new object[] { "AnnotationName", "PropertyName" })]
    [InlineData("DuplicateAnnotationNotAllowed", new object[] { "AnnotationName" })]
    [InlineData("DuplicatePropertyNamesNotAllowed", new object[] { "PropertyName" })]
    [InlineData("EdmLibraryExtensions_NoParameterBoundOperationsFoundFromIEdmModelFindMethodIsInvalid", new object[] { "OperationName" })]
    [InlineData("EdmLibraryExtensions_OperationGroupReturningActionsAndFunctionsModelInvalid", new object[] { "OperationGroup" })]
    [InlineData("EdmLibraryExtensions_UnBoundOperationsFoundFromIEdmModelFindMethodIsInvalid", new object[] { "OperationName" })]
    [InlineData("EdmLibraryExtensions_ValueOverflowForUnderlyingType", new object[] { "Value", "Int32" })]
    [InlineData("EdmValueUtils_CannotConvertTypeToClrValue", new object[] { "PrimitiveKind" })]
    [InlineData("EdmValueUtils_IncorrectPrimitiveTypeKind", new object[] { "TypeName", "ExpectedKind", "ActualKind" })]
    [InlineData("EdmValueUtils_IncorrectPrimitiveTypeKindNoTypeName", new object[] { "ExpectedKind", "ActualKind" })]
    [InlineData("EdmValueUtils_NonPrimitiveValue", new object[] { "PropertyName", "TypeName" })]
    [InlineData("EdmValueUtils_PropertyDoesntExist", new object[] { "PropertyName", "TypeName" })]
    [InlineData("EdmValueUtils_UnsupportedPrimitiveType", new object[] { "UnsupportedType" })]
    [InlineData("ExceptionUtils_ArgumentStringEmpty", new object[] { })]
    [InlineData("ExceptionUtils_ArgumentStringEmpty1", new object[] { })]
    [InlineData("ExceptionUtils_ArgumentStringNullOrEmpty", new object[] { })]
    [InlineData("ExceptionUtils_CheckIntegerNotNegative", new object[] { -1 })]
    [InlineData("ExceptionUtils_CheckIntegerPositive", new object[] { 0 })]
    [InlineData("ExceptionUtils_CheckLongPositive", new object[] { -1L })]
    [InlineData("ExpandItemBinder_CannotFindType", new object[] { "TypeName" })]
    [InlineData("ExpandItemBinder_InvaidSegmentInExpand", new object[] { "SegmentName" })]
    [InlineData("ExpandItemBinder_LevelsNotAllowedOnIncompatibleRelatedType", new object[] { "NavigationProperty", "RelatedType", "SourceType" })]
    [InlineData("ExpandItemBinder_PathTooDeep", new object[] { })]
    [InlineData("ExpandItemBinder_PropertyIsNotANavigationPropertyOrComplexProperty", new object[] { "PropertyName", "TypeName" })]
    [InlineData("ExpandItemBinder_TraversingANonNormalizedTree", new object[] { })]
    [InlineData("ExpandItemBinder_TraversingMultipleNavPropsInTheSamePath", new object[] { })]
    [InlineData("ExpandItemBinder_TypeSegmentNotFollowedByPath", new object[] { })]
    [InlineData("ExpandTreeNormalizer_NonPathInPropertyChain", new object[] { })]
    [InlineData("ExpressionLexer_DigitExpected", new object[] { 5, "Expression" })]
    [InlineData("ExpressionLexer_ExpectedLiteralToken", new object[] { "Token" })]
    [InlineData("ExpressionLexer_InvalidCharacter", new object[] { "Character", 5, "Expression" })]
    [InlineData("ExpressionLexer_InvalidEscapeSequence", new object[] { "EscapeSequence", 5, "Expression" })]
    [InlineData("ExpressionLexer_InvalidNumericString", new object[] { "InvalidNumber" })]
    [InlineData("ExpressionLexer_SyntaxError", new object[] { 5, "Expression" })]
    [InlineData("ExpressionLexer_UnbalancedBracketExpression", new object[] { })]
    [InlineData("ExpressionLexer_UnterminatedLiteral", new object[] { 5, "Expression" })]
    [InlineData("ExpressionLexer_UnterminatedStringLiteral", new object[] { 5, "Expression" })]
    [InlineData("ExpressionToken_IdentifierExpected", new object[] { 5 })]
    [InlineData("ExpressionToken_NoPropAllowedAfterDollarCount", new object[] { })]
    [InlineData("ExpressionToken_NoPropAllowedAfterRef", new object[] { })]
    [InlineData("ExpressionToken_NoSegmentAllowedBeforeStarInExpand", new object[] { })]
    [InlineData("ExpressionToken_OnlyRefAllowWithStarInExpand", new object[] { })]
    [InlineData("FunctionCallBinder_CallingFunctionOnOpenProperty", new object[] { "FunctionName" })]
    [InlineData("FunctionCallBinder_CannotFindASuitableOverload", new object[] { "FunctionName", 2 })]
    [InlineData("FunctionCallBinder_UriFunctionMustHaveHaveNullParent", new object[] { "FunctionName" })]
    [InlineData("FunctionCallParser_DuplicateParameterOrEntityKeyName", new object[] { })]
    [InlineData("FunctionOverloadResolver_FoundInvalidOperation", new object[] { "OperationName" })]
    [InlineData("FunctionOverloadResolver_FoundInvalidOperationImport", new object[] { "OperationImportName" })]
    [InlineData("FunctionOverloadResolver_MultipleActionImportOverloads", new object[] { "ActionImportName" })]
    [InlineData("FunctionOverloadResolver_MultipleActionOverloads", new object[] { "ActionName" })]
    [InlineData("FunctionOverloadResolver_MultipleOperationImportOverloads", new object[] { "OperationImportName" })]
    [InlineData("FunctionOverloadResolver_MultipleOperationOverloads", new object[] { "OperationName" })]
    [InlineData("FunctionOverloadResolver_NoSingleMatchFound", new object[] { "FunctionName", "ParameterNames" })]
    [InlineData("General_InternalError", new object[] { "ErrorMessage" })]
    [InlineData("HttpHeaderValueLexer_EndOfFileAfterSeparator", new object[] { "HeaderName", "HeaderValue", 5, "Separator" })]
    [InlineData("HttpHeaderValueLexer_FailedToReadTokenOrQuotedString", new object[] { "HeaderName", "HeaderValue", 5 })]
    [InlineData("HttpHeaderValueLexer_InvalidSeparatorAfterQuotedString", new object[] { "HeaderName", "HeaderValue", 5, "Separator" })]
    [InlineData("HttpHeaderValueLexer_TokenExpectedButFoundQuotedString", new object[] { "HeaderName", "HeaderValue", 5 })]
    [InlineData("HttpHeaderValueLexer_UnrecognizedSeparator", new object[] { "HeaderName", "HeaderValue", 5, "Separator" })]
    [InlineData("HttpUtils_CannotConvertCharToInt", new object[] { "Character" })]
    [InlineData("HttpUtils_ClosingQuoteNotFound", new object[] { "HeaderName", "HeaderValue", 5 })]
    [InlineData("HttpUtils_ContentTypeMissing", new object[] { })]
    [InlineData("HttpUtils_EscapeCharAtEnd", new object[] { "HeaderName", "HeaderValue", 5, "EscapeChar" })]
    [InlineData("HttpUtils_EscapeCharWithoutQuotes", new object[] { "HeaderName", "HeaderValue", 5, "EscapeChar" })]
    [InlineData("HttpUtils_ExpectedLiteralNotFoundInString", new object[] { "Literal", 5, "String" })]
    [InlineData("HttpUtils_InvalidCharacterInQuotedParameterValue", new object[] { "HeaderName", "HeaderValue", 5, "Character" })]
    [InlineData("HttpUtils_InvalidCharsetName", new object[] { "CharsetName" })]
    [InlineData("HttpUtils_InvalidHttpMethodString", new object[] { "HttpMethod" })]
    [InlineData("HttpUtils_InvalidQualityValue", new object[] { "QualityValue", "HeaderValue" })]
    [InlineData("HttpUtils_InvalidQualityValueStartChar", new object[] { "HeaderValue", "StartChar" })]
    [InlineData("HttpUtils_InvalidSeparatorBetweenCharsets", new object[] { "HeaderName" })]
    [InlineData("HttpUtils_MediaTypeMissingParameterName", new object[] { })]
    [InlineData("HttpUtils_MediaTypeMissingParameterValue", new object[] { "ParameterName" })]
    [InlineData("HttpUtils_MediaTypeRequiresSemicolonBeforeParameter", new object[] { "MediaType" })]
    [InlineData("HttpUtils_MediaTypeRequiresSlash", new object[] { "MediaType" })]
    [InlineData("HttpUtils_MediaTypeRequiresSubType", new object[] { "MediaType" })]
    [InlineData("HttpUtils_MediaTypeUnspecified", new object[] { "MediaType" })]
    [InlineData("HttpUtils_MissingSeparatorBetweenCharsets", new object[] { "HeaderName" })]
    [InlineData("HttpUtils_NoOrMoreThanOneContentTypeSpecified", new object[] { "HeaderName" })]
    [InlineData("HttpUtils_UnexpectedEndOfQValue", new object[] { "HeaderName" })]
    [InlineData("InstanceAnnotation_AttributeValueNotationUsedOnNonEmptyElement", new object[] { "Value" })]
    [InlineData("InstanceAnnotation_AttributeValueNotationUsedWithIncompatibleType", new object[] { "Value", "Value" })]
    [InlineData("InstanceAnnotation_MissingTermAttributeOnAnnotationElement", new object[] { })]
    [InlineData("InstanceAnnotation_MultipleAttributeValueNotationAttributes", new object[] { })]
    [InlineData("JsonInstanceAnnotationWriter_DuplicateAnnotationNameInCollection", new object[] { "Value" })]
    [InlineData("JsonInstanceAnnotationWriter_NullValueNotAllowedForInstanceAnnotation", new object[] { "Value", "Value" })]
    [InlineData("JsonReader_ArrayClosureMismatch", new object[] { "Value", "Value", "Value" })]
    [InlineData("JsonReader_CannotAccessValueInStreamState", new object[] { })]
    [InlineData("JsonReader_CannotCallReadInStreamState", new object[] { })]
    [InlineData("JsonReader_CannotCreateReadStream", new object[] { })]
    [InlineData("JsonReader_CannotCreateTextReader", new object[] { })]
    [InlineData("JsonReader_EndOfInputWithOpenScope", new object[] { })]
    [InlineData("JsonReader_InvalidBinaryFormat", new object[] { "Value" })]
    [InlineData("JsonReader_InvalidNumberFormat", new object[] { "Value" })]
    [InlineData("JsonReader_InvalidPropertyNameOrUnexpectedComma", new object[] { "Value" })]
    [InlineData("JsonReader_MaxBufferReached", new object[] { })]
    [InlineData("JsonReader_MissingColon", new object[] { "Value" })]
    [InlineData("JsonReader_MissingComma", new object[] { "Value" })]
    [InlineData("JsonReader_MultipleTopLevelValues", new object[] { })]
    [InlineData("JsonReader_UnexpectedComma", new object[] { "Value" })]
    [InlineData("JsonReader_UnexpectedEndOfString", new object[] { })]
    [InlineData("JsonReader_UnexpectedToken", new object[] { "Value" })]
    [InlineData("JsonReader_UnrecognizedEscapeSequence", new object[] { "Value" })]
    [InlineData("JsonReader_UnrecognizedToken", new object[] { })]
    [InlineData("JsonReaderExtensions_CannotReadPropertyValueAsString", new object[] { "Value", "Value" })]
    [InlineData("JsonReaderExtensions_CannotReadValueAsDouble", new object[] { "Value" })]
    [InlineData("JsonReaderExtensions_CannotReadValueAsString", new object[] { "Value" })]
    [InlineData("JsonReaderExtensions_UnexpectedInstanceAnnotationName", new object[] { "Value" })]
    [InlineData("JsonReaderExtensions_UnexpectedNodeDetected", new object[] { "Value", "Value" })]
    [InlineData("JsonReaderExtensions_UnexpectedNodeDetectedWithPropertyName", new object[] { "Value", "Value", "Value" })]
    [InlineData("MediaType_EncodingNotSupported", new object[] { "Value" })]
    [InlineData("MediaTypeUtils_BoundaryMustBeSpecifiedForBatchPayloads", new object[] { "Value", "Value" })]
    [InlineData("MediaTypeUtils_CannotDetermineFormatFromContentType", new object[] { "Value", "Value" })]
    [InlineData("MediaTypeUtils_DidNotFindMatchingMediaType", new object[] { "Value", "Value" })]
    [InlineData("MediaTypeUtils_NoOrMoreThanOneContentTypeSpecified", new object[] { "Value" })]
    [InlineData("MessageStreamWrappingStream_ByteLimitExceeded", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_AnyAllExpressionNotSingleValue", new object[] { })]
    [InlineData("MetadataBinder_BinaryOperatorOperandNotSingleValue", new object[] { "Value" })]
    [InlineData("MetadataBinder_BoundNodeCannotBeNull", new object[] { "Value" })]
    [InlineData("MetadataBinder_CannotConvertToType", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_CastOrIsOfCollectionsNotSupported", new object[] { })]
    [InlineData("MetadataBinder_CastOrIsOfExpressionWithWrongNumberOfOperands", new object[] { "Value" })]
    [InlineData("MetadataBinder_CastOrIsOfFunctionWithoutATypeArgument", new object[] { })]
    [InlineData("MetadataBinder_CollectionOpenPropertiesNotSupportedInThisRelease", new object[] { })]
    [InlineData("MetadataBinder_CountSegmentNextTokenNotCollectionValue", new object[] { })]
    [InlineData("MetadataBinder_DuplicitKeyPropertyInKeyValues", new object[] { "Value" })]
    [InlineData("MetadataBinder_FilterExpressionNotSingleValue", new object[] { })]
    [InlineData("MetadataBinder_FunctionArgumentNotSingleValue", new object[] { "Value" })]
    [InlineData("MetadataBinder_HierarchyNotFollowed", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_IllegalSegmentType", new object[] { "Value" })]
    [InlineData("MetadataBinder_IncompatibleOperandError", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_IncompatibleOperandsError", new object[] { "Value", "Value", "Value" })]
    [InlineData("MetadataBinder_InvalidIdentifierInQueryOption", new object[] { "Value" })]
    [InlineData("MetadataBinder_LambdaParentMustBeCollection", new object[] { })]
    [InlineData("MetadataBinder_LeftOperandNotSingleValue", new object[] { })]
    [InlineData("MetadataBinder_NavigationPropertyNotFollowingSingleEntityType", new object[] { })]
    [InlineData("MetadataBinder_NoApplicableFunctionFound", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_NotAllKeyPropertiesSpecifiedInKeyValues", new object[] { "Value" })]
    [InlineData("MetadataBinder_OrderByExpressionNotSingleValue", new object[] { })]
    [InlineData("MetadataBinder_ParameterAliasValueExpressionNotSingleValue", new object[] { })]
    [InlineData("MetadataBinder_ParameterNotInScope", new object[] { "Value" })]
    [InlineData("MetadataBinder_PropertyAccessSourceNotSingleValue", new object[] { "Value" })]
    [InlineData("MetadataBinder_PropertyAccessWithoutParentParameter", new object[] { })]
    [InlineData("MetadataBinder_PropertyNotDeclared", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_PropertyNotDeclaredOrNotKeyInKeyValue", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_QualifiedFunctionNameWithParametersNotDeclared", new object[] { "Value", "Value" })]
    [InlineData("MetadataBinder_QueryOptionNotApplicable", new object[] { "Value" })]
    [InlineData("MetadataBinder_QueryOptionsBindMethodCannotBeNull", new object[] { })]
    [InlineData("MetadataBinder_QueryOptionsBindStateCannotBeNull", new object[] { })]
    [InlineData("MetadataBinder_RightOperandNotCollectionValue", new object[] { })]
    [InlineData("MetadataBinder_SkipRequiresNonNegativeInteger", new object[] { "Value" })]
    [InlineData("MetadataBinder_TopRequiresNonNegativeInteger", new object[] { "Value" })]
    [InlineData("MetadataBinder_UnaryOperatorOperandNotSingleValue", new object[] { "Value" })]
    [InlineData("MetadataBinder_UnknownFunction", new object[] { "Value" })]
    [InlineData("MetadataBinder_UnnamedKeyValueOnTypeWithMultipleKeyProperties", new object[] { "Value" })]
    [InlineData("MetadataBinder_UnsupportedQueryTokenKind", new object[] { "Value" })]
    [InlineData("MetadataUtils_CalculateBindableOperationsForType", new object[] { "Value" })]
    [InlineData("MetadataUtils_ResolveTypeName", new object[] { "Value" })]
    [InlineData("Nodes_CollectionFunctionCallNode_ItemTypeMustBePrimitiveOrComplexOrEnum", new object[] { })]
    [InlineData("Nodes_CollectionNavigationNode_MustHaveManyMultiplicity", new object[] { })]
    [InlineData("Nodes_CollectionNavigationNode_MustHaveSingleMultiplicity", new object[] { })]
    [InlineData("Nodes_EntityCollectionFunctionCallNode_ItemTypeMustBeAnEntity", new object[] { })]
    [InlineData("Nodes_InNode_CollectionItemTypeMustBeSameAsSingleItemType", new object[] { "Value", "Value" })]
    [InlineData("Nodes_NonentityParameterQueryNodeWithEntityType", new object[] { "Value" })]
    [InlineData("Nodes_NonStaticEntitySetExpressionsAreNotSupportedInThisRelease", new object[] { })]
    [InlineData("Nodes_PropertyAccessShouldBeNonEntityProperty", new object[] { "Value" })]
    [InlineData("Nodes_PropertyAccessTypeMustBeCollection", new object[] { "Value" })]
    [InlineData("Nodes_PropertyAccessTypeShouldNotBeCollection", new object[] { "Value" })]
    [InlineData("Nodes_SingleValueFunctionCallNode_ItemTypeMustBePrimitiveOrComplexOrEnum", new object[] { })]
    [InlineData("ODataAsyncReader_AsyncCallOnSyncReader", new object[] { })]
    [InlineData("ODataAsyncReader_CannotCreateResponseWhenNotReadingResponse", new object[] { })]
    [InlineData("ODataAsyncReader_DuplicateHeaderFound", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_InvalidHeaderSpecified", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_InvalidHttpVersionSpecified", new object[] { "Value1", "Value2" })]
    [InlineData("ODataAsyncReader_InvalidNewLineEncountered", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_InvalidResponseLine", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_MultiByteEncodingsNotSupported", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_NonIntegerHttpStatusCode", new object[] { "Value" })]
    [InlineData("ODataAsyncReader_SyncCallOnAsyncReader", new object[] { })]
    [InlineData("ODataAsyncReader_UnexpectedEndOfInput", new object[] { })]
    [InlineData("ODataAsyncResponseMessage_MustNotModifyMessage", new object[] { })]
    [InlineData("ODataAsyncWriter_AsyncCallOnSyncWriter", new object[] { })]
    [InlineData("ODataAsyncWriter_CannotCreateResponseMoreThanOnce", new object[] { })]
    [InlineData("ODataAsyncWriter_CannotCreateResponseWhenNotWritingResponse", new object[] { })]
    [InlineData("ODataAsyncWriter_CannotWriteInStreamErrorForAsync", new object[] { })]
    [InlineData("ODataAsyncWriter_SyncCallOnAsyncWriter", new object[] { })]
    [InlineData("ODataBatch_GroupIdOrChangeSetIdCannotBeNull", new object[] { })]
    [InlineData("ODataBatch_InvalidHttpMethodForChangeSetRequest", new object[] { "Value" })]
    [InlineData("ODataBatchOperationHeaderDictionary_DuplicateCaseInsensitiveKeys", new object[] { "Value" })]
    [InlineData("ODataBatchOperationHeaderDictionary_KeyNotFound", new object[] { "Value" })]
    [InlineData("ODataBatchOperationMessage_VerifyNotCompleted", new object[] { })]
    [InlineData("ODataBatchOperationStream_Disposed", new object[] { })]
    [InlineData("ODataBatchReader_AbsoluteURINotMatchingBaseUri", new object[] { "Value", "Value" })]
    [InlineData("ODataBatchReader_AsyncCallOnSyncReader", new object[] { })]
    [InlineData("ODataBatchReader_CannotCreateRequestOperationWhenReadingResponse", new object[] { })]
    [InlineData("ODataBatchReader_CannotCreateResponseOperationWhenReadingRequest", new object[] { })]
    [InlineData("ODataBatchReader_CannotUseReaderWhileOperationStreamActive", new object[] { })]
    [InlineData("ODataBatchReader_DependsOnIdNotFound", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReader_DependsOnRequestIdIsPartOfAtomicityGroupNotAllowed", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReader_DuplicateAtomicityGroupIDsNotAllowed", new object[] { "Value" })]
    [InlineData("ODataBatchReader_DuplicateContentIDsNotAllowed", new object[] { "Value" })]
    [InlineData("ODataBatchReader_InvalidStateForCreateOperationRequestMessage", new object[] { "Value" })]
    [InlineData("ODataBatchReader_InvalidStateForCreateOperationResponseMessage", new object[] { "Value" })]
    [InlineData("ODataBatchReader_JsonBatchTopLevelPropertyMissing", new object[] { })]
    [InlineData("ODataBatchReader_MaxBatchSizeExceeded", new object[] { "Value" })]
    [InlineData("ODataBatchReader_MaxChangeSetSizeExceeded", new object[] { "Value" })]
    [InlineData("ODataBatchReader_MessageIdPositionedIncorrectly", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReader_NoMessageWasCreatedForOperation", new object[] { })]
    [InlineData("ODataBatchReader_OperationRequestMessageAlreadyCreated", new object[] { })]
    [InlineData("ODataBatchReader_OperationResponseMessageAlreadyCreated", new object[] { })]
    [InlineData("ODataBatchReader_ReaderModeNotInitilized", new object[] { })]
    [InlineData("ODataBatchReader_ReaderStreamChangesetBoundaryCannotBeNull", new object[] { })]
    [InlineData("ODataBatchReader_ReadOrReadAsyncCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataBatchReader_ReferenceIdNotIncludedInDependsOn", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataBatchReader_RequestPropertyMissing", new object[] { "Value" })]
    [InlineData("ODataBatchReader_SameRequestIdAsAtomicityGroupIdNotAllowed", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReader_SelfReferenceDependsOnRequestIdNotAllowed", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReader_SyncCallOnAsyncReader", new object[] { })]
    [InlineData("ODataBatchReaderStream_DuplicateHeaderFound", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_InvalidContentLengthSpecified", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_InvalidContentTypeSpecified", new object[] { "Value1", "Value2", "Value3", "Value4" })]
    [InlineData("ODataBatchReaderStream_InvalidHeaderSpecified", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_InvalidHttpVersionSpecified", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReaderStream_InvalidRequestLine", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_InvalidResponseLine", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_MissingContentTypeHeader", new object[] { })]
    [InlineData("ODataBatchReaderStream_MissingOrInvalidContentEncodingHeader", new object[] { "Value1", "Value2" })]
    [InlineData("ODataBatchReaderStream_MultiByteEncodingsNotSupported", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_NestedChangesetsAreNotSupported", new object[] { })]
    [InlineData("ODataBatchReaderStream_NonIntegerHttpStatusCode", new object[] { "Value" })]
    [InlineData("ODataBatchReaderStream_UnexpectedEndOfInput", new object[] { })]
    [InlineData("ODataBatchReaderStreamBuffer_BoundaryLineSecurityLimitReached", new object[] { "Value" })]
    [InlineData("ODataBatchUtils_RelativeUriStartingWithDollarUsedWithoutBaseUriSpecified", new object[] { "Value" })]
    [InlineData("ODataBatchUtils_RelativeUriUsedWithoutBaseUriSpecified", new object[] { "Value" })]
    [InlineData("ODataBatchWriter_AsyncCallOnSyncWriter", new object[] { })]
    [InlineData("ODataBatchWriter_CannotCompleteBatchWithActiveChangeSet", new object[] { })]
    [InlineData("ODataBatchWriter_CannotCompleteChangeSetWithoutActiveChangeSet", new object[] { })]
    [InlineData("ODataBatchWriter_CannotCreateRequestOperationWhenWritingResponse", new object[] { })]
    [InlineData("ODataBatchWriter_CannotCreateResponseOperationWhenWritingRequest", new object[] { })]
    [InlineData("ODataBatchWriter_CannotStartChangeSetWithActiveChangeSet", new object[] { })]
    [InlineData("ODataBatchWriter_CannotWriteInStreamErrorForBatch", new object[] { })]
    [InlineData("ODataBatchWriter_DuplicateContentIDsNotAllowed", new object[] { "Value" })]
    [InlineData("ODataBatchWriter_FlushOrFlushAsyncCalledInStreamRequestedState", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromBatchCompleted", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromBatchStarted", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromChangeSetCompleted", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromChangeSetStarted", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromOperationContentStreamDisposed", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromOperationContentStreamRequested", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromOperationCreated", new object[] { })]
    [InlineData("ODataBatchWriter_InvalidTransitionFromStart", new object[] { })]
    [InlineData("ODataBatchWriter_MaxBatchSizeExceeded", new object[] { "Value" })]
    [InlineData("ODataBatchWriter_MaxChangeSetSizeExceeded", new object[] { "Value" })]
    [InlineData("ODataBatchWriter_SyncCallOnAsyncWriter", new object[] { })]
    [InlineData("ODataCollectionReaderCore_AsyncCallOnSyncReader", new object[] { })]
    [InlineData("ODataCollectionReaderCore_ExpectedItemTypeSetInInvalidState", new object[] { "Value1", "Value2" })]
    [InlineData("ODataCollectionReaderCore_ReadOrReadAsyncCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataCollectionReaderCore_SyncCallOnAsyncReader", new object[] { })]
    [InlineData("ODataCollectionWriterCore_AsyncCallOnSyncWriter", new object[] { })]
    [InlineData("ODataCollectionWriterCore_InvalidTransitionFromCollection", new object[] { "Value1", "Value2" })]
    [InlineData("ODataCollectionWriterCore_InvalidTransitionFromItem", new object[] { "Value1", "Value2" })]
    [InlineData("ODataCollectionWriterCore_InvalidTransitionFromStart", new object[] { "Value1", "Value2" })]
    [InlineData("ODataCollectionWriterCore_SyncCallOnAsyncWriter", new object[] { })]
    [InlineData("ODataCollectionWriterCore_WriteEndCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataContextUriBuilder_NavigationSourceOrTypeNameMissingForResourceOrResourceSet", new object[] { })]
    [InlineData("ODataContextUriBuilder_ODataPathInvalidForContainedElement", new object[] { "Value" })]
    [InlineData("ODataContextUriBuilder_ODataUriMissingForIndividualProperty", new object[] { })]
    [InlineData("ODataContextUriBuilder_StreamValueMustBePropertiesOfODataResource", new object[] { })]
    [InlineData("ODataContextUriBuilder_TypeNameMissingForProperty", new object[] { })]
    [InlineData("ODataContextUriBuilder_TypeNameMissingForTopLevelCollection", new object[] { })]
    [InlineData("ODataContextUriBuilder_UnsupportedPayloadKind", new object[] { "Value" })]
    [InlineData("ODataContextUriBuilder_ValidateDerivedType", new object[] { "Value1", "Value2" })]
    [InlineData("ODataConventionalUriBuilder_EntityTypeWithNoKeyProperties", new object[] { "Value" })]
    [InlineData("ODataConventionalUriBuilder_NullKeyValue", new object[] { "Value1", "Value2" })]
    [InlineData("ODataEdmStructuredValue_UndeclaredProperty", new object[] { "Value1", "Value2" })]
    [InlineData("ODataErrorException_GeneralError", new object[] { })]
    [InlineData("ODataException_GeneralError", new object[] { })]
    [InlineData("ODataExpandPath_InvalidExpandPathSegment", new object[] { "Value" })]
    [InlineData("ODataExpandPath_LastSegmentMustBeNavigationPropertyOrTypeSegment", new object[] { })]
    [InlineData("ODataExpandPath_OnlyLastSegmentCanBeNavigationProperty", new object[] { })]
    [InlineData("ODataInputContext_UnsupportedPayloadKindForFormat", new object[] { "Value", "Value" })]
    [InlineData("ODataInstanceAnnotation_BadTermName", new object[] { "Value" })]
    [InlineData("ODataInstanceAnnotation_NeedPeriodInName", new object[] { "Value" })]
    [InlineData("ODataInstanceAnnotation_ReservedNamesNotAllowed", new object[] { "Value1", "Value2" })]
    [InlineData("ODataInstanceAnnotation_ValueCannotBeODataStreamReferenceValue", new object[] { })]
    [InlineData("ODataJsonBatchBodyContentReaderStream_UnexpectedNodeType", new object[] { "Value" })]
    [InlineData("ODataJsonBatchBodyContentReaderStream_UnsupportedContentTypeInHeader", new object[] { "Value" })]
    [InlineData("ODataJsonBatchPayloadItemPropertiesCache_DuplicateHeaderForRequestInBatch", new object[] { "Value" })]
    [InlineData("ODataJsonBatchPayloadItemPropertiesCache_DuplicatePropertyForRequestInBatch", new object[] { "Value" })]
    [InlineData("ODataJsonBatchPayloadItemPropertiesCache_UnknownPropertyForMessageInBatch", new object[] { "Value" })]
    [InlineData("ODataJsonCollectionDeserializer_CannotReadCollectionContentStart", new object[] { "Value" })]
    [InlineData("ODataJsonCollectionDeserializer_CannotReadCollectionEnd", new object[] { "Value" })]
    [InlineData("ODataJsonCollectionDeserializer_ExpectedCollectionPropertyNotFound", new object[] { "Value" })]
    [InlineData("ODataJsonCollectionDeserializer_InvalidCollectionTypeName", new object[] { "Value" })]
    [InlineData("ODataJsonContextUriParser_ContextUriDoesNotMatchExpectedPayloadKind", new object[] { "Value", "Value" })]
    [InlineData("ODataJsonContextUriParser_InvalidContextUrl", new object[] { "Value" })]
    [InlineData("ODataJsonContextUriParser_InvalidEntitySetNameOrTypeName", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonContextUriParser_InvalidPayloadKindWithSelectQueryOption", new object[] { "Value" })]
    [InlineData("ODataJsonContextUriParser_LastSegmentIsKeySegment", new object[] { "Value" })]
    [InlineData("ODataJsonContextUriParser_NoModel", new object[] { })]
    [InlineData("ODataJsonContextUriParser_NullMetadataDocumentUri", new object[] { })]
    [InlineData("ODataJsonContextUriParser_TopLevelContextUrlShouldBeAbsolute", new object[] { "Value" })]
    [InlineData("ODataJsonDeltaWriter_InvalidTransitionFromNestedResource", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonDeltaWriter_InvalidTransitionToNestedResource", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonDeltaWriter_WriteStartExpandedResourceSetCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataJsonDeserializer_AnnotationTargetingInstanceAnnotationWithoutValue", new object[] { "Value1", "Value" })]
    [InlineData("ODataJsonDeserializer_ContextLinkNotFoundAsFirstProperty", new object[] { })]
    [InlineData("ODataJsonDeserializer_OnlyODataTypeAnnotationCanTargetInstanceAnnotation", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataJsonDeserializer_RelativeUriUsedWithouODataMetadataAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkMustBeObjectValue", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkUrlCannotBeNull", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_ExpectedEntityReferenceLinksPropertyNotFound", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_InvalidAnnotationInEntityReferenceLink", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_InvalidEntityReferenceLinksPropertyFound", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_InvalidPropertyAnnotationInEntityReferenceLinks", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_InvalidPropertyInEntityReferenceLink", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_MissingEntityReferenceLinkProperty", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_MultipleUriPropertiesInEntityReferenceLink", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_PropertyAnnotationForEntityReferenceLink", new object[] { "Value" })]
    [InlineData("ODataJsonEntityReferenceLinkDeserializer_PropertyAnnotationForEntityReferenceLinks", new object[] { })]
    [InlineData("ODataJsonErrorDeserializer_InstanceAnnotationNotAllowedInErrorPayload", new object[] { "Value" })]
    [InlineData("ODataJsonErrorDeserializer_PropertyAnnotationNotAllowedInErrorPayload", new object[] { "Value" })]
    [InlineData("ODataJsonErrorDeserializer_PropertyAnnotationWithoutPropertyForError", new object[] { "Value" })]
    [InlineData("ODataJsonErrorDeserializer_TopLevelErrorMessageValueWithInvalidProperty", new object[] { "Value" })]
    [InlineData("ODataJsonErrorDeserializer_TopLevelErrorValueWithInvalidProperty", new object[] { "Value" })]
    [InlineData("ODataJsonErrorDeserializer_TopLevelErrorWithInvalidProperty", new object[] { "Value" })]
    [InlineData("ODataJsonInputContext_EntityTypeMustBeCompatibleWithEntitySetBaseType", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataJsonInputContext_ItemTypeRequiredForCollectionReaderInRequests", new object[] { })]
    [InlineData("ODataJsonInputContext_ModelRequiredForReading", new object[] { })]
    [InlineData("ODataJsonInputContext_NoEntitySetForRequest", new object[] { })]
    [InlineData("ODataJsonInputContext_OperationCannotBeNullForCreateParameterReader", new object[] { "Value" })]
    [InlineData("ODataJsonInputContext_PayloadKindDetectionForRequest", new object[] { })]
    [InlineData("ODataJsonOperationsDeserializerUtils_OperationPropertyCannotBeNull", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataJsonOperationsDeserializerUtils_OperationsPropertyMustHaveObjectValue", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonParameterDeserializer_NullCollectionExpected", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonParameterDeserializer_PropertyAnnotationForParameters", new object[] { })]
    [InlineData("ODataJsonParameterDeserializer_PropertyAnnotationWithoutPropertyForParameters", new object[] { "Value" })]
    [InlineData("ODataJsonParameterDeserializer_UnsupportedParameterTypeKind", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonParameterDeserializer_UnsupportedPrimitiveParameterType", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_CollectionTypeExpected", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_CollectionTypeNotExpected", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_ComplexValueWithPropertyTypeAnnotation", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_InvalidTopLevelPropertyName", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_InvalidTopLevelPropertyPayload", new object[] { })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_InvalidTypeName", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_NoPropertyAndAnnotationAllowedInNullPayload", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_ODataResourceExpectedForProperty", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_ODataTypeAnnotationInPrimitiveValue", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_ResourceTypeAnnotationNotFirst", new object[] { })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_ResourceValuePropertyAnnotationWithoutProperty", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_TopLevelPropertyAnnotationWithoutProperty", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_TopLevelPropertyWithPrimitiveNullValue", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_TypePropertyAfterValueProperty", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedAnnotationProperties", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedDataPropertyAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedMetadataReferenceProperty", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedODataPropertyAnnotation", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedProperty", new object[] { "Value" })]
    [InlineData("ODataJsonPropertyAndValueDeserializer_UnexpectedPropertyAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonPropertyAndValueSerializer_NoExpectedTypeOrTypeNameSpecifiedForCollectionValueInRequest", new object[] { })]
    [InlineData("ODataJsonPropertyAndValueSerializer_NoExpectedTypeOrTypeNameSpecifiedForResourceValueRequest", new object[] { })]
    [InlineData("ODataJsonReader_CannotReadResourcesOfResourceSet", new object[] { "Value" })]
    [InlineData("ODataJsonReader_UnexpectedPrimitiveValueForODataResource", new object[] { })]
    [InlineData("ODataJsonReaderCoreUtils_CannotReadSpatialPropertyValue", new object[] { })]
    [InlineData("ODataJsonReaderUtils_AnnotationWithNullValue", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertBoolean", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertDateTime", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertDateTimeOffset", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertDecimal", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertDouble", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_CannotConvertInt32", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_ConflictBetweenInputFormatAndParameter", new object[] { "Value" })]
    [InlineData("ODataJsonReaderUtils_InvalidValueForODataNullAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonReaderUtils_MultipleErrorPropertiesWithSameName", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_ArrayValueForSingletonBindPropertyAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_CannotReadCollectionNestedResource", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_CannotReadNestedResource", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_CannotReadResourceSetContentStart", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_CannotReadSingletonNestedResource", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_DeltaRemovedAnnotationMustBeObject", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_DuplicateNestedResourceSetAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_EmptyBindArray", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_ExpectedResourceSetPropertyNotFound", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_InvalidNodeTypeForItemsInResourceSet", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_InvalidPropertyAnnotationInTopLevelResourceSet", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_InvalidPropertyInTopLevelResourceSet", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_MetadataReferencePropertyInRequest", new object[] { })]
    [InlineData("ODataJsonResourceDeserializer_MultipleOptionalPropertiesInOperation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_NavigationPropertyWithoutValueAndEntityReferenceLink", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_OperationIsNotActionOrFunction", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_OperationMissingTargetProperty", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_PropertyWithoutValueWithUnknownType", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_PropertyWithoutValueWithWrongType", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_ResourceInstanceAnnotationPrecededByProperty", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_ResourceTypeAnnotationNotFirst", new object[] { })]
    [InlineData("ODataJsonResourceDeserializer_SingletonNavigationPropertyWithBindingAndValue", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_StreamPropertyInRequest", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_StreamPropertyWithValue", new object[] { "Value" })]
    [InlineData("ODataJsonResourceDeserializer_StringValueForCollectionBindPropertyAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedComplexCollectionPropertyAnnotation", new object[] { "PropertyName", "Value" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedDeferredLinkPropertyAnnotation", new object[] { "PropertyName", "Value" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedDeletedEntryInResponsePayload", new object[] { })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedExpandedCollectionNavigationLinkPropertyAnnotation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedExpandedSingletonNavigationLinkPropertyAnnotation", new object[] { "PropertyName", "Value" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedNavigationLinkInRequestPropertyAnnotation", new object[] { "PropertyName", "Value1", "Value2" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedPropertyAnnotationAfterExpandedResourceSet", new object[] { "PropertyName", "Value" })]
    [InlineData("ODataJsonResourceDeserializer_UnexpectedStreamPropertyAnnotation", new object[] { "PropertyName", "Value" })]
    [InlineData("ODataJsonResourceMetadataContext_MetadataAnnotationMustBeInPayload", new object[] { "Value" })]
    [InlineData("ODataJsonResourceSerializer_ActionsAndFunctionsGroupMustNotHaveDuplicateTarget", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonResourceSerializer_ActionsAndFunctionsGroupMustSpecifyTarget", new object[] { "ActionName" })]
    [InlineData("ODataJsonSerializer_RelativeUriUsedWithoutMetadataDocumentUriOrMetadata", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_DuplicatePropertiesInServiceDocument", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_DuplicatePropertiesInServiceDocumentElement", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_InstanceAnnotationInServiceDocument", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_InstanceAnnotationInServiceDocumentElement", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_MissingRequiredPropertyInServiceDocumentElement", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_MissingValuePropertyInServiceDocument", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_PropertyAnnotationInServiceDocument", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_PropertyAnnotationInServiceDocumentElement", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_PropertyAnnotationWithoutProperty", new object[] { "Value" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_UnexpectedPropertyInServiceDocument", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonServiceDocumentDeserializer_UnexpectedPropertyInServiceDocumentElement", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ODataJsonValidationUtils_OpenMetadataReferencePropertyNotSupported", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonValidationUtils_OperationPropertyCannotBeNull", new object[] { "Value1", "Value2" })]
    [InlineData("ODataJsonValueSerializer_MissingRawValueOnUntyped", new object[] { })]
    [InlineData("ODataJsonValueSerializer_MissingTypeNameOnCollection", new object[] { })]
    [InlineData("ODataJsonWriter_EntityReferenceLinkAfterResourceSetInRequest", new object[] { })]
    [InlineData("ODataJsonWriter_InstanceAnnotationNotSupportedOnExpandedResourceSet", new object[] { })]
    [InlineData("ODataJsonWriter_UnsupportedDateTimeFormat", new object[] { })]
    [InlineData("ODataJsonWriter_UnsupportedValueInCollection", new object[] { })]
    [InlineData("ODataJsonWriter_UnsupportedValueType", new object[] { "Value" })]
    [InlineData("ODataMessage_MustNotModifyMessage", new object[] { })]
    [InlineData("ODataMessageReader_DeltaInRequest", new object[] { })]
    [InlineData("ODataMessageReader_DetectPayloadKindMultipleTimes", new object[] { })]
    [InlineData("ODataMessageReader_EntitySetSpecifiedWithoutMetadata", new object[] { "Value" })]
    [InlineData("ODataMessageReader_ErrorPayloadInRequest", new object[] { })]
    [InlineData("ODataMessageReader_ExpectedCollectionTypeWrongKind", new object[] { "Value" })]
    [InlineData("ODataMessageReader_ExpectedPropertyTypeEntityCollectionKind", new object[] { })]
    [InlineData("ODataMessageReader_ExpectedPropertyTypeEntityKind", new object[] { })]
    [InlineData("ODataMessageReader_ExpectedPropertyTypeStream", new object[] { })]
    [InlineData("ODataMessageReader_ExpectedTypeSpecifiedWithoutMetadata", new object[] { "Value" })]
    [InlineData("ODataMessageReader_ExpectedValueTypeWrongKind", new object[] { "Value" })]
    [InlineData("ODataMessageReader_GetFormatCalledBeforeReadingStarted", new object[] { })]
    [InlineData("ODataMessageReader_MetadataDocumentInRequest", new object[] { })]
    [InlineData("ODataMessageReader_NoneOrEmptyContentTypeHeader", new object[] { })]
    [InlineData("ODataMessageReader_OperationImportSpecifiedWithoutMetadata", new object[] { "Value" })]
    [InlineData("ODataMessageReader_OperationSpecifiedWithoutMetadata", new object[] { "Value" })]
    [InlineData("ODataMessageReader_ParameterPayloadInResponse", new object[] { })]
    [InlineData("ODataMessageReader_PayloadKindDetectionInServerMode", new object[] { })]
    [InlineData("ODataMessageReader_PayloadKindDetectionRunning", new object[] { })]
    [InlineData("ODataMessageReader_ReaderAlreadyUsed", new object[] { })]
    [InlineData("ODataMessageReader_ServiceDocumentInRequest", new object[] { })]
    [InlineData("ODataMessageReader_SingletonNavigationPropertyForEntityReferenceLinks", new object[] { "Value1", "Value2" })]
    [InlineData("ODataMessageReader_WildcardInContentType", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_AsyncInRequest", new object[] { })]
    [InlineData("ODataMessageWriter_Buffer_Maximum_Size_Exceeded", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_CannotSetHeadersWithInvalidPayloadKind", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_CannotSpecifyOperationWithoutModel", new object[] { })]
    [InlineData("ODataMessageWriter_CannotWriteInStreamErrorForRawValues", new object[] { })]
    [InlineData("ODataMessageWriter_CannotWriteMetadataWithoutModel", new object[] { })]
    [InlineData("ODataMessageWriter_CannotWriteNullInRawFormat", new object[] { })]
    [InlineData("ODataMessageWriter_CannotWriteStreamPropertyAsTopLevelProperty", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_CannotWriteTopLevelNull", new object[] { })]
    [InlineData("ODataMessageWriter_DeltaInRequest", new object[] { })]
    [InlineData("ODataMessageWriter_EntityReferenceLinksInRequestNotAllowed", new object[] { })]
    [InlineData("ODataMessageWriter_ErrorPayloadInRequest", new object[] { })]
    [InlineData("ODataMessageWriter_IncompatiblePayloadKinds", new object[] { "PayloadKind1", "PayloadKind2" })]
    [InlineData("ODataMessageWriter_JsonPaddingOnInvalidContentType", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_JsonWriterFactory_ReturnedNull", new object[] { "Value1", "Value2" })]
    [InlineData("ODataMessageWriter_MetadataDocumentInRequest", new object[] { })]
    [InlineData("ODataMessageWriter_NonCollectionType", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_NotAllowedWriteTopLevelPropertyWithResourceValue", new object[] { "Value" })]
    [InlineData("ODataMessageWriter_ServiceDocumentInRequest", new object[] { })]
    [InlineData("ODataMessageWriter_WriteErrorAlreadyCalled", new object[] { })]
    [InlineData("ODataMessageWriter_WriterAlreadyUsed", new object[] { })]
    [InlineData("ODataMessageWriterSettings_MessageWriterSettingsXmlCustomizationCallbacksMustBeSpecifiedBoth", new object[] { })]
    [InlineData("ODataMetadataBuilder_MissingEntityInstanceUri", new object[] { "Value" })]
    [InlineData("ODataMetadataBuilder_MissingEntitySetUri", new object[] { "Value" })]
    [InlineData("ODataMetadataBuilder_MissingParentIdOrContextUrl", new object[] { })]
    [InlineData("ODataMetadataBuilder_MissingSegmentForEntitySetUriSuffix", new object[] { "Value1", "Value2" })]
    [InlineData("ODataMetadataBuilder_UnknownEntitySet", new object[] { "Value" })]
    [InlineData("ODataMetadataInputContext_ErrorReadingMetadata", new object[] { "Value" })]
    [InlineData("ODataMetadataOutputContext_ErrorWritingMetadata", new object[] { "Value" })]
    [InlineData("ODataMetadataOutputContext_NotSupportJsonMetadata", new object[] { })]
    [InlineData("ODataOutputContext_MetadataDocumentUriMissing", new object[] { })]
    [InlineData("ODataOutputContext_UnsupportedPayloadKindForFormat", new object[] { "PayloadKind", "Format" })]
    [InlineData("ODataParameterReaderCore_AsyncCallOnSyncReader", new object[] { })]
    [InlineData("ODataParameterReaderCore_CreateReaderAlreadyCalled", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_DuplicateParametersInPayload", new object[] { "Value" })]
    [InlineData("ODataParameterReaderCore_InvalidCreateReaderMethodCalledForState", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_ParameterNameNotInMetadata", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_ParametersMissingInPayload", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_ReadOrReadAsyncCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataParameterReaderCore_SubReaderMustBeCreatedAndReadToCompletionBeforeTheNextReadOrReadAsyncCall", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_SubReaderMustBeInCompletedStateBeforeTheNextReadOrReadAsyncCall", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterReaderCore_SyncCallOnAsyncReader", new object[] { })]
    [InlineData("ODataParameterWriter_CannotCreateParameterWriterOnResponseMessage", new object[] { })]
    [InlineData("ODataParameterWriter_InStreamErrorNotSupported", new object[] { })]
    [InlineData("ODataParameterWriterCore_AsyncCallOnSyncWriter", new object[] { })]
    [InlineData("ODataParameterWriterCore_CannotCreateCollectionWriterOnNonCollectionTypeKind", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterWriterCore_CannotCreateResourceSetWriterOnNonStructuredCollectionTypeKind", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterWriterCore_CannotCreateResourceWriterOnNonEntityOrComplexTypeKind", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterWriterCore_CannotWriteEnd", new object[] { })]
    [InlineData("ODataParameterWriterCore_CannotWriteInErrorOrCompletedState", new object[] { })]
    [InlineData("ODataParameterWriterCore_CannotWriteParameter", new object[] { })]
    [InlineData("ODataParameterWriterCore_CannotWriteStart", new object[] { })]
    [InlineData("ODataParameterWriterCore_CannotWriteValueOnNonSupportedValueType", new object[] { "ParameterName", "Value" })]
    [InlineData("ODataParameterWriterCore_CannotWriteValueOnNonValueTypeKind", new object[] { "ParameterName", "Value" })]
    [InlineData("ODataParameterWriterCore_DuplicatedParameterNameNotAllowed", new object[] { "Value" })]
    [InlineData("ODataParameterWriterCore_MissingParameterInParameterPayload", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterWriterCore_ParameterNameNotFoundInOperation", new object[] { "Value1", "Value2" })]
    [InlineData("ODataParameterWriterCore_SyncCallOnAsyncWriter", new object[] { })]
    [InlineData("ODataPrimitiveValue_CannotCreateODataPrimitiveValueFromNull", new object[] { })]
    [InlineData("ODataPrimitiveValue_CannotCreateODataPrimitiveValueFromUnsupportedValueType", new object[] { "Value" })]
    [InlineData("ODataPropertyAndValueDeserializer_InvalidCollectionElement", new object[] { "Value1", "Value2" })]
    [InlineData("ODataPropertyAndValueDeserializer_NavigationPropertyInProperties", new object[] { "Value1", "Value2" })]
    [InlineData("ODataReaderCore_AsyncCallOnSyncReader", new object[] { })]
    [InlineData("ODataReaderCore_CreateReadStreamCalledInInvalidState", new object[] { })]
    [InlineData("ODataReaderCore_CreateTextReaderCalledInInvalidState", new object[] { })]
    [InlineData("ODataReaderCore_NoReadCallsAllowed", new object[] { "Value" })]
    [InlineData("ODataReaderCore_ReadCalledWithOpenStream", new object[] { })]
    [InlineData("ODataReaderCore_ReadOrReadAsyncCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataReaderCore_SyncCallOnAsyncReader", new object[] { })]
    [InlineData("ODataRequestMessage_AsyncNotAvailable", new object[] { })]
    [InlineData("ODataRequestMessage_MessageStreamIsNull", new object[] { })]
    [InlineData("ODataRequestMessage_StreamTaskIsNull", new object[] { })]
    [InlineData("ODataResource_PropertyValueCannotBeODataResourceValue", new object[] { "Value" })]
    [InlineData("ODataResourceMetadataContext_EntityTypeWithNoKeyProperties", new object[] { "Value" })]
    [InlineData("ODataResourceMetadataContext_KeyOrETagValuesMustBePrimitiveValues", new object[] { "Value1", "Value2" })]
    [InlineData("ODataResourceMetadataContext_NullKeyValue", new object[] { "Value1", "Value2" })]
    [InlineData("ODataResourceSet_MustNotContainBothNextPageLinkAndDeltaLink", new object[] { })]
    [InlineData("ODataResourceTypeContext_MetadataOrSerializationInfoMissing", new object[] { })]
    [InlineData("ODataResourceTypeContext_ODataResourceTypeNameMissing", new object[] { })]
    [InlineData("ODataResponseMessage_AsyncNotAvailable", new object[] { })]
    [InlineData("ODataResponseMessage_MessageStreamIsNull", new object[] { })]
    [InlineData("ODataResponseMessage_StreamTaskIsNull", new object[] { })]
    [InlineData("ODataSelectPath_CannotOnlyHaveTypeSegment", new object[] { })]
    [InlineData("ODataSelectPath_InvalidSelectPathSegmentType", new object[] { "Value" })]
    [InlineData("ODataSelectPath_NavPropSegmentCanOnlyBeLastSegment", new object[] { })]
    [InlineData("ODataSelectPath_OperationSegmentCanOnlyBeLastSegment", new object[] { })]
    [InlineData("ODataUriParser_InvalidCount", new object[] { "Value" })]
    [InlineData("ODataUriParserException_GeneralError", new object[] { })]
    [InlineData("ODataUriUtils_ConvertFromUriLiteralNullOnNonNullableType", new object[] { "Value" })]
    [InlineData("ODataUriUtils_ConvertFromUriLiteralNullTypeVerificationFailure", new object[] { "Value1", "Value2" })]
    [InlineData("ODataUriUtils_ConvertFromUriLiteralOverflowNumber", new object[] { "Value1", "Value2" })]
    [InlineData("ODataUriUtils_ConvertFromUriLiteralTypeRefWithoutModel", new object[] { })]
    [InlineData("ODataUriUtils_ConvertFromUriLiteralTypeVerificationFailure", new object[] { "LiteralValue", "ExpectedType" })]
    [InlineData("ODataUriUtils_ConvertToUriLiteralUnsupportedType", new object[] { "Value" })]
    [InlineData("ODataUrlValidationError_InvalidRule", new object[] { "Value1", "Value2" })]
    [InlineData("ODataUrlValidationError_SelectRequired", new object[] { "Value" })]
    [InlineData("ODataUtils_CannotConvertValueToRawString", new object[] { "Value" })]
    [InlineData("ODataUtils_DidNotFindDefaultMediaType", new object[] { "Value" })]
    [InlineData("ODataUtils_MaxProtocolVersionExceeded", new object[] { "Value1", "Value2" })]
    [InlineData("ODataUtils_ModelDoesNotHaveContainer", new object[] { })]
    [InlineData("ODataUtils_UnsupportedVersionHeader", new object[] { "Value" })]
    [InlineData("ODataUtils_UnsupportedVersionNumber", new object[] { })]
    [InlineData("ODataWriter_RelativeUriUsedWithoutBaseUriSpecified", new object[] { "Value" })]
    [InlineData("ODataWriter_StreamPropertiesMustBePropertiesOfODataResource", new object[] { "Value" })]
    [InlineData("ODataWriterCore_AsyncCallOnSyncWriter", new object[] { })]
    [InlineData("ODataWriterCore_CannotWriteDeltaWithResourceSetWriter", new object[] { })]
    [InlineData("ODataWriterCore_CannotWriteTopLevelResourceSetWithResourceWriter", new object[] { })]
    [InlineData("ODataWriterCore_CannotWriteTopLevelResourceWithResourceSetWriter", new object[] { })]
    [InlineData("ODataWriterCore_DeferredLinkInRequest", new object[] { })]
    [InlineData("ODataWriterCore_DeltaLinkNotSupportedOnExpandedResourceSet", new object[] { })]
    [InlineData("ODataWriterCore_DeltaResourceWithoutIdOrKeyProperties", new object[] { })]
    [InlineData("ODataWriterCore_EntityReferenceLinkWithoutNavigationLink", new object[] { })]
    [InlineData("ODataWriterCore_InvalidStateTransition", new object[] { "State1", "State2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFrom40DeletedResource", new object[] { "State1", "State2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromCompleted", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromError", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromExpandedLink", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromNullResource", new object[] { "State", "Value" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromResource", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromResourceSet", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_InvalidTransitionFromStart", new object[] { "Value1", "Value2" })]
    [InlineData("ODataWriterCore_MultipleItemsInNestedResourceInfoWithContent", new object[] { })]
    [InlineData("ODataWriterCore_NestedContentNotAllowedIn40DeletedEntry", new object[] { })]
    [InlineData("ODataWriterCore_PathInODataUriMustBeSetWhenWritingContainedElement", new object[] { })]
    [InlineData("ODataWriterCore_PropertyValueAlreadyWritten", new object[] { "Value" })]
    [InlineData("ODataWriterCore_QueryCountInRequest", new object[] { })]
    [InlineData("ODataWriterCore_QueryDeltaLinkInRequest", new object[] { })]
    [InlineData("ODataWriterCore_QueryNextLinkInRequest", new object[] { })]
    [InlineData("ODataWriterCore_StreamNotDisposed", new object[] { })]
    [InlineData("ODataWriterCore_SyncCallOnAsyncWriter", new object[] { })]
    [InlineData("ODataWriterCore_WriteEndCalledInInvalidState", new object[] { "Value" })]
    [InlineData("ODataXmlDeserializer_RelativeUriUsedWithoutBaseUriSpecified", new object[] { "Value" })]
    [InlineData("ODataXmlErrorDeserializer_MultipleErrorElementsWithSameName", new object[] { "Value" })]
    [InlineData("ODataXmlErrorDeserializer_MultipleInnerErrorElementsWithSameName", new object[] { "Value" })]
    [InlineData("ODataXmlResourceDeserializer_ContentWithWrongType", new object[] { "Value" })]
    [InlineData("OpenNavigationPropertiesNotSupportedOnOpenTypes", new object[] { "Value" })]
    [InlineData("OperationSegment_CannotReturnNull", new object[] { })]
    [InlineData("OperationSegment_ReturnTypeForMultipleOverloads", new object[] { })]
    [InlineData("PathParser_CannotUseValueOnCollection", new object[] { })]
    [InlineData("PathParser_EntityReferenceNotSupported", new object[] { "Value" })]
    [InlineData("PathParser_TypeCastOnlyAllowedAfterStructuralCollection", new object[] { "Value" })]
    [InlineData("PathParser_TypeCastOnlyAllowedInDerivedTypeConstraint", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("PathParser_TypeMustBeRelatedToSet", new object[] { "TypeName", "SetName", "Value" })]
    [InlineData("PlatformHelper_DateTimeOffsetMustContainTimeZone", new object[] { "Value" })]
    [InlineData("PropertyAnnotationAfterTheProperty", new object[] { "Value1", "Value2" })]
    [InlineData("QueryOptionUtils_QueryParameterMustBeSpecifiedOnce", new object[] { "Value" })]
    [InlineData("ReaderUtils_EnumerableModified", new object[] { "Value" })]
    [InlineData("ReaderValidationUtils_CannotConvertPrimitiveValue", new object[] { "Value", "ExpectedType" })]
    [InlineData("ReaderValidationUtils_ContextUriDoesNotReferTypeAssignableToExpectedType", new object[] { "Uri", "TypeName", "Value" })]
    [InlineData("ReaderValidationUtils_ContextUriValidationInvalidExpectedEntitySet", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ReaderValidationUtils_ContextUriValidationInvalidExpectedEntityType", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ReaderValidationUtils_ContextUriValidationNonMatchingDeclaringTypes", new object[] { "Value1", "Value2", "Value3", "Value4" })]
    [InlineData("ReaderValidationUtils_ContextUriValidationNonMatchingPropertyNames", new object[] { "Value1", "Value2", "Value3", "Value4" })]
    [InlineData("ReaderValidationUtils_EntityReferenceLinkMissingUri", new object[] { })]
    [InlineData("ReaderValidationUtils_MessageReaderSettingsBaseUriMustBeNullOrAbsolute", new object[] { "Value" })]
    [InlineData("ReaderValidationUtils_NonMatchingPropertyNames", new object[] { "PropertyName1", "PropertyName2" })]
    [InlineData("ReaderValidationUtils_NullNamedValueForNonNullableType", new object[] { "Value1", "Value2" })]
    [InlineData("ReaderValidationUtils_NullNamedValueForNullableType", new object[] { "Value1", "Value2" })]
    [InlineData("ReaderValidationUtils_NullValueForNonNullableType", new object[] { "Value" })]
    [InlineData("ReaderValidationUtils_NullValueForNullableType", new object[] { "Value" })]
    [InlineData("ReaderValidationUtils_ResourceWithoutType", new object[] { })]
    [InlineData("ReaderValidationUtils_TypeInContextUriDoesNotMatchExpectedType", new object[] { "Uri", "ExpectedType", "Value" })]
    [InlineData("ReaderValidationUtils_UndeclaredPropertyBehaviorKindSpecifiedOnRequest", new object[] { })]
    [InlineData("ReaderValidationUtils_ValueTypeNotAllowedInDerivedTypeConstraint", new object[] { "ValueType", "Constraint", "Value" })]
    [InlineData("ReaderValidationUtils_ValueWithoutType", new object[] { })]
    [InlineData("RequestUriProcessor_BatchedActionOnEntityCreatedInSameChangeset", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_CannotApplyEachOnSingleEntities", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_CannotApplyFilterOnSingleEntities", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_CannotQueryCollections", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_ComposableEscapeFunctionShouldHaveValidParameter", new object[] { })]
    [InlineData("RequestUriProcessor_CountNotSupported", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_CountOnRoot", new object[] { })]
    [InlineData("RequestUriProcessor_EachOnRoot", new object[] { })]
    [InlineData("RequestUriProcessor_EmptySegmentInRequestUrl", new object[] { })]
    [InlineData("RequestUriProcessor_EscapeFunctionMustHaveOneStringParameter", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_FilterOnRoot", new object[] { })]
    [InlineData("RequestUriProcessor_FilterPathSegmentSyntaxError", new object[] { })]
    [InlineData("RequestUriProcessor_Forbidden", new object[] { })]
    [InlineData("RequestUriProcessor_FoundInvalidFunctionImport", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_InvalidTypeIdentifier_UnrelatedType", new object[] { "TypeName", "Value" })]
    [InlineData("RequestUriProcessor_InvalidValueForEntitySegment", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_InvalidValueForKeySegment", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_KeysMustBeNamed", new object[] { })]
    [InlineData("RequestUriProcessor_LinkSegmentMustBeFollowedByEntitySegment", new object[] { "SegmentName", "Value" })]
    [InlineData("RequestUriProcessor_MissingSegmentAfterLink", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_MustBeLeafSegment", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_NoBoundEscapeFunctionSupported", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_NoNavigationSourceFound", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_OnlySingleOperationCanFollowEachPathSegment", new object[] { })]
    [InlineData("RequestUriProcessor_OperationSegmentBoundToANonEntityType", new object[] { })]
    [InlineData("RequestUriProcessor_RefOnRoot", new object[] { })]
    [InlineData("RequestUriProcessor_ResourceNotFound", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_SegmentDoesNotSupportKeyPredicates", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_SyntaxError", new object[] { })]
    [InlineData("RequestUriProcessor_TargetEntitySetNotFound", new object[] { "Value" })]
    [InlineData("RequestUriProcessor_ValueSegmentAfterScalarPropertySegment", new object[] { "PropertyName", "Value" })]
    [InlineData("ResourceSetWithoutExpectedTypeValidator_IncompatibleTypes", new object[] { "ResourceSetName", "ExpectedType" })]
    [InlineData("SelectBinder_MultiLevelPathInSelect", new object[] { })]
    [InlineData("SelectedPropertiesNode_StarSegmentAfterTypeSegment", new object[] { })]
    [InlineData("SelectedPropertiesNode_StarSegmentNotLastSegment", new object[] { })]
    [InlineData("SelectExpandBinder_InvalidIdentifierAfterWildcard", new object[] { "Value" })]
    [InlineData("SelectExpandBinder_InvalidQueryOptionNestedSelection", new object[] { "Value" })]
    [InlineData("SelectExpandBinder_NoSegmentAllowedAfterDollarCount", new object[] { "Value" })]
    [InlineData("SelectExpandBinder_NotAllowedDollarCountAsFirstSegment", new object[] { })]
    [InlineData("SelectExpandBinder_NotAllowedDollarCountOnNavigationPropertyInDollarSelect", new object[] { "Value" })]
    [InlineData("SelectExpandBinder_NotAllowedDollarCountOnNonCollection", new object[] { })]
    [InlineData("SelectExpandBinder_SystemTokenInSelect", new object[] { "Value" })]
    [InlineData("SelectExpandBinder_UnknownPropertyType", new object[] { "Value" })]
    [InlineData("SelectExpandPathBinder_FollowNonTypeSegment", new object[] { "Value" })]
    [InlineData("SelectionItemBinder_NoExpandForSelectedProperty", new object[] { "Value" })]
    [InlineData("SelectionItemBinder_NonNavigationPathToken", new object[] { })]
    [InlineData("SelectTreeNormalizer_MultipleSelecTermWithSamePathFound", new object[] { "Value" })]
    [InlineData("ServiceProviderExtensions_NoServiceRegistered", new object[] { "Value" })]
    [InlineData("StreamItemInvalidPrimitiveKind", new object[] { "Value" })]
    [InlineData("StringItemShouldBeQuoted", new object[] { "Value" })]
    [InlineData("SyntacticTree_InvalidCountQueryOptionValue", new object[] { "Value1", "Value2" })]
    [InlineData("SyntacticTree_InvalidIndexQueryOptionValue", new object[] { "Value" })]
    [InlineData("SyntacticTree_InvalidSkipQueryOptionValue", new object[] { "Value" })]
    [InlineData("SyntacticTree_InvalidTopQueryOptionValue", new object[] { "Value" })]
    [InlineData("SyntacticTree_MaxDepthInvalid", new object[] { })]
    [InlineData("SyntacticTree_UriMustBeAbsolute", new object[] { "Value" })]
    [InlineData("TypeUtils_TypeNameIsNotQualified", new object[] { "Value" })]
    [InlineData("UriBuilder_NotSupportedClrLiteral", new object[] { "Value" })]
    [InlineData("UriBuilder_NotSupportedQueryToken", new object[] { "Value" })]
    [InlineData("UriCustomTypeParsers_AddCustomUriTypeParserAlreadyExists", new object[] { })]
    [InlineData("UriCustomTypeParsers_AddCustomUriTypeParserEdmTypeExists", new object[] { "Value" })]
    [InlineData("UriExpandParser_ParentStructuredTypeIsNull", new object[] { "Value" })]
    [InlineData("UriExpandParser_TermIsNotValidForStar", new object[] { "Value" })]
    [InlineData("UriExpandParser_TermIsNotValidForStarRef", new object[] { "Value" })]
    [InlineData("UriExpandParser_TermWithMultipleStarNotAllowed", new object[] { "Value" })]
    [InlineData("UriParser_ContextHandlerCanNotBeNull", new object[] { "Value" })]
    [InlineData("UriParser_EmptyParenthesis", new object[] { })]
    [InlineData("UriParser_ExpandCountExceeded", new object[] { "Value1", "Value2" })]
    [InlineData("UriParser_ExpandDepthExceeded", new object[] { "Value", "Value2" })]
    [InlineData("UriParser_MissingExpandOption", new object[] { "Value" })]
    [InlineData("UriParser_MissingSelectOption", new object[] { "Value" })]
    [InlineData("UriParser_NeedServiceRootForThisOverload", new object[] { })]
    [InlineData("UriParser_NegativeLimit", new object[] { })]
    [InlineData("UriParser_RelativeUriMustBeRelative", new object[] { })]
    [InlineData("UriParser_TypeInvalidForSelectExpand", new object[] { "Value" })]
    [InlineData("UriParser_UriMustBeAbsolute", new object[] { "Value" })]
    [InlineData("UriParserHelper_InvalidPrefixLiteral", new object[] { "Value" })]
    [InlineData("UriParserMetadata_MultipleMatchingKeysFound", new object[] { "Value" })]
    [InlineData("UriParserMetadata_MultipleMatchingNavigationSourcesFound", new object[] { "Value" })]
    [InlineData("UriParserMetadata_MultipleMatchingParametersFound", new object[] { "Value" })]
    [InlineData("UriParserMetadata_MultipleMatchingPropertiesFound", new object[] { "Value1", "Value2" })]
    [InlineData("UriParserMetadata_MultipleMatchingTypesFound", new object[] { "Value" })]
    [InlineData("UriPrimitiveTypeParsers_FailedToParseStringToGeography", new object[] { })]
    [InlineData("UriPrimitiveTypeParsers_FailedToParseTextToPrimitiveValue", new object[] { "Text", "ExpectedType" })]
    [InlineData("UriQueryExpressionParser_AsExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_CannotCreateStarTokenFromNonStar", new object[] { "Value" })]
    [InlineData("UriQueryExpressionParser_CloseParenOrCommaExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_CloseParenOrOperatorExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_ExpressionExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_IllegalQueryOptioninDollarCount", new object[] { })]
    [InlineData("UriQueryExpressionParser_InnerMostExpandRequireFilter", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_KeywordOrIdentifierExpected", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("UriQueryExpressionParser_OpenParenExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_PropertyPathExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryExpressionParser_RangeVariableAlreadyDeclared", new object[] { "Value" })]
    [InlineData("UriQueryExpressionParser_TooDeep", new object[] { })]
    [InlineData("UriQueryExpressionParser_UnrecognizedLiteral", new object[] { "Value1", "Value2", "Value3", "Value4" })]
    [InlineData("UriQueryExpressionParser_UnrecognizedLiteralWithReason", new object[] { "Value1", "Value2", "Value3", "Value4", "Value5" })]
    [InlineData("UriQueryExpressionParser_UnrecognizedWithMethod", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("UriQueryExpressionParser_WithExpected", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryPathParser_InvalidEscapeUri", new object[] { "Value" })]
    [InlineData("UriQueryPathParser_RequestUriDoesNotHaveTheCorrectBaseUri", new object[] { "Value1", "Value2" })]
    [InlineData("UriQueryPathParser_SyntaxError", new object[] { })]
    [InlineData("UriQueryPathParser_TooManySegments", new object[] { })]
    [InlineData("UriSelectParser_InvalidCountOption", new object[] { "Value" })]
    [InlineData("UriSelectParser_InvalidLevelsOption", new object[] { "Value" })]
    [InlineData("UriSelectParser_InvalidSkipOption", new object[] { "Value" })]
    [InlineData("UriSelectParser_InvalidTopOption", new object[] { "Value" })]
    [InlineData("UriSelectParser_SystemTokenInSelectExpand", new object[] { "Value1", "Value2" })]
    [InlineData("UriSelectParser_TermIsNotValid", new object[] { "Value" })]
    [InlineData("UriUtils_DateTimeOffsetInvalidFormat", new object[] { "Value" })]
    [InlineData("UriValidator_ValidatorMustUseSameModelAsParser", new object[] { })]
    [InlineData("ValidationUtils_ActionsAndFunctionsMustSpecifyMetadata", new object[] { "Value" })]
    [InlineData("ValidationUtils_ActionsAndFunctionsMustSpecifyTarget", new object[] { "Value" })]
    [InlineData("ValidationUtils_AssociationLinkMustSpecifyName", new object[] { })]
    [InlineData("ValidationUtils_AssociationLinkMustSpecifyUrl", new object[] { })]
    [InlineData("ValidationUtils_EnumerableContainsANullItem", new object[] { "Value" })]
    [InlineData("ValidationUtils_IncompatiblePrimitiveItemType", new object[] { "Value1", "Value2", "Value3", "Value4" })]
    [InlineData("ValidationUtils_IncompatibleType", new object[] { "Type1", "Type2" })]
    [InlineData("ValidationUtils_IncorrectTypeKind", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ValidationUtils_IncorrectTypeKindNoTypeName", new object[] { "Value1", "Value2" })]
    [InlineData("ValidationUtils_IncorrectValueTypeKind", new object[] { "Value1", "Value2" })]
    [InlineData("ValidationUtils_InvalidBatchBoundaryDelimiterLength", new object[] { "Value1", "Value2" })]
    [InlineData("ValidationUtils_InvalidCollectionTypeName", new object[] { "Value" })]
    [InlineData("ValidationUtils_InvalidCollectionTypeReference", new object[] { "Value" })]
    [InlineData("ValidationUtils_InvalidMetadataReferenceProperty", new object[] { "Value" })]
    [InlineData("ValidationUtils_LinkMustSpecifyName", new object[] { })]
    [InlineData("ValidationUtils_MaxDepthOfNestedEntriesExceeded", new object[] { "Value" })]
    [InlineData("ValidationUtils_MismatchPropertyKindForStreamProperty", new object[] { "Value" })]
    [InlineData("ValidationUtils_NavigationPropertyExpected", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("ValidationUtils_NestedCollectionsAreNotSupported", new object[] { })]
    [InlineData("ValidationUtils_NonNullableCollectionElementsMustNotBeNull", new object[] { })]
    [InlineData("ValidationUtils_NonPrimitiveTypeForPrimitiveValue", new object[] { "Value" })]
    [InlineData("ValidationUtils_NullCollectionItemForNonNullableType", new object[] { "Value" })]
    [InlineData("ValidationUtils_OpenCollectionProperty", new object[] { "Value" })]
    [InlineData("ValidationUtils_OpenStreamProperty", new object[] { "Value" })]
    [InlineData("ValidationUtils_PropertiesMustNotContainReservedChars", new object[] { "Value1", "Value2" })]
    [InlineData("ValidationUtils_PropertyDoesNotExistOnType", new object[] { "PropertyName", "TypeName" })]
    [InlineData("ValidationUtils_RecursionDepthLimitReached", new object[] { "Value" })]
    [InlineData("ValidationUtils_ResourceMustSpecifyName", new object[] { "Value" })]
    [InlineData("ValidationUtils_ResourceMustSpecifyUrl", new object[] { })]
    [InlineData("ValidationUtils_ResourceTypeNotAssignableToExpectedType", new object[] { "ResourceType", "ExpectedType" })]
    [InlineData("ValidationUtils_ResourceWithMediaResourceAndNonMLEType", new object[] { "Value" })]
    [InlineData("ValidationUtils_ResourceWithoutMediaResourceAndMLEType", new object[] { "Value" })]
    [InlineData("ValidationUtils_ServiceDocumentElementUrlMustNotBeNull", new object[] { })]
    [InlineData("ValidationUtils_StreamReferenceValuesNotSupportedInCollections", new object[] { })]
    [InlineData("ValidationUtils_TypeNameMustNotBeEmpty", new object[] { })]
    [InlineData("ValidationUtils_UnrecognizedTypeName", new object[] { "Value" })]
    [InlineData("ValidationUtils_UnsupportedPrimitiveType", new object[] { "Value" })]
    [InlineData("ValidationUtils_WorkspaceResourceMustNotContainNullItem", new object[] { })]
    [InlineData("ValueParser_InvalidDuration", new object[] { "Value" })]
    [InlineData("ValueUtils_CannotConvertValueToPrimitive", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_AssociationLinkInRequest", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_CollectionPropertiesMustNotHaveNullValue", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_DefaultStreamWithContentTypeWithoutReadLink", new object[] { })]
    [InlineData("WriterValidationUtils_DefaultStreamWithReadLinkWithoutContentType", new object[] { })]
    [InlineData("WriterValidationUtils_EntityReferenceLinksLinkMustNotBeNull", new object[] { })]
    [InlineData("WriterValidationUtils_EntityReferenceLinkUrlMustNotBeNull", new object[] { })]
    [InlineData("WriterValidationUtils_EntriesMustHaveNonEmptyId", new object[] { })]
    [InlineData("WriterValidationUtils_ExpandedLinkIsCollectionFalseWithResourceSetContent", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_ExpandedLinkIsCollectionFalseWithResourceSetMetadata", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_ExpandedLinkIsCollectionTrueWithResourceContent", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_ExpandedLinkIsCollectionTrueWithResourceMetadata", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_ExpandedLinkWithResourcePayloadAndResourceSetMetadata", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_ExpandedLinkWithResourceSetPayloadAndResourceMetadata", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_MessageWriterSettingsBaseUriMustBeNullOrAbsolute", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_MessageWriterSettingsJsonPaddingOnRequestMessage", new object[] { })]
    [InlineData("WriterValidationUtils_MessageWriterSettingsServiceDocumentUriMustBeNullOrAbsolute", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_MissingTypeNameWithMetadata", new object[] { })]
    [InlineData("WriterValidationUtils_NavigationLinkMustSpecifyUrl", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_NestedResourceInfoMustSpecifyIsCollection", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_NestedResourceTypeNotCompatibleWithParentPropertyType", new object[] { "ResourceType", "ExpectedType" })]
    [InlineData("WriterValidationUtils_NextPageLinkInRequest", new object[] { })]
    [InlineData("WriterValidationUtils_NonNullablePropertiesMustNotHaveNullValue", new object[] { "Value1", "Value2" })]
    [InlineData("WriterValidationUtils_OperationInRequest", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_PropertiesMustHaveNonEmptyName", new object[] { })]
    [InlineData("WriterValidationUtils_PropertyMustNotBeNull", new object[] { })]
    [InlineData("WriterValidationUtils_StreamPropertiesMustNotHaveNullValue", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_StreamPropertyInRequest", new object[] { "Value" })]
    [InlineData("WriterValidationUtils_StreamReferenceValueEmptyContentType", new object[] { })]
    [InlineData("WriterValidationUtils_StreamReferenceValueMustHaveEditLinkOrReadLink", new object[] { })]
    [InlineData("WriterValidationUtils_StreamReferenceValueMustHaveEditLinkToHaveETag", new object[] { })]
    [InlineData("WriterValidationUtils_ValueTypeNotAllowedInDerivedTypeConstraint", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("XmlReaderExtension_InvalidNodeInStringValue", new object[] { "Value" })]
    [InlineData("XmlReaderExtension_InvalidRootNode", new object[] { "Value" })]
    public void ResourceKey_ShouldFormatWithoutException(string resourceKey, object[] formatArgs)
    {
        // Arrange
        var resourceValue = SRResources.ResourceManager.GetString(resourceKey, SRResources.Culture);

        // Act & Assert
        Assert.NotNull(resourceValue); // Ensure the resource exists

        var exception = Record.Exception(() => string.Format(resourceValue, formatArgs));
        Assert.Null(exception); // Ensure no Exception is thrown

        // Match numbers of arguments required in the resource string and validate against formatArgs
        var matches = Regex.Matches(resourceValue, @"\{\d+\}").Select(m => m.Value).Distinct();
        Assert.Equal(matches.Count(), formatArgs.Length);

        var formattedValue = Error.Format(resourceValue, formatArgs);
        Assert.NotNull(formattedValue);
    }
}