//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/10/2015 2:53:40 PM
namespace DupNames.DSC
{
    /// <summary>
    /// There are no comments for EntityContainer in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EntityContainer")]
    public partial class EntityContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new EntityContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public EntityContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "DupNames.DSC", "DupNames.DSC");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("DupNames.DSC", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("DupNames.DSC.", originalNameAttribute.OriginalName);
                }
                return string.Concat("DupNames.DSC.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Set1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Set1")]
        public global::Microsoft.OData.Client.DataServiceQuery<DupWithTypeName> Set1
        {
            get
            {
                if ((this._Set1 == null))
                {
                    this._Set1 = base.CreateQuery<DupWithTypeName>("Set1");
                }
                return this._Set1;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<DupWithTypeName> _Set1;
        /// <summary>
        /// There are no comments for Set2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Set2")]
        public global::Microsoft.OData.Client.DataServiceQuery<DupWithTypeName1> Set2
        {
            get
            {
                if ((this._Set2 == null))
                {
                    this._Set2 = base.CreateQuery<DupWithTypeName1>("Set2");
                }
                return this._Set2;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<DupWithTypeName1> _Set2;
        /// <summary>
        /// There are no comments for Set1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public void AddToSet1(DupWithTypeName dupWithTypeName)
        {
            base.AddObject("Set1", dupWithTypeName);
        }
        /// <summary>
        /// There are no comments for Set2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public void AddToSet2(DupWithTypeName1 dupWithTypeName1)
        {
            base.AddObject("Set2", dupWithTypeName1);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""DupNames.DSC"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""DupWithTypeName"">
        <Key>
          <PropertyRef Name=""DupWithTypeName"" />
        </Key>
        <Property Name=""DupWithTypeName"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""dupWithTypeName"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""DupWithTypeName1"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""dupWithTypeName1"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DupWithTypeName2"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DupWithTypeName3"" Type=""DupNames.DSC.DupWithComplexTypeName"" Nullable=""false"" />
        <Property Name=""DupPropertyName"" Type=""Edm.Int32"" Nullable=""true"" />
        <NavigationProperty Name=""dupPropertyName"" Type=""Collection(DupNames.DSC.DupWithTypeName1)"" />
      </EntityType>
      <ComplexType Name=""DupWithComplexTypeName"">
        <Property Name=""DupWithComplexTypeName"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""dupWithComplexTypeName"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""DupWithComplexTypeName1"" Type=""Edm.String"" Nullable=""true"" />
        <Property Name=""_DupWithComplexTypeName2"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""__DupWithComplexTypeName2"" Type=""Edm.Int32"" Nullable=""true"" />
      </ComplexType>
      <EntityType Name=""DupWithTypeName1"">
        <Key>
          <PropertyRef Name=""DupWithTypeName"" />
        </Key>
        <Property Name=""dupWithTypeName"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""dupwithtypeName"" Type=""Edm.Guid"" Nullable=""false"" />
        <Property Name=""DupWithTypeName"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""DupWithTypeName1"" Type=""Edm.Int32"" Nullable=""true"" />
        <Property Name=""DupWithTypeName3"" Type=""Edm.Int32"" Nullable=""true"" />
      </EntityType>
      <EntityContainer Name=""EntityContainer"">
        <EntitySet Name=""Set1"" EntityType=""DupNames.DSC.DupWithTypeName"" />
        <EntitySet Name=""Set2"" EntityType=""DupNames.DSC.DupWithTypeName1"">
          <NavigationPropertyBinding Path=""Set1"" Target=""Set1"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.CsdlReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for DupWithTypeNameSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeNameSingle")]
    public partial class DupWithTypeNameSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DupWithTypeName>
    {
        /// <summary>
        /// Initialize a new DupWithTypeNameSingle object.
        /// </summary>
        public DupWithTypeNameSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DupWithTypeNameSingle object.
        /// </summary>
        public DupWithTypeNameSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DupWithTypeNameSingle object.
        /// </summary>
        public DupWithTypeNameSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DupWithTypeName> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for DupPropertyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupPropertyName")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName1> DupPropertyName
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._DupPropertyName == null))
                {
                    this._DupPropertyName = Context.CreateQuery<global::DupNames.DSC.DupWithTypeName1>(GetPath("dupPropertyName"));
                }
                return this._DupPropertyName;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName1> _DupPropertyName;
    }
    /// <summary>
    /// There are no comments for DupWithTypeName in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DupWithTypeName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DupWithTypeName")]
    [global::Microsoft.OData.Client.EntitySet("Set1")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName")]
    public partial class DupWithTypeName : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DupWithTypeName object.
        /// </summary>
        /// <param name="dupWithTypeName4">Initial value of DupWithTypeName4.</param>
        /// <param name="dupWithTypeName1">Initial value of DupWithTypeName1.</param>
        /// <param name="dupWithTypeName11">Initial value of DupWithTypeName11.</param>
        /// <param name="dupWithTypeName2">Initial value of DupWithTypeName2.</param>
        /// <param name="dupWithTypeName3">Initial value of DupWithTypeName3.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static DupWithTypeName CreateDupWithTypeName(global::System.Guid dupWithTypeName4, global::System.Guid dupWithTypeName1, global::System.Guid dupWithTypeName11, global::System.Guid dupWithTypeName2, global::DupNames.DSC.DupWithComplexTypeName dupWithTypeName3)
        {
            DupWithTypeName dupWithTypeName = new DupWithTypeName();
            dupWithTypeName.DupWithTypeName4 = dupWithTypeName4;
            dupWithTypeName.DupWithTypeName1 = dupWithTypeName1;
            dupWithTypeName.DupWithTypeName11 = dupWithTypeName11;
            dupWithTypeName.DupWithTypeName2 = dupWithTypeName2;
            if ((dupWithTypeName3 == null))
            {
                throw new global::System.ArgumentNullException("dupWithTypeName3");
            }
            dupWithTypeName.DupWithTypeName3 = dupWithTypeName3;
            return dupWithTypeName;
        }
        /// <summary>
        /// There are no comments for Property DupWithTypeName4 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName")]
        public global::System.Guid DupWithTypeName4
        {
            get
            {
                return this._DupWithTypeName4;
            }
            set
            {
                this.OnDupWithTypeName4Changing(value);
                this._DupWithTypeName4 = value;
                this.OnDupWithTypeName4Changed();
                this.OnPropertyChanged("DupWithTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupWithTypeName4;
        partial void OnDupWithTypeName4Changing(global::System.Guid value);
        partial void OnDupWithTypeName4Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName5 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupWithTypeName")]
        public global::System.Nullable<int> DupWithTypeName5
        {
            get
            {
                return this._DupWithTypeName5;
            }
            set
            {
                this.OnDupWithTypeName5Changing(value);
                this._DupWithTypeName5 = value;
                this.OnDupWithTypeName5Changed();
                this.OnPropertyChanged("dupWithTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithTypeName5;
        partial void OnDupWithTypeName5Changing(global::System.Nullable<int> value);
        partial void OnDupWithTypeName5Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName1")]
        public global::System.Guid DupWithTypeName1
        {
            get
            {
                return this._DupWithTypeName1;
            }
            set
            {
                this.OnDupWithTypeName1Changing(value);
                this._DupWithTypeName1 = value;
                this.OnDupWithTypeName1Changed();
                this.OnPropertyChanged("DupWithTypeName1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupWithTypeName1;
        partial void OnDupWithTypeName1Changing(global::System.Guid value);
        partial void OnDupWithTypeName1Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName11 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupWithTypeName1")]
        public global::System.Guid DupWithTypeName11
        {
            get
            {
                return this._DupWithTypeName11;
            }
            set
            {
                this.OnDupWithTypeName11Changing(value);
                this._DupWithTypeName11 = value;
                this.OnDupWithTypeName11Changed();
                this.OnPropertyChanged("dupWithTypeName1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupWithTypeName11;
        partial void OnDupWithTypeName11Changing(global::System.Guid value);
        partial void OnDupWithTypeName11Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName2")]
        public global::System.Guid DupWithTypeName2
        {
            get
            {
                return this._DupWithTypeName2;
            }
            set
            {
                this.OnDupWithTypeName2Changing(value);
                this._DupWithTypeName2 = value;
                this.OnDupWithTypeName2Changed();
                this.OnPropertyChanged("DupWithTypeName2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupWithTypeName2;
        partial void OnDupWithTypeName2Changing(global::System.Guid value);
        partial void OnDupWithTypeName2Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName3")]
        public global::DupNames.DSC.DupWithComplexTypeName DupWithTypeName3
        {
            get
            {
                return this._DupWithTypeName3;
            }
            set
            {
                this.OnDupWithTypeName3Changing(value);
                this._DupWithTypeName3 = value;
                this.OnDupWithTypeName3Changed();
                this.OnPropertyChanged("DupWithTypeName3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::DupNames.DSC.DupWithComplexTypeName _DupWithTypeName3;
        partial void OnDupWithTypeName3Changing(global::DupNames.DSC.DupWithComplexTypeName value);
        partial void OnDupWithTypeName3Changed();
        /// <summary>
        /// There are no comments for Property DupPropertyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupPropertyName")]
        public global::System.Nullable<int> DupPropertyName
        {
            get
            {
                return this._DupPropertyName;
            }
            set
            {
                this.OnDupPropertyNameChanging(value);
                this._DupPropertyName = value;
                this.OnDupPropertyNameChanged();
                this.OnPropertyChanged("DupPropertyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupPropertyName;
        partial void OnDupPropertyNameChanging(global::System.Nullable<int> value);
        partial void OnDupPropertyNameChanged();
        /// <summary>
        /// There are no comments for Property DupPropertyName1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupPropertyName")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::DupNames.DSC.DupWithTypeName1> DupPropertyName1
        {
            get
            {
                return this._DupPropertyName1;
            }
            set
            {
                this.OnDupPropertyName1Changing(value);
                this._DupPropertyName1 = value;
                this.OnDupPropertyName1Changed();
                this.OnPropertyChanged("dupPropertyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::DupNames.DSC.DupWithTypeName1> _DupPropertyName1 = new global::Microsoft.OData.Client.DataServiceCollection<global::DupNames.DSC.DupWithTypeName1>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnDupPropertyName1Changing(global::Microsoft.OData.Client.DataServiceCollection<global::DupNames.DSC.DupWithTypeName1> value);
        partial void OnDupPropertyName1Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DupWithComplexTypeName in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithComplexTypeName")]
    public partial class DupWithComplexTypeName : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property DupWithComplexTypeName2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithComplexTypeName")]
        public global::System.Nullable<int> DupWithComplexTypeName2
        {
            get
            {
                return this._DupWithComplexTypeName21;
            }
            set
            {
                this.OnDupWithComplexTypeName2Changing(value);
                this._DupWithComplexTypeName21 = value;
                this.OnDupWithComplexTypeName2Changed();
                this.OnPropertyChanged("DupWithComplexTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithComplexTypeName21;
        partial void OnDupWithComplexTypeName2Changing(global::System.Nullable<int> value);
        partial void OnDupWithComplexTypeName2Changed();
        /// <summary>
        /// There are no comments for Property DupWithComplexTypeName3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupWithComplexTypeName")]
        public global::System.Nullable<int> DupWithComplexTypeName3
        {
            get
            {
                return this._DupWithComplexTypeName3;
            }
            set
            {
                this.OnDupWithComplexTypeName3Changing(value);
                this._DupWithComplexTypeName3 = value;
                this.OnDupWithComplexTypeName3Changed();
                this.OnPropertyChanged("dupWithComplexTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithComplexTypeName3;
        partial void OnDupWithComplexTypeName3Changing(global::System.Nullable<int> value);
        partial void OnDupWithComplexTypeName3Changed();
        /// <summary>
        /// There are no comments for Property DupWithComplexTypeName1 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithComplexTypeName1")]
        public string DupWithComplexTypeName1
        {
            get
            {
                return this._DupWithComplexTypeName1;
            }
            set
            {
                this.OnDupWithComplexTypeName1Changing(value);
                this._DupWithComplexTypeName1 = value;
                this.OnDupWithComplexTypeName1Changed();
                this.OnPropertyChanged("DupWithComplexTypeName1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private string _DupWithComplexTypeName1;
        partial void OnDupWithComplexTypeName1Changing(string value);
        partial void OnDupWithComplexTypeName1Changed();
        /// <summary>
        /// There are no comments for Property _DupWithComplexTypeName2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("_DupWithComplexTypeName2")]
        public global::System.Nullable<int> _DupWithComplexTypeName2
        {
            get
            {
                return this.__DupWithComplexTypeName21;
            }
            set
            {
                this.On_DupWithComplexTypeName2Changing(value);
                this.__DupWithComplexTypeName21 = value;
                this.On_DupWithComplexTypeName2Changed();
                this.OnPropertyChanged("_DupWithComplexTypeName2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> __DupWithComplexTypeName21;
        partial void On_DupWithComplexTypeName2Changing(global::System.Nullable<int> value);
        partial void On_DupWithComplexTypeName2Changed();
        /// <summary>
        /// There are no comments for Property __DupWithComplexTypeName2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("__DupWithComplexTypeName2")]
        public global::System.Nullable<int> __DupWithComplexTypeName2
        {
            get
            {
                return this.___DupWithComplexTypeName2;
            }
            set
            {
                this.On__DupWithComplexTypeName2Changing(value);
                this.___DupWithComplexTypeName2 = value;
                this.On__DupWithComplexTypeName2Changed();
                this.OnPropertyChanged("__DupWithComplexTypeName2");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> ___DupWithComplexTypeName2;
        partial void On__DupWithComplexTypeName2Changing(global::System.Nullable<int> value);
        partial void On__DupWithComplexTypeName2Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DupWithTypeName1Single in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName1Single")]
    public partial class DupWithTypeName1Single : global::Microsoft.OData.Client.DataServiceQuerySingle<DupWithTypeName1>
    {
        /// <summary>
        /// Initialize a new DupWithTypeName1Single object.
        /// </summary>
        public DupWithTypeName1Single(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DupWithTypeName1Single object.
        /// </summary>
        public DupWithTypeName1Single(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DupWithTypeName1Single object.
        /// </summary>
        public DupWithTypeName1Single(global::Microsoft.OData.Client.DataServiceQuerySingle<DupWithTypeName1> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for DupWithTypeName1 in the schema.
    /// </summary>
    /// <KeyProperties>
    /// DupWithTypeName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("DupWithTypeName")]
    [global::Microsoft.OData.Client.EntitySet("Set2")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName1")]
    public partial class DupWithTypeName1 : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DupWithTypeName1 object.
        /// </summary>
        /// <param name="dupWithTypeName2">Initial value of DupWithTypeName2.</param>
        /// <param name="dupwithtypeName">Initial value of DupwithtypeName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static DupWithTypeName1 CreateDupWithTypeName1(global::System.Guid dupWithTypeName2, global::System.Guid dupwithtypeName)
        {
            DupWithTypeName1 dupWithTypeName1 = new DupWithTypeName1();
            dupWithTypeName1.DupWithTypeName2 = dupWithTypeName2;
            dupWithTypeName1.DupwithtypeName = dupwithtypeName;
            return dupWithTypeName1;
        }
        /// <summary>
        /// There are no comments for Property DupWithTypeName2 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupWithTypeName")]
        public global::System.Guid DupWithTypeName2
        {
            get
            {
                return this._DupWithTypeName2;
            }
            set
            {
                this.OnDupWithTypeName2Changing(value);
                this._DupWithTypeName2 = value;
                this.OnDupWithTypeName2Changed();
                this.OnPropertyChanged("dupWithTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupWithTypeName2;
        partial void OnDupWithTypeName2Changing(global::System.Guid value);
        partial void OnDupWithTypeName2Changed();
        /// <summary>
        /// There are no comments for Property DupwithtypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("dupwithtypeName")]
        public global::System.Guid DupwithtypeName
        {
            get
            {
                return this._DupwithtypeName;
            }
            set
            {
                this.OnDupwithtypeNameChanging(value);
                this._DupwithtypeName = value;
                this.OnDupwithtypeNameChanged();
                this.OnPropertyChanged("dupwithtypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Guid _DupwithtypeName;
        partial void OnDupwithtypeNameChanging(global::System.Guid value);
        partial void OnDupwithtypeNameChanged();
        /// <summary>
        /// There are no comments for Property DupWithTypeName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName")]
        public global::System.Nullable<int> DupWithTypeName
        {
            get
            {
                return this._DupWithTypeName;
            }
            set
            {
                this.OnDupWithTypeNameChanging(value);
                this._DupWithTypeName = value;
                this.OnDupWithTypeNameChanged();
                this.OnPropertyChanged("DupWithTypeName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithTypeName;
        partial void OnDupWithTypeNameChanging(global::System.Nullable<int> value);
        partial void OnDupWithTypeNameChanged();
        /// <summary>
        /// There are no comments for Property DupWithTypeName11 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName1")]
        public global::System.Nullable<int> DupWithTypeName11
        {
            get
            {
                return this._DupWithTypeName11;
            }
            set
            {
                this.OnDupWithTypeName11Changing(value);
                this._DupWithTypeName11 = value;
                this.OnDupWithTypeName11Changed();
                this.OnPropertyChanged("DupWithTypeName1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithTypeName11;
        partial void OnDupWithTypeName11Changing(global::System.Nullable<int> value);
        partial void OnDupWithTypeName11Changed();
        /// <summary>
        /// There are no comments for Property DupWithTypeName3 in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DupWithTypeName3")]
        public global::System.Nullable<int> DupWithTypeName3
        {
            get
            {
                return this._DupWithTypeName3;
            }
            set
            {
                this.OnDupWithTypeName3Changing(value);
                this._DupWithTypeName3 = value;
                this.OnDupWithTypeName3Changed();
                this.OnPropertyChanged("DupWithTypeName3");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::System.Nullable<int> _DupWithTypeName3;
        partial void OnDupWithTypeName3Changing(global::System.Nullable<int> value);
        partial void OnDupWithTypeName3Changed();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::DupNames.DSC.DupWithTypeName as global::DupNames.DSC.DupWithTypeNameSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DupNames.DSC.DupWithTypeNameSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DupNames.DSC.DupWithTypeNameSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DupNames.DSC.DupWithTypeName as global::DupNames.DSC.DupWithTypeNameSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="dupWithTypeName">The value of dupWithTypeName</param>
        public static global::DupNames.DSC.DupWithTypeNameSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName> source,
            global::System.Guid dupWithTypeName)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "DupWithTypeName", dupWithTypeName }
            };
            return new global::DupNames.DSC.DupWithTypeNameSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DupNames.DSC.DupWithTypeName1 as global::DupNames.DSC.DupWithTypeName1Single specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::DupNames.DSC.DupWithTypeName1Single ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName1> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::DupNames.DSC.DupWithTypeName1Single(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::DupNames.DSC.DupWithTypeName1 as global::DupNames.DSC.DupWithTypeName1Single specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="dupWithTypeName">The value of dupWithTypeName</param>
        public static global::DupNames.DSC.DupWithTypeName1Single ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::DupNames.DSC.DupWithTypeName1> source,
            global::System.Nullable<int> dupWithTypeName)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "DupWithTypeName", dupWithTypeName }
            };
            return new global::DupNames.DSC.DupWithTypeName1Single(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
