//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2/19/2016 11:59:48 AM
namespace OverrideOperations.DSC
{
    /// <summary>
    /// There are no comments for OverrideOperationsContainer in the schema.
    /// </summary>
    public partial class OverrideOperationsContainer : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new OverrideOperationsContainer object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public OverrideOperationsContainer(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for ETSets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<ET> ETSets
        {
            get
            {
                if ((this._ETSets == null))
                {
                    this._ETSets = base.CreateQuery<ET>("ETSets");
                }
                return this._ETSets;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<ET> _ETSets;
        /// <summary>
        /// There are no comments for ETSets in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public void AddToETSets(ET eT)
        {
            base.AddObject("ETSets", eT);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""OverrideOperations.DSC"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""ET"">
        <Key>
          <PropertyRef Name=""UserName"" />
        </Key>
        <Property Name=""UserName"" Type=""Edm.String"" Nullable=""false"" />
      </EntityType>
      <EntityType Name=""DerivedET"" BaseType=""OverrideOperations.DSC.ET"">
        <Property Name=""DerivedComplexP"" Type=""OverrideOperations.DSC.DerivedCT"" />
      </EntityType>
      <ComplexType Name=""CT"">
        <Property Name=""Name"" Type=""Edm.String"" Nullable=""false"" />
      </ComplexType>
      <ComplexType Name=""DerivedCT"" BaseType=""OverrideOperations.DSC.CT"">
        <Property Name=""Description"" Type=""Edm.String"" Nullable=""false"" />
      </ComplexType>
      <Function Name=""FunctionWithoutParameter"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""OverrideOperations.DSC.ET"" Nullable=""false"" />
        <ReturnType Type=""OverrideOperations.DSC.CT"" Nullable=""false"" />
      </Function>
      <Function Name=""FunctionWithoutParameter"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""OverrideOperations.DSC.DerivedET"" Nullable=""false"" />
        <ReturnType Type=""OverrideOperations.DSC.CT"" Nullable=""false"" />
      </Function>
      <Action Name=""ActionWithParameter"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""OverrideOperations.DSC.ET"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""OverrideOperations.DSC.ET"" Nullable=""false"" />
      </Action>
      <Action Name=""ActionWithParameter"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""OverrideOperations.DSC.DerivedET"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""OverrideOperations.DSC.ET"" Nullable=""false"" />
      </Action>
      <Function Name=""FunctionBoundToCollectionOfEntity"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
      </Function>
      <Function Name=""FunctionBoundToCollectionOfEntity"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""Collection(OverrideOperations.DSC.DerivedET)"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
      </Function>
      <Action Name=""ActionBoundToCollectionOfEntity"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
      </Action>
      <Action Name=""ActionBoundToCollectionOfEntity"" IsBound=""true"">
        <Parameter Name=""entity"" Type=""Collection(OverrideOperations.DSC.DerivedET)"" Nullable=""false"" />
        <Parameter Name=""p1"" Type=""Edm.String"" Nullable=""false"" />
        <ReturnType Type=""Collection(OverrideOperations.DSC.ET)"" Nullable=""false"" />
      </Action>
      <EntityContainer Name=""OverrideOperationsContainer"">
        <EntitySet Name=""ETSets"" EntityType=""OverrideOperations.DSC.ET"">
          <NavigationPropertyBinding Path=""NavP"" Target=""ETSets"" />
        </EntitySet>
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for ETSingle in the schema.
    /// </summary>
    public partial class ETSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<ET>
    {
        /// <summary>
        /// Initialize a new ETSingle object.
        /// </summary>
        public ETSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new ETSingle object.
        /// </summary>
        public ETSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new ETSingle object.
        /// </summary>
        public ETSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<ET> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for ET in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    [global::Microsoft.OData.Client.EntitySet("ETSets")]
    public partial class ET : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new ET object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static ET CreateET(string userName)
        {
            ET eT = new ET();
            eT.UserName = userName;
            return eT;
        }
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
        /// <summary>
        /// There are no comments for FunctionWithoutParameter in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.CT> FunctionWithoutParameter()
        {
            global::System.Uri requestUri;
            Context.TryGetUri(this, out requestUri);

            return this.Context.CreateFunctionQuerySingle<global::OverrideOperations.DSC.CT>(string.Join("/", global::System.Linq.Enumerable.Select(global::System.Linq.Enumerable.Skip(requestUri.Segments, this.Context.BaseUri.Segments.Length), s => s.Trim('/'))), "OverrideOperations.DSC.FunctionWithoutParameter", false);
        }
        /// <summary>
        /// There are no comments for ActionWithParameter in the schema.
        /// </summary>
        public global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET> ActionWithParameter(string p1)
        {
            global::Microsoft.OData.Client.EntityDescriptor resource = Context.EntityTracker.TryGetEntityDescriptor(this);
            if (resource == null)
            {
                throw new global::System.Exception("cannot find entity");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET>(this.Context, resource.EditLink.OriginalString.Trim('/') + "/OverrideOperations.DSC.ActionWithParameter", new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
    }
    /// <summary>
    /// There are no comments for DerivedETSingle in the schema.
    /// </summary>
    public partial class DerivedETSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<DerivedET>
    {
        /// <summary>
        /// Initialize a new DerivedETSingle object.
        /// </summary>
        public DerivedETSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new DerivedETSingle object.
        /// </summary>
        public DerivedETSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new DerivedETSingle object.
        /// </summary>
        public DerivedETSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<DerivedET> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for DerivedET in the schema.
    /// </summary>
    /// <KeyProperties>
    /// UserName
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("UserName")]
    public partial class DerivedET : ET
    {
        /// <summary>
        /// Create a new DerivedET object.
        /// </summary>
        /// <param name="userName">Initial value of UserName.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static DerivedET CreateDerivedET(string userName)
        {
            DerivedET derivedET = new DerivedET();
            derivedET.UserName = userName;
            return derivedET;
        }
        /// <summary>
        /// There are no comments for Property DerivedComplexP in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public global::OverrideOperations.DSC.DerivedCT DerivedComplexP
        {
            get
            {
                return this._DerivedComplexP;
            }
            set
            {
                this.OnDerivedComplexPChanging(value);
                this._DerivedComplexP = value;
                this.OnDerivedComplexPChanged();
                this.OnPropertyChanged("DerivedComplexP");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private global::OverrideOperations.DSC.DerivedCT _DerivedComplexP;
        partial void OnDerivedComplexPChanging(global::OverrideOperations.DSC.DerivedCT value);
        partial void OnDerivedComplexPChanged();
        /// <summary>
        /// There are no comments for FunctionWithoutParameter in the schema.
        /// </summary>
        public new global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.CT> FunctionWithoutParameter()
        {
            global::System.Uri requestUri;
            Context.TryGetUri(this, out requestUri);

            return this.Context.CreateFunctionQuerySingle<global::OverrideOperations.DSC.CT>(string.Join("/", global::System.Linq.Enumerable.Select(global::System.Linq.Enumerable.Skip(requestUri.Segments, this.Context.BaseUri.Segments.Length), s => s.Trim('/'))), "OverrideOperations.DSC.FunctionWithoutParameter", false);
        }
        /// <summary>
        /// There are no comments for ActionWithParameter in the schema.
        /// </summary>
        public new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET> ActionWithParameter(string p1)
        {
            global::Microsoft.OData.Client.EntityDescriptor resource = Context.EntityTracker.TryGetEntityDescriptor(this);
            if (resource == null)
            {
                throw new global::System.Exception("cannot find entity");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET>(this.Context, resource.EditLink.OriginalString.Trim('/') + "/OverrideOperations.DSC.ActionWithParameter", new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
    }
    /// <summary>
    /// There are no comments for CT in the schema.
    /// </summary>
    public partial class CT : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CT object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static CT CreateCT(string name)
        {
            CT cT = new CT();
            cT.Name = name;
            return cT;
        }
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for DerivedCT in the schema.
    /// </summary>
    public partial class DerivedCT : CT
    {
        /// <summary>
        /// Create a new DerivedCT object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="description">Initial value of Description.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public static DerivedCT CreateDerivedCT(string name, string description)
        {
            DerivedCT derivedCT = new DerivedCT();
            derivedCT.Name = name;
            derivedCT.Description = description;
            return derivedCT;
        }
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.Design.T4", "2.2.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::OverrideOperations.DSC.ET as global::OverrideOperations.DSC.ETSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::OverrideOperations.DSC.ETSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::OverrideOperations.DSC.ETSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::OverrideOperations.DSC.ET as global::OverrideOperations.DSC.ETSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::OverrideOperations.DSC.ETSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> source,
            string userName)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::OverrideOperations.DSC.ETSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::OverrideOperations.DSC.DerivedET as global::OverrideOperations.DSC.DerivedETSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::OverrideOperations.DSC.DerivedETSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.DerivedET> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::OverrideOperations.DSC.DerivedETSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::OverrideOperations.DSC.DerivedET as global::OverrideOperations.DSC.DerivedETSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="userName">The value of userName</param>
        public static global::OverrideOperations.DSC.DerivedETSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.DerivedET> source,
            string userName)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "UserName", userName }
            };
            return new global::OverrideOperations.DSC.DerivedETSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Cast an entity of type global::OverrideOperations.DSC.ET to its derived type global::OverrideOperations.DSC.DerivedET
        /// </summary>
        /// <param name="source">source entity</param>
        public static global::OverrideOperations.DSC.DerivedETSingle CastToDerivedET(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.ET> source)
        {
            global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.DerivedET> query = source.CastTo<global::OverrideOperations.DSC.DerivedET>();
            return new global::OverrideOperations.DSC.DerivedETSingle(source.Context, query.GetPath(null));
        }
        /// <summary>
        /// There are no comments for FunctionWithoutParameter in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.CT> FunctionWithoutParameter(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.ET> source)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuerySingle<global::OverrideOperations.DSC.CT>("OverrideOperations.DSC.FunctionWithoutParameter", false);
        }
        /// <summary>
        /// There are no comments for FunctionWithoutParameter in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.CT> FunctionWithoutParameter(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.DerivedET> source)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuerySingle<global::OverrideOperations.DSC.CT>("OverrideOperations.DSC.FunctionWithoutParameter", false);
        }
        /// <summary>
        /// There are no comments for FunctionBoundToCollectionOfEntity in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> FunctionBoundToCollectionOfEntity(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuery<global::OverrideOperations.DSC.ET>("OverrideOperations.DSC.FunctionBoundToCollectionOfEntity", false, new global::Microsoft.OData.Client.UriOperationParameter("p1", p1));
        }
        /// <summary>
        /// There are no comments for FunctionBoundToCollectionOfEntity in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> FunctionBoundToCollectionOfEntity(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.DerivedET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return source.CreateFunctionQuery<global::OverrideOperations.DSC.ET>("OverrideOperations.DSC.FunctionBoundToCollectionOfEntity", false, new global::Microsoft.OData.Client.UriOperationParameter("p1", p1));
        }
        /// <summary>
        /// There are no comments for ActionWithParameter in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET> ActionWithParameter(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.ET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET>(source.Context, source.AppendRequestUri("OverrideOperations.DSC.ActionWithParameter"), new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
        /// <summary>
        /// There are no comments for ActionWithParameter in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET> ActionWithParameter(this global::Microsoft.OData.Client.DataServiceQuerySingle<global::OverrideOperations.DSC.DerivedET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuerySingle<global::OverrideOperations.DSC.ET>(source.Context, source.AppendRequestUri("OverrideOperations.DSC.ActionWithParameter"), new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
        /// <summary>
        /// There are no comments for ActionBoundToCollectionOfEntity in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuery<global::OverrideOperations.DSC.ET> ActionBoundToCollectionOfEntity(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.ET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::OverrideOperations.DSC.ET>(source.Context, source.AppendRequestUri("OverrideOperations.DSC.ActionBoundToCollectionOfEntity"), new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
        /// <summary>
        /// There are no comments for ActionBoundToCollectionOfEntity in the schema.
        /// </summary>
        public static global::Microsoft.OData.Client.DataServiceActionQuery<global::OverrideOperations.DSC.ET> ActionBoundToCollectionOfEntity(this global::Microsoft.OData.Client.DataServiceQuery<global::OverrideOperations.DSC.DerivedET> source, string p1)
        {
            if (!source.IsComposable)
            {
                throw new global::System.NotSupportedException("The previous function is not composable.");
            }

            return new global::Microsoft.OData.Client.DataServiceActionQuery<global::OverrideOperations.DSC.ET>(source.Context, source.AppendRequestUri("OverrideOperations.DSC.ActionBoundToCollectionOfEntity"), new global::Microsoft.OData.Client.BodyOperationParameter("p1", p1));
        }
    }
}
