//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 1/19/2020 3:25:01 PM
namespace SimpleMultipleFiles
{
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::SimpleMultipleFiles.TestType as global::SimpleMultipleFiles.TestTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::SimpleMultipleFiles.TestTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SimpleMultipleFiles.TestType> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::SimpleMultipleFiles.TestTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::SimpleMultipleFiles.TestType as global::SimpleMultipleFiles.TestTypeSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keyProp">The value of keyProp</param>
        public static global::SimpleMultipleFiles.TestTypeSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::SimpleMultipleFiles.TestType> source,
            int keyProp)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "KeyProp", keyProp }
            };
            return new global::SimpleMultipleFiles.TestTypeSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}