namespace __GeneratedOdata.Parsers.Rules
{
    using Sprache;
    
    public static class _boundOperationParser
    {
        public static Parser<__GeneratedOdata.CstNodes.Rules._boundOperation> Instance { get; } = from _ʺx2Fʺ_1 in __GeneratedOdata.Parsers.Inners._ʺx2FʺParser.Instance
from _ⲤboundActionCallⳆboundEntityColFunctionCall_꘡collectionNavigation꘡ⳆboundEntityFunctionCall_꘡singleNavigation꘡ⳆboundComplexColFunctionCall_꘡complexColPath꘡ⳆboundComplexFunctionCall_꘡complexPath꘡ⳆboundPrimitiveColFunctionCall_꘡primitiveColPath꘡ⳆboundPrimitiveFunctionCall_꘡primitivePath꘡ⳆboundFunctionCallNoParensↃ_1 in __GeneratedOdata.Parsers.Inners._ⲤboundActionCallⳆboundEntityColFunctionCall_꘡collectionNavigation꘡ⳆboundEntityFunctionCall_꘡singleNavigation꘡ⳆboundComplexColFunctionCall_꘡complexColPath꘡ⳆboundComplexFunctionCall_꘡complexPath꘡ⳆboundPrimitiveColFunctionCall_꘡primitiveColPath꘡ⳆboundPrimitiveFunctionCall_꘡primitivePath꘡ⳆboundFunctionCallNoParensↃParser.Instance
select new __GeneratedOdata.CstNodes.Rules._boundOperation(_ʺx2Fʺ_1, _ⲤboundActionCallⳆboundEntityColFunctionCall_꘡collectionNavigation꘡ⳆboundEntityFunctionCall_꘡singleNavigation꘡ⳆboundComplexColFunctionCall_꘡complexColPath꘡ⳆboundComplexFunctionCall_꘡complexPath꘡ⳆboundPrimitiveColFunctionCall_꘡primitiveColPath꘡ⳆboundPrimitiveFunctionCall_꘡primitivePath꘡ⳆboundFunctionCallNoParensↃ_1);
    }
    
}
