//   Copyright 2011 Microsoft Corporation
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.

namespace Microsoft.Data.OData {
    using System;
    using System.Reflection;
    using System.Globalization;
    using System.Resources;
    using System.Text;
    using System.Threading;
    using System.Security.Permissions;

    
    using System.ComponentModel;

    [AttributeUsage(AttributeTargets.All)]
    internal sealed class TextResDescriptionAttribute : DescriptionAttribute {

        private bool replaced = false;

        /// <summary>
        ///     Constructs a new sys description.
        /// </summary>
        /// <param name='description'>
        ///     description text.
        /// </param>
        public TextResDescriptionAttribute(string description) : base(description) {
        }

        /// <summary>
        ///     Retrieves the description text.
        /// </summary>
        /// <returns>
        ///     description
        /// </returns>
        public override string Description {
            get {
                if (!replaced) {
                    replaced = true;
                    DescriptionValue = TextRes.GetString(base.Description);
                }
                return base.Description;
            }
        }
    }

    [AttributeUsage(AttributeTargets.All)]
    internal sealed class TextResCategoryAttribute : CategoryAttribute {

        public TextResCategoryAttribute(string category) : base(category) {
        }

        protected override string GetLocalizedString(string value) {
            return TextRes.GetString(value);
        }
    }


    /// <summary>
    ///    AutoGenerated resource class. Usage:
    ///
    ///        string s = TextRes.GetString(TextRes.MyIdenfitier);
    /// </summary>
    
    internal sealed class TextRes {
        internal const string General_InternalError = "General_InternalError";
        internal const string ODataRequestMessage_AsyncNotAvailable = "ODataRequestMessage_AsyncNotAvailable";
        internal const string ODataRequestMessage_StreamTaskIsNull = "ODataRequestMessage_StreamTaskIsNull";
        internal const string ODataRequestMessage_MessageStreamIsNull = "ODataRequestMessage_MessageStreamIsNull";
        internal const string ODataResponseMessage_AsyncNotAvailable = "ODataResponseMessage_AsyncNotAvailable";
        internal const string ODataResponseMessage_StreamTaskIsNull = "ODataResponseMessage_StreamTaskIsNull";
        internal const string ODataResponseMessage_MessageStreamIsNull = "ODataResponseMessage_MessageStreamIsNull";
        internal const string AsyncBufferedStream_WriterDisposedWithoutFlush = "AsyncBufferedStream_WriterDisposedWithoutFlush";
        internal const string ODataWriter_RelativeUriUsedWithoutBaseUriSpecified = "ODataWriter_RelativeUriUsedWithoutBaseUriSpecified";
        internal const string ODataWriter_NavigationLinkMustSpecifyUrl = "ODataWriter_NavigationLinkMustSpecifyUrl";
        internal const string ODataWriter_CannotCreateWriterForFormat = "ODataWriter_CannotCreateWriterForFormat";
        internal const string ODataWriter_NamedStreamPropertiesMustBePropertiesOfODataEntry = "ODataWriter_NamedStreamPropertiesMustBePropertiesOfODataEntry";
        internal const string ODataWriterCore_FeedExpandedLinkWithEntryContent = "ODataWriterCore_FeedExpandedLinkWithEntryContent";
        internal const string ODataWriterCore_EntryExpandedLinkWithFeedContent = "ODataWriterCore_EntryExpandedLinkWithFeedContent";
        internal const string ODataWriterCore_InvalidStateTransition = "ODataWriterCore_InvalidStateTransition";
        internal const string ODataWriterCore_InvalidTransitionFromStart = "ODataWriterCore_InvalidTransitionFromStart";
        internal const string ODataWriterCore_InvalidTransitionFromEntry = "ODataWriterCore_InvalidTransitionFromEntry";
        internal const string ODataWriterCore_InvalidTransitionFromNullEntry = "ODataWriterCore_InvalidTransitionFromNullEntry";
        internal const string ODataWriterCore_InvalidTransitionFromFeed = "ODataWriterCore_InvalidTransitionFromFeed";
        internal const string ODataWriterCore_InvalidTransitionFromExpandedLink = "ODataWriterCore_InvalidTransitionFromExpandedLink";
        internal const string ODataWriterCore_InvalidTransitionFromCompleted = "ODataWriterCore_InvalidTransitionFromCompleted";
        internal const string ODataWriterCore_InvalidTransitionFromError = "ODataWriterCore_InvalidTransitionFromError";
        internal const string ODataWriterCore_WriteEndCalledInInvalidState = "ODataWriterCore_WriteEndCalledInInvalidState";
        internal const string ODataWriterCore_OnlyTopLevelFeedsSupportInlineCount = "ODataWriterCore_OnlyTopLevelFeedsSupportInlineCount";
        internal const string ODataWriterCore_InlineCountInRequest = "ODataWriterCore_InlineCountInRequest";
        internal const string ODataWriterCore_CannotWriteTopLevelFeedWithEntryWriter = "ODataWriterCore_CannotWriteTopLevelFeedWithEntryWriter";
        internal const string ODataWriterCore_CannotWriteTopLevelEntryWithFeedWriter = "ODataWriterCore_CannotWriteTopLevelEntryWithFeedWriter";
        internal const string ODataWriterCore_SyncCallOnAsyncWriter = "ODataWriterCore_SyncCallOnAsyncWriter";
        internal const string ODataWriterCore_AsyncCallOnSyncWriter = "ODataWriterCore_AsyncCallOnSyncWriter";
        internal const string DuplicatePropertyNamesChecker_DuplicatePropertyNamesNotAllowed = "DuplicatePropertyNamesChecker_DuplicatePropertyNamesNotAllowed";
        internal const string DuplicatePropertyNamesChecker_MultipleExpandedLinks = "DuplicatePropertyNamesChecker_MultipleExpandedLinks";
        internal const string DuplicatePropertyNamesChecker_MultipleLinksForSingleton = "DuplicatePropertyNamesChecker_MultipleLinksForSingleton";
        internal const string AtomValueUtils_CannotConvertValueToAtomPrimitive = "AtomValueUtils_CannotConvertValueToAtomPrimitive";
        internal const string ODataJsonWriter_UnsupportedValueType = "ODataJsonWriter_UnsupportedValueType";
        internal const string ODataException_GeneralError = "ODataException_GeneralError";
        internal const string ODataErrorException_GeneralError = "ODataErrorException_GeneralError";
        internal const string ODataVersionChecker_ActionsAndFunctionsNotSupported = "ODataVersionChecker_ActionsAndFunctionsNotSupported";
        internal const string ODataVersionChecker_AssociationLinksNotSupported = "ODataVersionChecker_AssociationLinksNotSupported";
        internal const string ODataVersionChecker_InlineCountNotSupported = "ODataVersionChecker_InlineCountNotSupported";
        internal const string ODataVersionChecker_NextLinkNotSupported = "ODataVersionChecker_NextLinkNotSupported";
        internal const string ODataVersionChecker_MultiValuePropertiesNotSupported = "ODataVersionChecker_MultiValuePropertiesNotSupported";
        internal const string ODataVersionChecker_NamedStreamsNotSupported = "ODataVersionChecker_NamedStreamsNotSupported";
        internal const string ODataVersionChecker_EpmVersionNotSupported = "ODataVersionChecker_EpmVersionNotSupported";
        internal const string ODataVersionChecker_ProtocolVersion3IsNotSupported = "ODataVersionChecker_ProtocolVersion3IsNotSupported";
        internal const string ODataAtomCollectionWriter_CollectionNameMustNotBeNull = "ODataAtomCollectionWriter_CollectionNameMustNotBeNull";
        internal const string ODataAtomWriter_StartEntryXmlCustomizationCallbackReturnedSameInstance = "ODataAtomWriter_StartEntryXmlCustomizationCallbackReturnedSameInstance";
        internal const string ODataAtomWriter_AtomLinkMustSpecifyIsCollection = "ODataAtomWriter_AtomLinkMustSpecifyIsCollection";
        internal const string ODataAtomWriterMetadataUtils_AuthorMetadataMustNotContainNull = "ODataAtomWriterMetadataUtils_AuthorMetadataMustNotContainNull";
        internal const string ODataAtomWriterMetadataUtils_CategoryMetadataMustNotContainNull = "ODataAtomWriterMetadataUtils_CategoryMetadataMustNotContainNull";
        internal const string ODataAtomWriterMetadataUtils_ContributorMetadataMustNotContainNull = "ODataAtomWriterMetadataUtils_ContributorMetadataMustNotContainNull";
        internal const string ODataAtomWriterMetadataUtils_LinkMetadataMustNotContainNull = "ODataAtomWriterMetadataUtils_LinkMetadataMustNotContainNull";
        internal const string ODataAtomWriterMetadataUtils_LinkMustSpecifyHref = "ODataAtomWriterMetadataUtils_LinkMustSpecifyHref";
        internal const string ODataAtomWriterMetadataUtils_CategoryMustSpecifyTerm = "ODataAtomWriterMetadataUtils_CategoryMustSpecifyTerm";
        internal const string ODataAtomWriterMetadataUtils_LinkHrefsMustMatch = "ODataAtomWriterMetadataUtils_LinkHrefsMustMatch";
        internal const string ODataAtomWriterMetadataUtils_LinkTitlesMustMatch = "ODataAtomWriterMetadataUtils_LinkTitlesMustMatch";
        internal const string ODataAtomWriterMetadataUtils_LinkRelationsMustMatch = "ODataAtomWriterMetadataUtils_LinkRelationsMustMatch";
        internal const string ODataAtomWriterMetadataUtils_LinkMediaTypesMustMatch = "ODataAtomWriterMetadataUtils_LinkMediaTypesMustMatch";
        internal const string ODataAtomWriterMetadataUtils_InvalidAnnotationValue = "ODataAtomWriterMetadataUtils_InvalidAnnotationValue";
        internal const string ODataAtomWriterMetadataUtils_CategoriesHrefWithOtherValues = "ODataAtomWriterMetadataUtils_CategoriesHrefWithOtherValues";
        internal const string ODataAtomMetadataEpmMerge_TextKindConflict = "ODataAtomMetadataEpmMerge_TextKindConflict";
        internal const string ODataAtomMetadataEpmMerge_TextValueConflict = "ODataAtomMetadataEpmMerge_TextValueConflict";
        internal const string ODataMessageWriter_WriterAlreadyUsed = "ODataMessageWriter_WriterAlreadyUsed";
        internal const string ODataMessageWriter_InvalidAcceptHeaderForWritingRawValue = "ODataMessageWriter_InvalidAcceptHeaderForWritingRawValue";
        internal const string ODataMessageWriter_InvalidContentTypeForWritingRawValue = "ODataMessageWriter_InvalidContentTypeForWritingRawValue";
        internal const string ODataMessageWriter_NextPageLinkInRequest = "ODataMessageWriter_NextPageLinkInRequest";
        internal const string ODataMessageWriter_InlineCountInRequest = "ODataMessageWriter_InlineCountInRequest";
        internal const string ODataMessageWriter_ErrorPayloadInRequest = "ODataMessageWriter_ErrorPayloadInRequest";
        internal const string ODataMessageWriter_ServiceDocumentInRequest = "ODataMessageWriter_ServiceDocumentInRequest";
        internal const string ODataMessageWriter_MetadataDocumentInRequest = "ODataMessageWriter_MetadataDocumentInRequest";
        internal const string ODataMessageWriter_CannotWriteNullInRawFormat = "ODataMessageWriter_CannotWriteNullInRawFormat";
        internal const string ODataMessageWriter_CannotSetHeadersWithInvalidPayloadKind = "ODataMessageWriter_CannotSetHeadersWithInvalidPayloadKind";
        internal const string ODataMessageWriter_CannotSetMimeTypeWithInvalidPayloadKind = "ODataMessageWriter_CannotSetMimeTypeWithInvalidPayloadKind";
        internal const string ODataMessageWriter_IncompatiblePayloadKinds = "ODataMessageWriter_IncompatiblePayloadKinds";
        internal const string ODataMessageWriter_CannotWriteStreamPropertyAsTopLevelProperty = "ODataMessageWriter_CannotWriteStreamPropertyAsTopLevelProperty";
        internal const string ODataMessageWriter_WriteErrorAlreadyCalled = "ODataMessageWriter_WriteErrorAlreadyCalled";
        internal const string ODataMessageWriter_CannotWriteInStreamErrorForRawValues = "ODataMessageWriter_CannotWriteInStreamErrorForRawValues";
        internal const string ODataMessageWriter_CannotWriteMetadataWithoutModel = "ODataMessageWriter_CannotWriteMetadataWithoutModel";
        internal const string ODataMessageWriterSettings_MessageWriterSettingsXmlCustomizationCallbacksMustBeSpecifiedBoth = "ODataMessageWriterSettings_MessageWriterSettingsXmlCustomizationCallbacksMustBeSpecifiedBoth";
        internal const string ODataCollectionWriter_CannotCreateCollectionWriterForFormat = "ODataCollectionWriter_CannotCreateCollectionWriterForFormat";
        internal const string ODataCollectionWriterCore_InvalidTransitionFromStart = "ODataCollectionWriterCore_InvalidTransitionFromStart";
        internal const string ODataCollectionWriterCore_InvalidTransitionFromCollection = "ODataCollectionWriterCore_InvalidTransitionFromCollection";
        internal const string ODataCollectionWriterCore_InvalidTransitionFromItem = "ODataCollectionWriterCore_InvalidTransitionFromItem";
        internal const string ODataCollectionWriterCore_WriteEndCalledInInvalidState = "ODataCollectionWriterCore_WriteEndCalledInInvalidState";
        internal const string ODataCollectionWriterCore_SyncCallOnAsyncWriter = "ODataCollectionWriterCore_SyncCallOnAsyncWriter";
        internal const string ODataCollectionWriterCore_AsyncCallOnSyncWriter = "ODataCollectionWriterCore_AsyncCallOnSyncWriter";
        internal const string ODataCollectionWriterCore_CollectionsMustNotHaveEmptyName = "ODataCollectionWriterCore_CollectionsMustNotHaveEmptyName";
        internal const string ODataBatchWriter_FlushOrFlushAsyncCalledInStreamRequestedState = "ODataBatchWriter_FlushOrFlushAsyncCalledInStreamRequestedState";
        internal const string ODataBatchWriter_CannotCompleteBatchWithActiveChangeSet = "ODataBatchWriter_CannotCompleteBatchWithActiveChangeSet";
        internal const string ODataBatchWriter_CannotStartChangeSetWithActiveChangeSet = "ODataBatchWriter_CannotStartChangeSetWithActiveChangeSet";
        internal const string ODataBatchWriter_CannotCompleteChangeSetWithoutActiveChangeSet = "ODataBatchWriter_CannotCompleteChangeSetWithoutActiveChangeSet";
        internal const string ODataBatchWriter_InvalidTransitionFromStart = "ODataBatchWriter_InvalidTransitionFromStart";
        internal const string ODataBatchWriter_InvalidTransitionFromBatchStarted = "ODataBatchWriter_InvalidTransitionFromBatchStarted";
        internal const string ODataBatchWriter_InvalidTransitionFromChangeSetStarted = "ODataBatchWriter_InvalidTransitionFromChangeSetStarted";
        internal const string ODataBatchWriter_InvalidTransitionFromOperationCreated = "ODataBatchWriter_InvalidTransitionFromOperationCreated";
        internal const string ODataBatchWriter_InvalidTransitionFromOperationContentStreamRequested = "ODataBatchWriter_InvalidTransitionFromOperationContentStreamRequested";
        internal const string ODataBatchWriter_InvalidTransitionFromOperationContentStreamDisposed = "ODataBatchWriter_InvalidTransitionFromOperationContentStreamDisposed";
        internal const string ODataBatchWriter_InvalidTransitionFromChangeSetCompleted = "ODataBatchWriter_InvalidTransitionFromChangeSetCompleted";
        internal const string ODataBatchWriter_InvalidTransitionFromBatchCompleted = "ODataBatchWriter_InvalidTransitionFromBatchCompleted";
        internal const string ODataBatchWriter_CannotCreateRequestOperationWhenWritingResponse = "ODataBatchWriter_CannotCreateRequestOperationWhenWritingResponse";
        internal const string ODataBatchWriter_CannotCreateResponseOperationWhenWritingRequest = "ODataBatchWriter_CannotCreateResponseOperationWhenWritingRequest";
        internal const string ODataBatchWriter_InvalidHttpMethodForQueryOperation = "ODataBatchWriter_InvalidHttpMethodForQueryOperation";
        internal const string ODataBatchWriter_InvalidHttpMethodForChangeSetRequest = "ODataBatchWriter_InvalidHttpMethodForChangeSetRequest";
        internal const string ODataBatchWriter_MaxBatchSizeExceeded = "ODataBatchWriter_MaxBatchSizeExceeded";
        internal const string ODataBatchWriter_MaxChangeSetSizeExceeded = "ODataBatchWriter_MaxChangeSetSizeExceeded";
        internal const string ODataBatchWriter_SyncCallOnAsyncWriter = "ODataBatchWriter_SyncCallOnAsyncWriter";
        internal const string ODataBatchWriter_AsyncCallOnSyncWriter = "ODataBatchWriter_AsyncCallOnSyncWriter";
        internal const string ODataBatchWriter_DuplicateContentIDsNotAllowed = "ODataBatchWriter_DuplicateContentIDsNotAllowed";
        internal const string ODataBatchWriterUtils_RelativeUriUsedWithoutBaseUriSpecified = "ODataBatchWriterUtils_RelativeUriUsedWithoutBaseUriSpecified";
        internal const string ODataBatchOperationMessage_VerifyNotCompleted = "ODataBatchOperationMessage_VerifyNotCompleted";
        internal const string ODataBatchOperationStream_Disposed = "ODataBatchOperationStream_Disposed";
        internal const string HttpUtils_MediaTypeUnspecified = "HttpUtils_MediaTypeUnspecified";
        internal const string HttpUtils_MediaTypeRequiresSlash = "HttpUtils_MediaTypeRequiresSlash";
        internal const string HttpUtils_MediaTypeRequiresSubType = "HttpUtils_MediaTypeRequiresSubType";
        internal const string HttpUtils_MediaTypeMissingParameterValue = "HttpUtils_MediaTypeMissingParameterValue";
        internal const string HttpUtils_MediaTypeMissingParameterName = "HttpUtils_MediaTypeMissingParameterName";
        internal const string HttpUtils_EscapeCharWithoutQuotes = "HttpUtils_EscapeCharWithoutQuotes";
        internal const string HttpUtils_EscapeCharAtEnd = "HttpUtils_EscapeCharAtEnd";
        internal const string HttpUtils_ClosingQuoteNotFound = "HttpUtils_ClosingQuoteNotFound";
        internal const string HttpUtils_ContentTypeMissing = "HttpUtils_ContentTypeMissing";
        internal const string HttpUtils_MediaTypeRequiresSemicolonBeforeParameter = "HttpUtils_MediaTypeRequiresSemicolonBeforeParameter";
        internal const string HttpUtils_InvalidQualityValueStartChar = "HttpUtils_InvalidQualityValueStartChar";
        internal const string HttpUtils_InvalidQualityValue = "HttpUtils_InvalidQualityValue";
        internal const string HttpUtils_CannotConvertCharToInt = "HttpUtils_CannotConvertCharToInt";
        internal const string HttpUtils_MissingSeparatorBetweenCharsets = "HttpUtils_MissingSeparatorBetweenCharsets";
        internal const string HttpUtils_InvalidSeparatorBetweenCharsets = "HttpUtils_InvalidSeparatorBetweenCharsets";
        internal const string HttpUtils_InvalidCharsetName = "HttpUtils_InvalidCharsetName";
        internal const string HttpUtils_UnexpectedEndOfQValue = "HttpUtils_UnexpectedEndOfQValue";
        internal const string HttpUtils_ExpectedLiteralNotFoundInString = "HttpUtils_ExpectedLiteralNotFoundInString";
        internal const string MediaType_EncodingNotSupported = "MediaType_EncodingNotSupported";
        internal const string MediaTypeUtils_DidNotFindMatchingMediaType = "MediaTypeUtils_DidNotFindMatchingMediaType";
        internal const string MediaTypeUtils_CannotDetermineFormatFromContentType = "MediaTypeUtils_CannotDetermineFormatFromContentType";
        internal const string MediaTypeUtils_NoOrMoreThanOneContentTypeSpecified = "MediaTypeUtils_NoOrMoreThanOneContentTypeSpecified";
        internal const string EntityPropertyMapping_EpmAttribute = "EntityPropertyMapping_EpmAttribute";
        internal const string EntityPropertyMapping_LeadingAndTrialingWhitespacesNotAllowedOnCriteriaValue = "EntityPropertyMapping_LeadingAndTrialingWhitespacesNotAllowedOnCriteriaValue";
        internal const string EntityPropertyMapping_InvalidTargetPath = "EntityPropertyMapping_InvalidTargetPath";
        internal const string EntityPropertyMapping_TargetNamespaceUriNotValid = "EntityPropertyMapping_TargetNamespaceUriNotValid";
        internal const string EpmSourceTree_InvalidSourcePath = "EpmSourceTree_InvalidSourcePath";
        internal const string EpmSourceTree_NestedMultiValue = "EpmSourceTree_NestedMultiValue";
        internal const string EpmSourceTree_MultiValueNotAllowedInCustomMapping = "EpmSourceTree_MultiValueNotAllowedInCustomMapping";
        internal const string EpmSourceTree_PropertiesFromSameMultiValueMappedToDifferentTopLevelElements = "EpmSourceTree_PropertiesFromSameMultiValueMappedToDifferentTopLevelElements";
        internal const string EpmSourceTree_PropertiesFromSameMultiValueMappedWithDifferentKeepInContent = "EpmSourceTree_PropertiesFromSameMultiValueMappedWithDifferentKeepInContent";
        internal const string EpmSourceTree_EndsWithNonPrimitiveType = "EpmSourceTree_EndsWithNonPrimitiveType";
        internal const string EpmSourceTree_TraversalOfNonComplexType = "EpmSourceTree_TraversalOfNonComplexType";
        internal const string EpmSourceTree_DuplicateEpmAttributesWithSameSourceName = "EpmSourceTree_DuplicateEpmAttributesWithSameSourceName";
        internal const string EpmSourceTree_NotAllMultiValueItemPropertiesMapped = "EpmSourceTree_NotAllMultiValueItemPropertiesMapped";
        internal const string EpmSourceTree_MultiValueOfPrimitiveMappedToLinkWithoutCriteria = "EpmSourceTree_MultiValueOfPrimitiveMappedToLinkWithoutCriteria";
        internal const string EpmSourceTree_MultiValueOfComplexTypesDifferentConditionalMapping = "EpmSourceTree_MultiValueOfComplexTypesDifferentConditionalMapping";
        internal const string EpmSourceTree_ConditionalMappingInvalidLinkRelCriteriaValue = "EpmSourceTree_ConditionalMappingInvalidLinkRelCriteriaValue";
        internal const string EpmSourceTree_ConditionalMappingInvalidCategorySchemeCriteriaValue = "EpmSourceTree_ConditionalMappingInvalidCategorySchemeCriteriaValue";
        internal const string EpmSourceTree_MissingPropertyOnType = "EpmSourceTree_MissingPropertyOnType";
        internal const string EpmSourceTree_MissingPropertyOnInstance = "EpmSourceTree_MissingPropertyOnInstance";
        internal const string EpmSourceTree_NonStringPropertyMappedToConditionAttribute = "EpmSourceTree_NonStringPropertyMappedToConditionAttribute";
        internal const string EpmSourceTree_NamedStreamCannotBeMapped = "EpmSourceTree_NamedStreamCannotBeMapped";
        internal const string EpmTargetTree_InvalidTargetPath = "EpmTargetTree_InvalidTargetPath";
        internal const string EpmTargetTree_AttributeInMiddle = "EpmTargetTree_AttributeInMiddle";
        internal const string EpmTargetTree_MultiValueAndNormalPropertyMappedToTheSameConditionalTopLevelElement = "EpmTargetTree_MultiValueAndNormalPropertyMappedToTheSameConditionalTopLevelElement";
        internal const string EpmTargetTree_MultiValueAndNormalPropertyMappedToTheSameTopLevelElement = "EpmTargetTree_MultiValueAndNormalPropertyMappedToTheSameTopLevelElement";
        internal const string EpmTargetTree_MultiValueMappedToNonRepeatableAtomElement = "EpmTargetTree_MultiValueMappedToNonRepeatableAtomElement";
        internal const string EpmTargetTree_TwoMultiValuePropertiesMappedToTheSameConditionalTopLevelElement = "EpmTargetTree_TwoMultiValuePropertiesMappedToTheSameConditionalTopLevelElement";
        internal const string EpmTargetTree_TwoMultiValuePropertiesMappedToTheSameTopLevelElement = "EpmTargetTree_TwoMultiValuePropertiesMappedToTheSameTopLevelElement";
        internal const string EpmTargetTree_DuplicateEpmAttributesWithSameTargetName = "EpmTargetTree_DuplicateEpmAttributesWithSameTargetName";
        internal const string EpmTargetTree_ConditionalMappingCategoryTermIsRequired = "EpmTargetTree_ConditionalMappingCategoryTermIsRequired";
        internal const string EpmTargetTree_ConditionalMappingLinkHrefIsRequired = "EpmTargetTree_ConditionalMappingLinkHrefIsRequired";
        internal const string EpmTargetTree_ConditionalMappingRelIsRequiredForNonConditional = "EpmTargetTree_ConditionalMappingRelIsRequiredForNonConditional";
        internal const string EpmTargetTree_ConditionalMappingToCriteriaAttribute = "EpmTargetTree_ConditionalMappingToCriteriaAttribute";
        internal const string EpmTargetTree_ConditionalMappingToNonConditionalSyndicationItem = "EpmTargetTree_ConditionalMappingToNonConditionalSyndicationItem";
        internal const string EpmSyndicationWriter_DateTimePropertyHasNullValue = "EpmSyndicationWriter_DateTimePropertyHasNullValue";
        internal const string EpmSyndicationWriter_DateTimePropertyCanNotBeConverted = "EpmSyndicationWriter_DateTimePropertyCanNotBeConverted";
        internal const string EpmSyndicationWriter_EmptyMultiValueMappedToAuthor = "EpmSyndicationWriter_EmptyMultiValueMappedToAuthor";
        internal const string EpmSyndicationWriter_EmptyValueForAtomPersonEmailOrUri = "EpmSyndicationWriter_EmptyValueForAtomPersonEmailOrUri";
        internal const string EpmSyndicationWriter_NullPropertyMappedToElementWhichDoesntAllowIt = "EpmSyndicationWriter_NullPropertyMappedToElementWhichDoesntAllowIt";
        internal const string EpmSyndicationWriter_NullValueForAttributeTarget = "EpmSyndicationWriter_NullValueForAttributeTarget";
        internal const string EpmSyndicationWriter_InvalidLinkLengthValue = "EpmSyndicationWriter_InvalidLinkLengthValue";
        internal const string EpmSyndicationWriter_InvalidValueForLinkRelCriteriaAttribute = "EpmSyndicationWriter_InvalidValueForLinkRelCriteriaAttribute";
        internal const string EpmSyndicationWriter_InvalidValueForCategorySchemeCriteriaAttribute = "EpmSyndicationWriter_InvalidValueForCategorySchemeCriteriaAttribute";
        internal const string EpmSyndicationWriter_UpdateNonConditionalCriteriaAttributeValueSameAsCondition = "EpmSyndicationWriter_UpdateNonConditionalCriteriaAttributeValueSameAsCondition";
        internal const string ODataUtils_CannotConvertValueToRawPrimitive = "ODataUtils_CannotConvertValueToRawPrimitive";
        internal const string ODataUtils_DidNotFindDefaultMediaType = "ODataUtils_DidNotFindDefaultMediaType";
        internal const string ODataUtils_CannotSaveAnnotationsToBuiltInModel = "ODataUtils_CannotSaveAnnotationsToBuiltInModel";
        internal const string ODataUtils_DidNotFindServiceOperation = "ODataUtils_DidNotFindServiceOperation";
        internal const string ODataUtils_FoundMultipleServiceOperations = "ODataUtils_FoundMultipleServiceOperations";
        internal const string ODataUtils_DidNotFindEntitySet = "ODataUtils_DidNotFindEntitySet";
        internal const string ODataUtils_CannotSetMetadataAnnotationOnPrimitiveType = "ODataUtils_CannotSetMetadataAnnotationOnPrimitiveType";
        internal const string ODataUtils_UnsupportedVersionHeader = "ODataUtils_UnsupportedVersionHeader";
        internal const string ODataUtils_UnsupportedVersionNumber = "ODataUtils_UnsupportedVersionNumber";
        internal const string ReaderUtils_EnumerableModified = "ReaderUtils_EnumerableModified";
        internal const string ReaderValidationUtils_NullValueForNonNullableType = "ReaderValidationUtils_NullValueForNonNullableType";
        internal const string ReaderValidationUtils_EntityReferenceLinkMissingUri = "ReaderValidationUtils_EntityReferenceLinkMissingUri";
        internal const string ReaderValidationUtils_ValueWithoutType = "ReaderValidationUtils_ValueWithoutType";
        internal const string ReaderValidationUtils_EntryWithoutType = "ReaderValidationUtils_EntryWithoutType";
        internal const string ReaderValidationUtils_DerivedComplexTypesAreNotAllowed = "ReaderValidationUtils_DerivedComplexTypesAreNotAllowed";
        internal const string ReaderValidationUtils_CannotConvertPrimitiveValue = "ReaderValidationUtils_CannotConvertPrimitiveValue";
        internal const string ReaderValidationUtils_MessageReaderSettingsBaseUriMustBeNullOrAbsolute = "ReaderValidationUtils_MessageReaderSettingsBaseUriMustBeNullOrAbsolute";
        internal const string ODataMessageReader_ReaderAlreadyUsed = "ODataMessageReader_ReaderAlreadyUsed";
        internal const string ODataMessageReader_IncompatiblePayloadKinds = "ODataMessageReader_IncompatiblePayloadKinds";
        internal const string ODataMessageReader_ErrorPayloadInRequest = "ODataMessageReader_ErrorPayloadInRequest";
        internal const string ODataMessageReader_ServiceDocumentInRequest = "ODataMessageReader_ServiceDocumentInRequest";
        internal const string ODataMessageReader_MetadataDocumentInRequest = "ODataMessageReader_MetadataDocumentInRequest";
        internal const string ODataMessageReader_ExpectedTypeSpecifiedWithoutMetadata = "ODataMessageReader_ExpectedTypeSpecifiedWithoutMetadata";
        internal const string ODataMessageReader_FunctionImportSpecifiedWithoutMetadata = "ODataMessageReader_FunctionImportSpecifiedWithoutMetadata";
        internal const string ODataMessageReader_ExpectedCollectionTypeWrongKind = "ODataMessageReader_ExpectedCollectionTypeWrongKind";
        internal const string ODataMessageReader_ExpectedPropertyTypeEntityKind = "ODataMessageReader_ExpectedPropertyTypeEntityKind";
        internal const string ODataMessageReader_ExpectedPropertyTypeStream = "ODataMessageReader_ExpectedPropertyTypeStream";
        internal const string ODataMessageReader_ExpectedValueTypeWrongKind = "ODataMessageReader_ExpectedValueTypeWrongKind";
        internal const string ODataMessageReader_NoneOrEmptyContentTypeHeader = "ODataMessageReader_NoneOrEmptyContentTypeHeader";
        internal const string ODataMessageReader_WildcardInContentType = "ODataMessageReader_WildcardInContentType";
        internal const string ODataMediaTypeUtils_BoundaryMustBeSpecifiedForBatchPayloads = "ODataMediaTypeUtils_BoundaryMustBeSpecifiedForBatchPayloads";
        internal const string ODataReaderCore_SyncCallOnAsyncReader = "ODataReaderCore_SyncCallOnAsyncReader";
        internal const string ODataReaderCore_AsyncCallOnSyncReader = "ODataReaderCore_AsyncCallOnSyncReader";
        internal const string ODataReaderCore_ReadOrReadAsyncCalledInInvalidState = "ODataReaderCore_ReadOrReadAsyncCalledInInvalidState";
        internal const string ODataReaderCore_NoReadCallsAllowed = "ODataReaderCore_NoReadCallsAllowed";
        internal const string ODataJsonReader_CannotReadEntriesOfFeed = "ODataJsonReader_CannotReadEntriesOfFeed";
        internal const string ODataJsonReader_CannotReadFeedStart = "ODataJsonReader_CannotReadFeedStart";
        internal const string ODataJsonReader_CannotReadEntryStart = "ODataJsonReader_CannotReadEntryStart";
        internal const string ODataJsonReader_ParsingWithoutMetadata = "ODataJsonReader_ParsingWithoutMetadata";
        internal const string ODataJsonReaderUtils_CannotConvertInt64OrDecimal = "ODataJsonReaderUtils_CannotConvertInt64OrDecimal";
        internal const string ODataJsonReaderUtils_CannotConvertInt32 = "ODataJsonReaderUtils_CannotConvertInt32";
        internal const string ODataJsonReaderUtils_CannotConvertDouble = "ODataJsonReaderUtils_CannotConvertDouble";
        internal const string ODataJsonReaderUtils_CannotConvertBoolean = "ODataJsonReaderUtils_CannotConvertBoolean";
        internal const string ODataJsonReaderUtils_CannotConvertDateTime = "ODataJsonReaderUtils_CannotConvertDateTime";
        internal const string ODataJsonReaderUtils_MultipleMetadataPropertiesWithSameName = "ODataJsonReaderUtils_MultipleMetadataPropertiesWithSameName";
        internal const string ODataJsonReaderUtils_MultipleEntityReferenceLinksWrapperPropertiesWithSameName = "ODataJsonReaderUtils_MultipleEntityReferenceLinksWrapperPropertiesWithSameName";
        internal const string ODataJsonReaderUtils_MultipleErrorPropertiesWithSameName = "ODataJsonReaderUtils_MultipleErrorPropertiesWithSameName";
        internal const string ODataJsonReaderUtils_OperationPropertyCannotBeNull = "ODataJsonReaderUtils_OperationPropertyCannotBeNull";
        internal const string ODataJsonReaderUtils_FeedPropertyWithNullValue = "ODataJsonReaderUtils_FeedPropertyWithNullValue";
        internal const string ODataJsonReaderUtils_MediaResourcePropertyWithNullValue = "ODataJsonReaderUtils_MediaResourcePropertyWithNullValue";
        internal const string ODataJsonReaderUtils_EntityReferenceLinksInlineCountWithNullValue = "ODataJsonReaderUtils_EntityReferenceLinksInlineCountWithNullValue";
        internal const string ODataJsonReaderUtils_EntityReferenceLinksPropertyWithNullValue = "ODataJsonReaderUtils_EntityReferenceLinksPropertyWithNullValue";
        internal const string ODataJsonReaderUtils_MetadataPropertyWithNullValue = "ODataJsonReaderUtils_MetadataPropertyWithNullValue";
        internal const string ODataJsonDeserializer_DataWrapperPropertyNotFound = "ODataJsonDeserializer_DataWrapperPropertyNotFound";
        internal const string ODataJsonDeserializer_DataWrapperMultipleProperties = "ODataJsonDeserializer_DataWrapperMultipleProperties";
        internal const string ODataJsonDeserializer_RelativeUriUsedWithoutBaseUriSpecified = "ODataJsonDeserializer_RelativeUriUsedWithoutBaseUriSpecified";
        internal const string ODataJsonCollectionDeserializer_MissingResultsPropertyForCollection = "ODataJsonCollectionDeserializer_MissingResultsPropertyForCollection";
        internal const string ODataJsonCollectionDeserializer_CannotReadCollectionContentStart = "ODataJsonCollectionDeserializer_CannotReadCollectionContentStart";
        internal const string ODataJsonCollectionDeserializer_MultipleResultsPropertiesForCollection = "ODataJsonCollectionDeserializer_MultipleResultsPropertiesForCollection";
        internal const string ODataJsonEntityReferenceLinkDeserializer_ExpectedEntityReferenceLinksResultsPropertyNotFound = "ODataJsonEntityReferenceLinkDeserializer_ExpectedEntityReferenceLinksResultsPropertyNotFound";
        internal const string ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkMustBeObjectValue = "ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkMustBeObjectValue";
        internal const string ODataJsonEntityReferenceLinkDeserializer_MultipleUriPropertiesInEntityReferenceLink = "ODataJsonEntityReferenceLinkDeserializer_MultipleUriPropertiesInEntityReferenceLink";
        internal const string ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkUriCannotBeNull = "ODataJsonEntityReferenceLinkDeserializer_EntityReferenceLinkUriCannotBeNull";
        internal const string ODataJsonEntryAndFeedDeserializer_ExpectedFeedResultsPropertyNotFound = "ODataJsonEntryAndFeedDeserializer_ExpectedFeedResultsPropertyNotFound";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotReadFeedContentStart = "ODataJsonEntryAndFeedDeserializer_CannotReadFeedContentStart";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleMetadataPropertiesInEntryValue = "ODataJsonEntryAndFeedDeserializer_MultipleMetadataPropertiesInEntryValue";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleUriPropertiesInDeferredLink = "ODataJsonEntryAndFeedDeserializer_MultipleUriPropertiesInDeferredLink";
        internal const string ODataJsonEntryAndFeedDeserializer_DeferredLinkUriCannotBeNull = "ODataJsonEntryAndFeedDeserializer_DeferredLinkUriCannotBeNull";
        internal const string ODataJsonEntryAndFeedDeserializer_DeferredLinkMissingUri = "ODataJsonEntryAndFeedDeserializer_DeferredLinkMissingUri";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotReadNavigationPropertyValue = "ODataJsonEntryAndFeedDeserializer_CannotReadNavigationPropertyValue";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleFeedResultsPropertiesFound = "ODataJsonEntryAndFeedDeserializer_MultipleFeedResultsPropertiesFound";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleMetadataPropertiesForNamedStream = "ODataJsonEntryAndFeedDeserializer_MultipleMetadataPropertiesForNamedStream";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotParseStreamReference = "ODataJsonEntryAndFeedDeserializer_CannotParseStreamReference";
        internal const string ODataJsonEntryAndFeedDeserializer_MetadataPropertyMustHaveObjectValue = "ODataJsonEntryAndFeedDeserializer_MetadataPropertyMustHaveObjectValue";
        internal const string ODataJsonEntryAndFeedDeserializer_PropertyInEntryMustHaveObjectValue = "ODataJsonEntryAndFeedDeserializer_PropertyInEntryMustHaveObjectValue";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotReadSingletonNavigationPropertyValue = "ODataJsonEntryAndFeedDeserializer_CannotReadSingletonNavigationPropertyValue";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotReadWrappedFeedStart = "ODataJsonEntryAndFeedDeserializer_CannotReadWrappedFeedStart";
        internal const string ODataJsonEntryAndFeedDeserializer_CannotReadCollectionNavigationPropertyValue = "ODataJsonEntryAndFeedDeserializer_CannotReadCollectionNavigationPropertyValue";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleOptionalPropertiesInOperation = "ODataJsonEntryAndFeedDeserializer_MultipleOptionalPropertiesInOperation";
        internal const string ODataJsonEntryAndFeedDeserializer_MultipleTargetPropertiesInOperation = "ODataJsonEntryAndFeedDeserializer_MultipleTargetPropertiesInOperation";
        internal const string ODataJsonEntryAndFeedDeserializer_OperationMissingTargetProperty = "ODataJsonEntryAndFeedDeserializer_OperationMissingTargetProperty";
        internal const string ODataJsonErrorDeserializer_TopLevelErrorWithInvalidProperty = "ODataJsonErrorDeserializer_TopLevelErrorWithInvalidProperty";
        internal const string ODataJsonErrorDeserializer_TopLevelErrorMessageValueWithInvalidProperty = "ODataJsonErrorDeserializer_TopLevelErrorMessageValueWithInvalidProperty";
        internal const string ODataJsonErrorDeserializer_TopLevelErrorValueWithInvalidProperty = "ODataJsonErrorDeserializer_TopLevelErrorValueWithInvalidProperty";
        internal const string ODataJsonPropertyAndValueDeserializer_TopLevelPropertyWithoutMetadata = "ODataJsonPropertyAndValueDeserializer_TopLevelPropertyWithoutMetadata";
        internal const string ODataJsonPropertyAndValueDeserializer_InvalidTopLevelPropertyPayload = "ODataJsonPropertyAndValueDeserializer_InvalidTopLevelPropertyPayload";
        internal const string ODataJsonPropertyAndValueDeserializer_CannotReadPropertyValue = "ODataJsonPropertyAndValueDeserializer_CannotReadPropertyValue";
        internal const string ODataJsonPropertyAndValueDeserializer_MultipleMetadataPropertiesInComplexValue = "ODataJsonPropertyAndValueDeserializer_MultipleMetadataPropertiesInComplexValue";
        internal const string ODataJsonPropertyAndValueDeserializer_MultiplePropertiesInMultiValueWrapper = "ODataJsonPropertyAndValueDeserializer_MultiplePropertiesInMultiValueWrapper";
        internal const string ODataJsonPropertyAndValueDeserializer_MultiValueWithoutResults = "ODataJsonPropertyAndValueDeserializer_MultiValueWithoutResults";
        internal const string ODataJsonPropertyAndValueDeserializer_InvalidTypeName = "ODataJsonPropertyAndValueDeserializer_InvalidTypeName";
        internal const string ODataJsonServiceDocumentDeserializer_MultipleEntitySetsPropertiesForServiceDocument = "ODataJsonServiceDocumentDeserializer_MultipleEntitySetsPropertiesForServiceDocument";
        internal const string ODataJsonServiceDocumentDeserializer_NoEntitySetsPropertyForServiceDocument = "ODataJsonServiceDocumentDeserializer_NoEntitySetsPropertyForServiceDocument";
        internal const string ODataCollectionReaderCore_ReadOrReadAsyncCalledInInvalidState = "ODataCollectionReaderCore_ReadOrReadAsyncCalledInInvalidState";
        internal const string ODataCollectionReaderCore_SyncCallOnAsyncReader = "ODataCollectionReaderCore_SyncCallOnAsyncReader";
        internal const string ODataCollectionReaderCore_AsyncCallOnSyncReader = "ODataCollectionReaderCore_AsyncCallOnSyncReader";
        internal const string ODataJsonCollectionReader_CannotReadWrappedCollectionStart = "ODataJsonCollectionReader_CannotReadWrappedCollectionStart";
        internal const string ODataJsonCollectionReader_CannotReadCollectionStart = "ODataJsonCollectionReader_CannotReadCollectionStart";
        internal const string ODataJsonCollectionReader_ParsingWithoutMetadata = "ODataJsonCollectionReader_ParsingWithoutMetadata";
        internal const string ValidationUtils_ActionsAndFunctionsMustSpecifyNonEmptyRelation = "ValidationUtils_ActionsAndFunctionsMustSpecifyNonEmptyRelation";
        internal const string ValidationUtils_ActionsAndFunctionsMustSpecifyTarget = "ValidationUtils_ActionsAndFunctionsMustSpecifyTarget";
        internal const string ValidationUtils_EnumerableContainsANullItem = "ValidationUtils_EnumerableContainsANullItem";
        internal const string ValidationUtils_AssociationLinkMustSpecifyName = "ValidationUtils_AssociationLinkMustSpecifyName";
        internal const string ValidationUtils_AssociationLinkMustSpecifyUrl = "ValidationUtils_AssociationLinkMustSpecifyUrl";
        internal const string ValidationUtils_TypeNameMustNotBeEmpty = "ValidationUtils_TypeNameMustNotBeEmpty";
        internal const string ValidationUtils_PropertyDoesNotExistOnType = "ValidationUtils_PropertyDoesNotExistOnType";
        internal const string ValidationUtils_ResourceCollectionMustSpecifyUrl = "ValidationUtils_ResourceCollectionMustSpecifyUrl";
        internal const string ValidationUtils_ResourceCollectionUrlMustNotBeNull = "ValidationUtils_ResourceCollectionUrlMustNotBeNull";
        internal const string ValidationUtils_NonPrimitiveTypeForPrimitiveValue = "ValidationUtils_NonPrimitiveTypeForPrimitiveValue";
        internal const string ValidationUtils_UnsupportedPrimitiveType = "ValidationUtils_UnsupportedPrimitiveType";
        internal const string ValidationUtils_IncompatiblePrimitiveItemType = "ValidationUtils_IncompatiblePrimitiveItemType";
        internal const string ValidationUtils_MultiValueElementsMustNotBeNull = "ValidationUtils_MultiValueElementsMustNotBeNull";
        internal const string ValidationUtils_InvalidMultiValueTypeName = "ValidationUtils_InvalidMultiValueTypeName";
        internal const string ValidationUtils_UnrecognizedTypeName = "ValidationUtils_UnrecognizedTypeName";
        internal const string ValidationUtils_IncorrectTypeKind = "ValidationUtils_IncorrectTypeKind";
        internal const string ValidationUtils_IncorrectValueTypeKind = "ValidationUtils_IncorrectValueTypeKind";
        internal const string ValidationUtils_LinkMustSpecifyName = "ValidationUtils_LinkMustSpecifyName";
        internal const string ValidationUtils_MismatchPropertyKindForNamedStreamProperty = "ValidationUtils_MismatchPropertyKindForNamedStreamProperty";
        internal const string ValidationUtils_InvalidEtagValue = "ValidationUtils_InvalidEtagValue";
        internal const string ValidationUtils_NestedMultiValuesAreNotSupported = "ValidationUtils_NestedMultiValuesAreNotSupported";
        internal const string ValidationUtils_MultiValuesNotSupportedInCollections = "ValidationUtils_MultiValuesNotSupportedInCollections";
        internal const string ValidationUtils_StreamReferenceValuesNotSupportedInMultiValues = "ValidationUtils_StreamReferenceValuesNotSupportedInMultiValues";
        internal const string ValidationUtils_StreamReferenceValueNotSupportedInCollections = "ValidationUtils_StreamReferenceValueNotSupportedInCollections";
        internal const string ValidationUtils_IncompatibleType = "ValidationUtils_IncompatibleType";
        internal const string ValidationUtils_MultiValuePropertiesMustNotHaveNullValue = "ValidationUtils_MultiValuePropertiesMustNotHaveNullValue";
        internal const string ValidationUtils_NonNullablePrimitivePropertiesMustNotHaveNullValue = "ValidationUtils_NonNullablePrimitivePropertiesMustNotHaveNullValue";
        internal const string ValidationUtils_NamedStreamPropertiesMustNotHaveNullValue = "ValidationUtils_NamedStreamPropertiesMustNotHaveNullValue";
        internal const string ValidationUtils_OpenMultiValueProperty = "ValidationUtils_OpenMultiValueProperty";
        internal const string ValidationUtils_OpenStreamProperty = "ValidationUtils_OpenStreamProperty";
        internal const string ValidationUtils_InvalidMultiValueTypeReference = "ValidationUtils_InvalidMultiValueTypeReference";
        internal const string ValidationUtils_EntryWithMediaResourceAndNonMLEType = "ValidationUtils_EntryWithMediaResourceAndNonMLEType";
        internal const string ValidationUtils_EntryWithoutMediaResourceAndMLEType = "ValidationUtils_EntryWithoutMediaResourceAndMLEType";
        internal const string ValidationUtils_ModelWithMultipleContainers = "ValidationUtils_ModelWithMultipleContainers";
        internal const string ValidationUtils_EntryTypeNotAssignableToExpectedType = "ValidationUtils_EntryTypeNotAssignableToExpectedType";
        internal const string ValidationUtils_OpenNavigationProperty = "ValidationUtils_OpenNavigationProperty";
        internal const string ValidationUtils_NavigationPropertyExpected = "ValidationUtils_NavigationPropertyExpected";
        internal const string WriterValidationUtils_PropertyMustNotBeNull = "WriterValidationUtils_PropertyMustNotBeNull";
        internal const string WriterValidationUtils_PropertiesMustHaveNonEmptyName = "WriterValidationUtils_PropertiesMustHaveNonEmptyName";
        internal const string WriterValidationUtils_MissingTypeNameWithMetadata = "WriterValidationUtils_MissingTypeNameWithMetadata";
        internal const string WriterValidationUtils_FeedsMustHaveNonEmptyId = "WriterValidationUtils_FeedsMustHaveNonEmptyId";
        internal const string WriterValidationUtils_NextPageLinkInRequest = "WriterValidationUtils_NextPageLinkInRequest";
        internal const string WriterValidationUtils_WorkspaceCollectionsMustNotContainNullItem = "WriterValidationUtils_WorkspaceCollectionsMustNotContainNullItem";
        internal const string WriterValidationUtils_ResourceCollectionMustHaveUniqueName = "WriterValidationUtils_ResourceCollectionMustHaveUniqueName";
        internal const string WriterValidationUtils_DefaultStreamWithContentTypeWithoutReadLink = "WriterValidationUtils_DefaultStreamWithContentTypeWithoutReadLink";
        internal const string WriterValidationUtils_DefaultStreamWithReadLinkWithoutContentType = "WriterValidationUtils_DefaultStreamWithReadLinkWithoutContentType";
        internal const string WriterValidationUtils_StreamReferenceValueMustHaveEditLinkOrReadLink = "WriterValidationUtils_StreamReferenceValueMustHaveEditLinkOrReadLink";
        internal const string WriterValidationUtils_StreamReferenceValueMustHaveEditLinkToHaveETag = "WriterValidationUtils_StreamReferenceValueMustHaveEditLinkToHaveETag";
        internal const string WriterValidationUtils_StreamReferenceValueEmptyContentType = "WriterValidationUtils_StreamReferenceValueEmptyContentType";
        internal const string WriterValidationUtils_EntriesMustHaveNonEmptyId = "WriterValidationUtils_EntriesMustHaveNonEmptyId";
        internal const string WriterValidationUtils_MessageWriterSettingsBaseUriMustBeNullOrAbsolute = "WriterValidationUtils_MessageWriterSettingsBaseUriMustBeNullOrAbsolute";
        internal const string XmlReaderExtension_InvalidNodeInStringValue = "XmlReaderExtension_InvalidNodeInStringValue";
        internal const string XmlReaderExtension_InvalidRootNode = "XmlReaderExtension_InvalidRootNode";
        internal const string BufferingXmlReader_TopLevelXmlBaseMustBeAbsolute = "BufferingXmlReader_TopLevelXmlBaseMustBeAbsolute";
        internal const string ODataAtomInputContext_TopLevelPropertyElementWrongNamespace = "ODataAtomInputContext_TopLevelPropertyElementWrongNamespace";
        internal const string ODataAtomInputContext_NonEmptyElementWithNullAttribute = "ODataAtomInputContext_NonEmptyElementWithNullAttribute";
        internal const string ODataAtomInputContext_WrongCollectionItemElementName = "ODataAtomInputContext_WrongCollectionItemElementName";
        internal const string ODataAtomInputContext_InvalidMultiValueElement = "ODataAtomInputContext_InvalidMultiValueElement";
        internal const string ODataMetadataInputContext_ErrorReadingMetadata = "ODataMetadataInputContext_ErrorReadingMetadata";
        internal const string EpmExtensionMethods_InvalidKeepInContentOnType = "EpmExtensionMethods_InvalidKeepInContentOnType";
        internal const string EpmExtensionMethods_InvalidKeepInContentOnProperty = "EpmExtensionMethods_InvalidKeepInContentOnProperty";
        internal const string EpmExtensionMethods_InvalidTargetTextContentKindOnType = "EpmExtensionMethods_InvalidTargetTextContentKindOnType";
        internal const string EpmExtensionMethods_InvalidTargetTextContentKindOnProperty = "EpmExtensionMethods_InvalidTargetTextContentKindOnProperty";
        internal const string EpmExtensionMethods_MissingAttributeOnType = "EpmExtensionMethods_MissingAttributeOnType";
        internal const string EpmExtensionMethods_MissingAttributeOnProperty = "EpmExtensionMethods_MissingAttributeOnProperty";
        internal const string EpmExtensionMethods_AttributeNotAllowedForCustomMappingOnType = "EpmExtensionMethods_AttributeNotAllowedForCustomMappingOnType";
        internal const string EpmExtensionMethods_AttributeNotAllowedForCustomMappingOnProperty = "EpmExtensionMethods_AttributeNotAllowedForCustomMappingOnProperty";
        internal const string EpmExtensionMethods_AttributeNotAllowedForAtomPubMappingOnType = "EpmExtensionMethods_AttributeNotAllowedForAtomPubMappingOnType";
        internal const string EpmExtensionMethods_AttributeNotAllowedForAtomPubMappingOnProperty = "EpmExtensionMethods_AttributeNotAllowedForAtomPubMappingOnProperty";
        internal const string EpmExtensionMethods_ConditionalMappingToNonConditionalSyndicationItemOnType = "EpmExtensionMethods_ConditionalMappingToNonConditionalSyndicationItemOnType";
        internal const string EpmExtensionMethods_ConditionalMappingToNonConditionalSyndicationItemOnProperty = "EpmExtensionMethods_ConditionalMappingToNonConditionalSyndicationItemOnProperty";
        internal const string EpmExtensionMethods_ConditionalMappingToInvalidContentKindOnType = "EpmExtensionMethods_ConditionalMappingToInvalidContentKindOnType";
        internal const string EpmExtensionMethods_ConditionalMappingToInvalidContentKindOnProperty = "EpmExtensionMethods_ConditionalMappingToInvalidContentKindOnProperty";
        internal const string EpmExtensionMethods_CannotConvertEdmAnnotationValue = "EpmExtensionMethods_CannotConvertEdmAnnotationValue";
        internal const string ODataAtomReader_MediaLinkEntryMismatch = "ODataAtomReader_MediaLinkEntryMismatch";
        internal const string ODataAtomReader_FeedNavigationLinkForResourceReferenceProperty = "ODataAtomReader_FeedNavigationLinkForResourceReferenceProperty";
        internal const string ODataAtomReader_EmptyExpansionForCollection = "ODataAtomReader_EmptyExpansionForCollection";
        internal const string ODataAtomReader_ExpandedFeedInEntryNavigationLink = "ODataAtomReader_ExpandedFeedInEntryNavigationLink";
        internal const string ODataAtomReader_ExpandedEntryInFeedNavigationLink = "ODataAtomReader_ExpandedEntryInFeedNavigationLink";
        internal const string ODataAtomReaderUtils_InvalidTypeName = "ODataAtomReaderUtils_InvalidTypeName";
        internal const string ODataAtomDeserializer_RelativeUriUsedWithoutBaseUriSpecified = "ODataAtomDeserializer_RelativeUriUsedWithoutBaseUriSpecified";
        internal const string ODataAtomCollectionDeserializer_TypeOrNullAttributeNotAllowed = "ODataAtomCollectionDeserializer_TypeOrNullAttributeNotAllowed";
        internal const string ODataAtomCollectionDeserializer_WrongCollectionItemElementName = "ODataAtomCollectionDeserializer_WrongCollectionItemElementName";
        internal const string ODataAtomCollectionDeserializer_TopLevelCollectionElementWrongNamespace = "ODataAtomCollectionDeserializer_TopLevelCollectionElementWrongNamespace";
        internal const string ODataAtomPropertyAndValueDeserializer_TopLevelPropertyElementWrongNamespace = "ODataAtomPropertyAndValueDeserializer_TopLevelPropertyElementWrongNamespace";
        internal const string ODataAtomPropertyAndValueDeserializer_NonEmptyElementWithNullAttribute = "ODataAtomPropertyAndValueDeserializer_NonEmptyElementWithNullAttribute";
        internal const string ODataAtomPropertyAndValueDeserializer_InvalidMultiValueElement = "ODataAtomPropertyAndValueDeserializer_InvalidMultiValueElement";
        internal const string EdmLibraryExtensions_UnsupportedPrimitiveType = "EdmLibraryExtensions_UnsupportedPrimitiveType";
        internal const string EdmLibraryExtensions_MultiValueItemCanBeOnlyPrimitiveOrComplex = "EdmLibraryExtensions_MultiValueItemCanBeOnlyPrimitiveOrComplex";
        internal const string ODataAtomEntryAndFeedDeserializer_EntryElementWrongName = "ODataAtomEntryAndFeedDeserializer_EntryElementWrongName";
        internal const string ODataAtomEntryAndFeedDeserializer_ContentWithSourceLinkIsNotEmpty = "ODataAtomEntryAndFeedDeserializer_ContentWithSourceLinkIsNotEmpty";
        internal const string ODataAtomEntryAndFeedDeserializer_ContentWithWrongType = "ODataAtomEntryAndFeedDeserializer_ContentWithWrongType";
        internal const string ODataAtomEntryAndFeedDeserializer_ContentWithInvalidNode = "ODataAtomEntryAndFeedDeserializer_ContentWithInvalidNode";
        internal const string ODataAtomEntryAndFeedDeserializer_FeedElementWrongName = "ODataAtomEntryAndFeedDeserializer_FeedElementWrongName";
        internal const string ODataAtomEntryAndFeedDeserializer_UnknownElementInInline = "ODataAtomEntryAndFeedDeserializer_UnknownElementInInline";
        internal const string ODataAtomEntryAndFeedDeserializer_MultipleExpansionsInInline = "ODataAtomEntryAndFeedDeserializer_MultipleExpansionsInInline";
        internal const string ODataAtomEntryAndFeedDeserializer_MultipleInlineElementsInLink = "ODataAtomEntryAndFeedDeserializer_MultipleInlineElementsInLink";
        internal const string ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleEditLinks = "ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleEditLinks";
        internal const string ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleReadLinks = "ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleReadLinks";
        internal const string ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleContentTypes = "ODataAtomEntryAndFeedDeserializer_StreamPropertyWithMultipleContentTypes";
        internal const string ODataAtomEntryAndFeedDeserializer_StreamPropertyDuplicatePropertyName = "ODataAtomEntryAndFeedDeserializer_StreamPropertyDuplicatePropertyName";
        internal const string ODataAtomEntryAndFeedDeserializer_StreamPropertyWithEmptyName = "ODataAtomEntryAndFeedDeserializer_StreamPropertyWithEmptyName";
        internal const string ODataAtomEntryAndFeedDeserializer_OperationMissingOrEmptyRelAttribute = "ODataAtomEntryAndFeedDeserializer_OperationMissingOrEmptyRelAttribute";
        internal const string ODataAtomEntryAndFeedDeserializer_OperationMissingTargetAttribute = "ODataAtomEntryAndFeedDeserializer_OperationMissingTargetAttribute";
        internal const string ODataAtomServiceDocumentDeserializer_ServiceDocumentRootElementWrongNameOrNamespace = "ODataAtomServiceDocumentDeserializer_ServiceDocumentRootElementWrongNameOrNamespace";
        internal const string ODataAtomServiceDocumentDeserializer_MissingWorkspaceElement = "ODataAtomServiceDocumentDeserializer_MissingWorkspaceElement";
        internal const string ODataAtomServiceDocumentDeserializer_MultipleWorkspaceElementsFound = "ODataAtomServiceDocumentDeserializer_MultipleWorkspaceElementsFound";
        internal const string ODataAtomServiceDocumentDeserializer_UnexpectedElementInServiceDocument = "ODataAtomServiceDocumentDeserializer_UnexpectedElementInServiceDocument";
        internal const string ODataAtomServiceDocumentDeserializer_UnexpectedElementInWorkspace = "ODataAtomServiceDocumentDeserializer_UnexpectedElementInWorkspace";
        internal const string ODataAtomServiceDocumentDeserializer_UnexpectedElementInCollection = "ODataAtomServiceDocumentDeserializer_UnexpectedElementInCollection";
        internal const string ODataAtomEntryMetadataDeserializer_InvalidTextConstructKind = "ODataAtomEntryMetadataDeserializer_InvalidTextConstructKind";
        internal const string ODataAtomErrorDeserializer_InvalidRootElement = "ODataAtomErrorDeserializer_InvalidRootElement";
        internal const string ODataAtomErrorDeserializer_MultipleErrorElementsWithSameName = "ODataAtomErrorDeserializer_MultipleErrorElementsWithSameName";
        internal const string ODataAtomErrorDeserializer_MultipleInnerErrorElementsWithSameName = "ODataAtomErrorDeserializer_MultipleInnerErrorElementsWithSameName";
        internal const string ODataAtomEntityReferenceLinkDeserializer_InvalidEntityReferenceLinkStartElement = "ODataAtomEntityReferenceLinkDeserializer_InvalidEntityReferenceLinkStartElement";
        internal const string ODataAtomEntityReferenceLinkDeserializer_InvalidEntityReferenceLinksStartElement = "ODataAtomEntityReferenceLinkDeserializer_InvalidEntityReferenceLinksStartElement";
        internal const string ODataAtomEntityReferenceLinkDeserializer_MultipleEntityReferenceLinksElementsWithSameName = "ODataAtomEntityReferenceLinkDeserializer_MultipleEntityReferenceLinksElementsWithSameName";
        internal const string EpmReader_OpenComplexOrMultivalueEpmProperty = "EpmReader_OpenComplexOrMultivalueEpmProperty";
        internal const string EpmSyndicationReader_EmptyValueForAtomPersonEmailOrUri = "EpmSyndicationReader_EmptyValueForAtomPersonEmailOrUri";
        internal const string EpmSyndicationReader_MultipleValuesForNonMultiValueProperty = "EpmSyndicationReader_MultipleValuesForNonMultiValueProperty";
        internal const string ExceptionUtils_CheckIntegerNotNegative = "ExceptionUtils_CheckIntegerNotNegative";
        internal const string ExceptionUtils_ArgumentStringNullOrEmpty = "ExceptionUtils_ArgumentStringNullOrEmpty";
        internal const string JsonReader_UnexpectedComma = "JsonReader_UnexpectedComma";
        internal const string JsonReader_MultipleTopLevelValues = "JsonReader_MultipleTopLevelValues";
        internal const string JsonReader_EndOfInputWithOpenScope = "JsonReader_EndOfInputWithOpenScope";
        internal const string JsonReader_UnexpectedToken = "JsonReader_UnexpectedToken";
        internal const string JsonReader_UnrecognizedToken = "JsonReader_UnrecognizedToken";
        internal const string JsonReader_MissingColon = "JsonReader_MissingColon";
        internal const string JsonReader_UnrecognizedEscapeSequence = "JsonReader_UnrecognizedEscapeSequence";
        internal const string JsonReader_UnexpectedEndOfString = "JsonReader_UnexpectedEndOfString";
        internal const string JsonReader_InvalidNumberFormat = "JsonReader_InvalidNumberFormat";
        internal const string JsonReader_MissingComma = "JsonReader_MissingComma";
        internal const string JsonReader_InvalidPropertyNameOrUnexpectedComma = "JsonReader_InvalidPropertyNameOrUnexpectedComma";
        internal const string JsonReaderExtensions_UnexpectedNodeDetected = "JsonReaderExtensions_UnexpectedNodeDetected";
        internal const string JsonReaderExtensions_CannotReadPropertyValueAsString = "JsonReaderExtensions_CannotReadPropertyValueAsString";
        internal const string JsonReaderExtensions_CannotReadValueAsString = "JsonReaderExtensions_CannotReadValueAsString";
        internal const string JsonReaderExtensions_CannotReadValueAsDouble = "JsonReaderExtensions_CannotReadValueAsDouble";

        static TextRes loader = null;
        ResourceManager resources;

        internal TextRes() {
            resources = new System.Resources.ResourceManager("Microsoft.Data.OData", this.GetType().Assembly);
        }
        
        private static TextRes GetLoader() {
            if (loader == null) {
                TextRes sr = new TextRes();
                Interlocked.CompareExchange(ref loader, sr, null);
            }
            return loader;
        }

        private static CultureInfo Culture {
            get { return null/*use ResourceManager default, CultureInfo.CurrentUICulture*/; }
        }
        
        public static ResourceManager Resources {
            get {
                return GetLoader().resources;
            }
        }
        
        public static string GetString(string name, params object[] args) {
            TextRes sys = GetLoader();
            if (sys == null)
                return null;
            string res = sys.resources.GetString(name, TextRes.Culture);

            if (args != null && args.Length > 0) {
                for (int i = 0; i < args.Length; i ++) {
                    String value = args[i] as String;
                    if (value != null && value.Length > 1024) {
                        args[i] = value.Substring(0, 1024 - 3) + "...";
                    }
                }
                return String.Format(CultureInfo.CurrentCulture, res, args);
            }
            else {
                return res;
            }
        }

        public static string GetString(string name) {
            TextRes sys = GetLoader();
            if (sys == null)
                return null;
            return sys.resources.GetString(name, TextRes.Culture);
        }
        
        public static string GetString(string name, out bool usedFallback) {
            // always false for this version of gensr
            usedFallback = false;
            return GetString(name);
        }

        public static object GetObject(string name) {
            TextRes sys = GetLoader();
            if (sys == null)
                return null;
            return sys.resources.GetObject(name, TextRes.Culture);
        }
    }
}
