//---------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Contracts.DataServiceActionProviderOverrides.#WithCreateInvokableFunc(System.Func`4<Microsoft.OData.Service.DataServiceOperationContext,Microsoft.OData.Service.Providers.ServiceAction,System.Object[],Microsoft.OData.Service.Providers.IDataServiceInvokable>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Contracts.DataServiceUpdatable2Overrides.#WithImmediateCreateInvokable(System.Action`1<Microsoft.OData.Service.Providers.IDataServiceInvokable>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Contracts.DataServiceUpdatable2Overrides.#WithPendingActionsCreateInvokable(System.Action`1<Microsoft.OData.Service.Providers.IDataServiceInvokable>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Microsoft.Test.OData.Framework.TestProviders.Dictionary.DictionaryDataContext")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Dictionary.DictionaryDataContext.#ScheduleInvokable(Microsoft.OData.Service.Providers.IDataServiceInvokable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Dictionary.DictionaryDataContext.#ScheduleInvokable(Microsoft.OData.Service.Providers.IDataServiceInvokable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Reflection.ReflectionDataContext.#ScheduleInvokable(Microsoft.OData.Service.Providers.IDataServiceInvokable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Reflection.ReflectionDataContext.#ScheduleInvokable(Microsoft.OData.Service.Providers.IDataServiceInvokable)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.Reflection.ReflectionMetadataHelper.#GetResourceTypesOfSet(System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode", Scope = "member", Target = "Microsoft.Test.OData.Framework.TestProviders.OptionalProviders.StreamWrapper.#ReadUri")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Invokable", Scope = "type", Target = "Microsoft.Test.OData.Framework.TestProviders.OptionalProviders.TestDataServiceInvokable")]