//---------------------------------------------------------------------
// <copyright file="Microsoft.OData.Edm.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
//
//      GENERATED FILE.  DO NOT MODIFY.
//
// </copyright>
//---------------------------------------------------------------------

using System;
using System.Globalization;
using System.Reflection;
using System.Resources;
using System.Threading;

namespace Microsoft.OData.Edm
{
    /// <summary>
    ///    AutoGenerated resource class. Usage:
    ///
    ///        string s = EdmRes.GetString(EdmRes.MyIdenfitier);
    /// </summary>
    internal sealed class EdmRes {
    }