odataRelativeUri	= '$batch' [ "?" batchOptions ]
					/ '$entity' "?" entityOptions
					/ '$entity' "/" qualifiedEntityTypeName ? entityCastOptions
					/ '$metadata' [ "?" metadataOptions ] [ context ]
					/ resourcePath [ "?" queryOptions ]

batchOptions	= batchOption *( "&" batchOption )

batchOption	= format
			/ customQueryOption

format	= ( "$format" / "format" ) EQ
		  ( "atom"
		  / "json"
		  / "xml"
		  / 1*pchar "/" 1*pchar
		  )

customQueryOption	= 

pchar	= unreserved
		/ pct-encoded
		/ sub-delims
		/ ":"
		/ "@"

unreserved	= ALPHA
			/ DIGIT
			/ "-"
			/ "."
			/ "_"
			/ "~"

pct-encoded	= "%" HEXDIG HEXDIG

sub-delims	= "$" 
			/ "&"
			/ "'"
			/ "="
			/ other-delims

other-delims	= "!"
				/ "("
				/ ")"
				/ "*"
				/ "+"
				/ ","
				/ ";"

;------------------------------------------------------------------------------
; 9. Punctuation
;------------------------------------------------------------------------------

EQ	= "="

;------------------------------------------------------------------------------
; C. ABNF core definitions [RFC5234]
;------------------------------------------------------------------------------

ALPHA	= %x41-5A / %x61-7A 
DIGIT	= %x30-39 
HEXDIG = DIGIT / A-to-F