namespace __GeneratedOdataV3.Parsers.Inners
{
    using CombinatorParsingV2;
    
    public static class _entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Parser
    {
        public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡> Instance { get; } = (_entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡Parser.Instance).Or<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>(_entityFunction_functionExprParameters_꘡singleNavigationExpr꘡Parser.Instance).Or<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>(_complexColFunction_functionExprParameters_꘡complexColPathExpr꘡Parser.Instance).Or<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>(_complexFunction_functionExprParameters_꘡complexPathExpr꘡Parser.Instance).Or<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>(_primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡Parser.Instance).Or<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>(_primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Parser.Instance);
        
        public static class _entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡> Parse(IInput<char>? input)
                {
                    var _entityColFunction_1 = __GeneratedOdataV3.Parsers.Rules._entityColFunctionParser.Instance.Parse(input);
if (!_entityColFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_entityColFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡)!, input);
}

var _collectionNavigationExpr_1 = __GeneratedOdataV3.Parsers.Rules._collectionNavigationExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_collectionNavigationExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡(_entityColFunction_1.Parsed, _functionExprParameters_1.Parsed, _collectionNavigationExpr_1.Parsed.GetOrElse(null)), _collectionNavigationExpr_1.Remainder);
                }
            }
        }
        
        public static class _entityFunction_functionExprParameters_꘡singleNavigationExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡> Parse(IInput<char>? input)
                {
                    var _entityFunction_1 = __GeneratedOdataV3.Parsers.Rules._entityFunctionParser.Instance.Parse(input);
if (!_entityFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_entityFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡)!, input);
}

var _singleNavigationExpr_1 = __GeneratedOdataV3.Parsers.Rules._singleNavigationExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_singleNavigationExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._entityFunction_functionExprParameters_꘡singleNavigationExpr꘡(_entityFunction_1.Parsed, _functionExprParameters_1.Parsed, _singleNavigationExpr_1.Parsed.GetOrElse(null)), _singleNavigationExpr_1.Remainder);
                }
            }
        }
        
        public static class _complexColFunction_functionExprParameters_꘡complexColPathExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡> Parse(IInput<char>? input)
                {
                    var _complexColFunction_1 = __GeneratedOdataV3.Parsers.Rules._complexColFunctionParser.Instance.Parse(input);
if (!_complexColFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_complexColFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡)!, input);
}

var _complexColPathExpr_1 = __GeneratedOdataV3.Parsers.Rules._complexColPathExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_complexColPathExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexColFunction_functionExprParameters_꘡complexColPathExpr꘡(_complexColFunction_1.Parsed, _functionExprParameters_1.Parsed, _complexColPathExpr_1.Parsed.GetOrElse(null)), _complexColPathExpr_1.Remainder);
                }
            }
        }
        
        public static class _complexFunction_functionExprParameters_꘡complexPathExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡> Parse(IInput<char>? input)
                {
                    var _complexFunction_1 = __GeneratedOdataV3.Parsers.Rules._complexFunctionParser.Instance.Parse(input);
if (!_complexFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_complexFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡)!, input);
}

var _complexPathExpr_1 = __GeneratedOdataV3.Parsers.Rules._complexPathExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_complexPathExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._complexFunction_functionExprParameters_꘡complexPathExpr꘡(_complexFunction_1.Parsed, _functionExprParameters_1.Parsed, _complexPathExpr_1.Parsed.GetOrElse(null)), _complexPathExpr_1.Remainder);
                }
            }
        }
        
        public static class _primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡> Parse(IInput<char>? input)
                {
                    var _primitiveColFunction_1 = __GeneratedOdataV3.Parsers.Rules._primitiveColFunctionParser.Instance.Parse(input);
if (!_primitiveColFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_primitiveColFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡)!, input);
}

var _collectionPathExpr_1 = __GeneratedOdataV3.Parsers.Rules._collectionPathExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_collectionPathExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡(_primitiveColFunction_1.Parsed, _functionExprParameters_1.Parsed, _collectionPathExpr_1.Parsed.GetOrElse(null)), _collectionPathExpr_1.Remainder);
                }
            }
        }
        
        public static class _primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Parser
        {
            public static IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡> Instance { get; } = new Parser();
            
            private sealed class Parser : IParser<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡>
            {
                public Parser()
                {
                }
                
                public IOutput<char, __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡> Parse(IInput<char>? input)
                {
                    var _primitiveFunction_1 = __GeneratedOdataV3.Parsers.Rules._primitiveFunctionParser.Instance.Parse(input);
if (!_primitiveFunction_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡)!, input);
}

var _functionExprParameters_1 = __GeneratedOdataV3.Parsers.Rules._functionExprParametersParser.Instance.Parse(_primitiveFunction_1.Remainder);
if (!_functionExprParameters_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡)!, input);
}

var _primitivePathExpr_1 = __GeneratedOdataV3.Parsers.Rules._primitivePathExprParser.Instance.Optional().Parse(_functionExprParameters_1.Remainder);
if (!_primitivePathExpr_1.Success)
{
    return Output.Create(false, default(__GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡)!, input);
}

return Output.Create(true, new __GeneratedOdataV3.CstNodes.Inners._entityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡._primitiveFunction_functionExprParameters_꘡primitivePathExpr꘡(_primitiveFunction_1.Parsed, _functionExprParameters_1.Parsed, _primitivePathExpr_1.Parsed.GetOrElse(null)), _primitivePathExpr_1.Remainder);
                }
            }
        }
    }
    
}
