//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name: CustomObjectContext.cs
// Generation date: 2/12/2008 3:19:12 PM
namespace AstoriaUnitTests.ObjectContextStubs
{
    
    /// <summary>
    /// There are no comments for CustomObjectContext in the schema.
    /// </summary>
    public partial class CustomObjectContext : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new CustomObjectContext object using the connection string found in the 'CustomObjectContext' section of the application configuration file.
        /// </summary>
        public CustomObjectContext() :
            this(PopulateData.EntityConnection)
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomObjectContext object.
        /// </summary>
        public CustomObjectContext(string connectionString) :
            this(PopulateData.EntityConnection)
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new CustomObjectContext object.
        /// </summary>
        public CustomObjectContext(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "CustomObjectContext")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Customer>("[Customers]");
                }
                return this._Customers;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Customer> _Customers;

        /// <summary>
        /// There are no comments for CustomerBlobs in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.CustomerBlob> CustomerBlobs
        {
            get
            {
                if ((this._CustomerBlobs == null))
                {
                    this._CustomerBlobs = base.CreateQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.CustomerBlob>("[CustomerBlobs]");
                }
                return this._CustomerBlobs;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.CustomerBlob> _CustomerBlobs;

        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Order>("[Orders]");
                }
                return this._Orders;
            }
        }
        private global::System.Data.Objects.ObjectQuery<AstoriaUnitTests.ObjectContextStubs.Hidden.Order> _Orders;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        public void AddToCustomers(AstoriaUnitTests.ObjectContextStubs.Hidden.Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for CustomerBlobs in the schema.
        /// </summary>
        public void AddToCustomerBlobs(AstoriaUnitTests.ObjectContextStubs.Hidden.CustomerBlob customerBlob)
        {
            base.AddObject("CustomerBlobs", customerBlob);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        public void AddToOrders(AstoriaUnitTests.ObjectContextStubs.Hidden.Order order)
        {
            base.AddObject("Orders", order);
        }
    }
}
