namespace __GeneratedOdataV4.CstNodes.Rules
{
    public sealed class _functionExpr
    {
        public _functionExpr(__GeneratedOdataV4.CstNodes.Rules._namespace _namespace_1, __GeneratedOdataV4.CstNodes.Inners._ʺx2Eʺ _ʺx2Eʺ_1, __GeneratedOdataV4.CstNodes.Inners._ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ _ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ_1)
        {
            this._namespace_1 = _namespace_1;
            this._ʺx2Eʺ_1 = _ʺx2Eʺ_1;
            this._ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ_1 = _ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ_1;
        }
        
        public __GeneratedOdataV4.CstNodes.Rules._namespace _namespace_1 { get; }
        public __GeneratedOdataV4.CstNodes.Inners._ʺx2Eʺ _ʺx2Eʺ_1 { get; }
        public __GeneratedOdataV4.CstNodes.Inners._ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ _ⲤentityColFunction_functionExprParameters_꘡collectionNavigationExpr꘡ⳆentityFunction_functionExprParameters_꘡singleNavigationExpr꘡ⳆcomplexColFunction_functionExprParameters_꘡complexColPathExpr꘡ⳆcomplexFunction_functionExprParameters_꘡complexPathExpr꘡ⳆprimitiveColFunction_functionExprParameters_꘡collectionPathExpr꘡ⳆprimitiveFunction_functionExprParameters_꘡primitivePathExpr꘡Ↄ_1 { get; }
    }
    
}
