//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name: CustomDataBinding.cs
// Generation date: 6/11/2010 4:23:54 PM
namespace AstoriaUnitTests.Stubs.CustomDataClient
{
    
    /// <summary>
    /// There are no comments for CustomDataContext in the schema.
    /// </summary>
    public partial class CustomDataContext : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new CustomDataContext object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public CustomDataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            return clientType.FullName;
        }
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Customer> Customers
        {
            get
            {
                if ((this._Customers == null))
                {
                    this._Customers = base.CreateQuery<Customer>("Customers");
                }
                return this._Customers;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Customer> _Customers;
        /// <summary>
        /// There are no comments for EmptySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<EmptySetEntity> EmptySet
        {
            get
            {
                if ((this._EmptySet == null))
                {
                    this._EmptySet = base.CreateQuery<EmptySetEntity>("EmptySet");
                }
                return this._EmptySet;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<EmptySetEntity> _EmptySet;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Order> Orders
        {
            get
            {
                if ((this._Orders == null))
                {
                    this._Orders = base.CreateQuery<Order>("Orders");
                }
                return this._Orders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Order> _Orders;
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<AstoriaUnitTests.Stubs.CustomDataClient.OtherNs.Region> Regions
        {
            get
            {
                if ((this._Regions == null))
                {
                    this._Regions = base.CreateQuery<AstoriaUnitTests.Stubs.CustomDataClient.OtherNs.Region>("Regions");
                }
                return this._Regions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<AstoriaUnitTests.Stubs.CustomDataClient.OtherNs.Region> _Regions;
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<Product> Products
        {
            get
            {
                if ((this._Products == null))
                {
                    this._Products = base.CreateQuery<Product>("Products");
                }
                return this._Products;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<Product> _Products;
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceQuery<OrderDetail> OrderDetails
        {
            get
            {
                if ((this._OrderDetails == null))
                {
                    this._OrderDetails = base.CreateQuery<OrderDetail>("OrderDetails");
                }
                return this._OrderDetails;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<OrderDetail> _OrderDetails;
        /// <summary>
        /// There are no comments for Customers in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
        /// <summary>
        /// There are no comments for EmptySet in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToEmptySet(EmptySetEntity emptySetEntity)
        {
            base.AddObject("EmptySet", emptySetEntity);
        }
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToOrders(Order order)
        {
            base.AddObject("Orders", order);
        }
    
        /// <summary>
        /// There are no comments for Regions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToRegions(AstoriaUnitTests.Stubs.CustomDataClient.OtherNs.Region region)
        {
            base.AddObject("Regions", region);
        }
        /// <summary>
        /// There are no comments for Products in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public void AddToOrderDetails(OrderDetail orderDetail)
        {
            base.AddObject("OrderDetails", orderDetail);
        }
    }
    /// <summary>
    /// There are no comments for ComplexType AstoriaUnitTests.Stubs.Address in the schema.
    /// </summary>
    public partial class Address : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// There are no comments for Property StreetAddress in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string StreetAddress
        {
            get
            {
                return this._StreetAddress;
            }
            set
            {
                this.OnStreetAddressChanging(value);
                this._StreetAddress = value;
                this.OnStreetAddressChanged();
                this.OnPropertyChanged("StreetAddress");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _StreetAddress;
        partial void OnStreetAddressChanging(string value);
        partial void OnStreetAddressChanged();
        /// <summary>
        /// There are no comments for Property City in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string City
        {
            get
            {
                return this._City;
            }
            set
            {
                this.OnCityChanging(value);
                this._City = value;
                this.OnCityChanged();
                this.OnPropertyChanged("City");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _City;
        partial void OnCityChanging(string value);
        partial void OnCityChanged();
        /// <summary>
        /// There are no comments for Property State in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string State
        {
            get
            {
                return this._State;
            }
            set
            {
                this.OnStateChanging(value);
                this._State = value;
                this.OnStateChanged();
                this.OnPropertyChanged("State");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _State;
        partial void OnStateChanging(string value);
        partial void OnStateChanged();
        /// <summary>
        /// There are no comments for Property PostalCode in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string PostalCode
        {
            get
            {
                return this._PostalCode;
            }
            set
            {
                this.OnPostalCodeChanging(value);
                this._PostalCode = value;
                this.OnPostalCodeChanged();
                this.OnPropertyChanged("PostalCode");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _PostalCode;
        partial void OnPostalCodeChanging(string value);
        partial void OnPostalCodeChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("Customers")]
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class Customer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="guidValue">Initial value of GuidValue.</param>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static Customer CreateCustomer(Address address, global::System.Guid guidValue, int ID)
        {
            Customer customer = new Customer();
            if ((address == null))
            {
                throw new global::System.ArgumentNullException("address");
            }
            customer.Address = address;
            customer.GuidValue = guidValue;
            customer.ID = ID;
            return customer;
        }
        /// <summary>
        /// There are no comments for Property Address in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public Address Address
        {
            get
            {
                if (((this._Address == null) 
                            && (this._AddressInitialized != true)))
                {
                    this._Address = new Address();
                    this._AddressInitialized = true;
                }
                return this._Address;
            }
            set
            {
                this.OnAddressChanging(value);
                this._Address = value;
                this._AddressInitialized = true;
                this.OnAddressChanged();
                this.OnPropertyChanged("Address");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private Address _Address;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private bool _AddressInitialized;
        partial void OnAddressChanging(Address value);
        partial void OnAddressChanged();
        /// <summary>
        /// There are no comments for Property GuidValue in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::System.Guid GuidValue
        {
            get
            {
                return this._GuidValue;
            }
            set
            {
                this.OnGuidValueChanging(value);
                this._GuidValue = value;
                this.OnGuidValueChanged();
                this.OnPropertyChanged("GuidValue");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::System.Guid _GuidValue;
        partial void OnGuidValueChanging(global::System.Guid value);
        partial void OnGuidValueChanged();
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property NameAsHtml in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string NameAsHtml
        {
            get
            {
                return this._NameAsHtml;
            }
            set
            {
                this.OnNameAsHtmlChanging(value);
                this._NameAsHtml = value;
                this.OnNameAsHtmlChanged();
                this.OnPropertyChanged("NameAsHtml");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _NameAsHtml;
        partial void OnNameAsHtmlChanging(string value);
        partial void OnNameAsHtmlChanged();
        /// <summary>
        /// There are no comments for BestFriend in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public Customer BestFriend
        {
            get
            {
                return this._BestFriend;
            }
            set
            {
                this._BestFriend = value;
                this.OnPropertyChanged("BestFriend");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private Customer _BestFriend;
        /// <summary>
        /// There are no comments for Orders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<Order> Orders
        {
            get
            {
                return this._Orders;
            }
            set
            {
                this._Orders = value;
                this.OnPropertyChanged("Orders");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<Order> _Orders = new global::Microsoft.OData.Client.DataServiceCollection<Order>(null, Microsoft.OData.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.CustomerWithBirthday in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class CustomerWithBirthday : Customer
    {
        /// <summary>
        /// Create a new CustomerWithBirthday object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="guidValue">Initial value of GuidValue.</param>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="birthday">Initial value of Birthday.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static CustomerWithBirthday CreateCustomerWithBirthday(Address address, global::System.Guid guidValue, int ID, global::System.DateTimeOffset birthday)
        {
            CustomerWithBirthday customerWithBirthday = new CustomerWithBirthday();
            if ((address == null))
            {
                throw new global::System.ArgumentNullException("address");
            }
            customerWithBirthday.Address = address;
            customerWithBirthday.GuidValue = guidValue;
            customerWithBirthday.ID = ID;
            customerWithBirthday.Birthday = birthday;
            return customerWithBirthday;
        }
        /// <summary>
        /// There are no comments for Property Birthday in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::System.DateTimeOffset Birthday
        {
            get
            {
                return this._Birthday;
            }
            set
            {
                this.OnBirthdayChanging(value);
                this._Birthday = value;
                this.OnBirthdayChanged();
                this.OnPropertyChanged("Birthday");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::System.DateTimeOffset _Birthday;
        partial void OnBirthdayChanging(global::System.DateTimeOffset value);
        partial void OnBirthdayChanged();
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.CustomerWithoutProperties in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class CustomerWithoutProperties : CustomerWithBirthday
    {
        /// <summary>
        /// Create a new CustomerWithoutProperties object.
        /// </summary>
        /// <param name="address">Initial value of Address.</param>
        /// <param name="guidValue">Initial value of GuidValue.</param>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="birthday">Initial value of Birthday.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static CustomerWithoutProperties CreateCustomerWithoutProperties(Address address, global::System.Guid guidValue, int ID, global::System.DateTime birthday)
        {
            CustomerWithoutProperties customerWithoutProperties = new CustomerWithoutProperties();
            if ((address == null))
            {
                throw new global::System.ArgumentNullException("address");
            }
            customerWithoutProperties.Address = address;
            customerWithoutProperties.GuidValue = guidValue;
            customerWithoutProperties.ID = ID;
            customerWithoutProperties.Birthday = birthday;
            return customerWithoutProperties;
        }
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.EmptySetEntity in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("EmptySet")]
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class EmptySetEntity : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new EmptySetEntity object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static EmptySetEntity CreateEmptySetEntity(int ID)
        {
            EmptySetEntity emptySetEntity = new EmptySetEntity();
            emptySetEntity.ID = ID;
            return emptySetEntity;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType AstoriaUnitTests.Stubs.CurrencyAmount in the schema.
    /// </summary>
    public partial class CurrencyAmount : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new CurrencyAmount object.
        /// </summary>
        /// <param name="amount">Initial value of Amount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static CurrencyAmount CreateCurrencyAmount(decimal amount)
        {
            CurrencyAmount currencyAmount = new CurrencyAmount();
            currencyAmount.Amount = amount;
            return currencyAmount;
        }
        /// <summary>
        /// There are no comments for Property Amount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public decimal Amount
        {
            get
            {
                return this._Amount;
            }
            set
            {
                this.OnAmountChanging(value);
                this._Amount = value;
                this.OnAmountChanged();
                this.OnPropertyChanged("Amount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private decimal _Amount;
        partial void OnAmountChanging(decimal value);
        partial void OnAmountChanged();
        /// <summary>
        /// There are no comments for Property CurrencyName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string CurrencyName
        {
            get
            {
                return this._CurrencyName;
            }
            set
            {
                this.OnCurrencyNameChanging(value);
                this._CurrencyName = value;
                this.OnCurrencyNameChanged();
                this.OnPropertyChanged("CurrencyName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _CurrencyName;
        partial void OnCurrencyNameChanging(string value);
        partial void OnCurrencyNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.Order in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("Orders")]
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class Order : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Order object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="dollarAmount">Initial value of DollarAmount.</param>
        /// <param name="currencyAmount">Initial value of CurrencyAmount.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static Order CreateOrder(int ID, double dollarAmount, CurrencyAmount currencyAmount)
        {
            Order order = new Order();
            order.ID = ID;
            order.DollarAmount = dollarAmount;
            if ((currencyAmount == null))
            {
                throw new global::System.ArgumentNullException("currencyAmount");
            }
            order.CurrencyAmount = currencyAmount;
            return order;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property DollarAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public double DollarAmount
        {
            get
            {
                return this._DollarAmount;
            }
            set
            {
                this.OnDollarAmountChanging(value);
                this._DollarAmount = value;
                this.OnDollarAmountChanged();
                this.OnPropertyChanged("DollarAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private double _DollarAmount;
        partial void OnDollarAmountChanging(double value);
        partial void OnDollarAmountChanged();
        /// <summary>
        /// There are no comments for Property CurrencyAmount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public CurrencyAmount CurrencyAmount
        {
            get
            {
                if (((this._CurrencyAmount == null) 
                            && (this._CurrencyAmountInitialized != true)))
                {
                    this._CurrencyAmount = new CurrencyAmount();
                    this._CurrencyAmountInitialized = true;
                }
                return this._CurrencyAmount;
            }
            set
            {
                this.OnCurrencyAmountChanging(value);
                this._CurrencyAmount = value;
                this._CurrencyAmountInitialized = true;
                this.OnCurrencyAmountChanged();
                this.OnPropertyChanged("CurrencyAmount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private CurrencyAmount _CurrencyAmount;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private bool _CurrencyAmountInitialized;
        partial void OnCurrencyAmountChanging(CurrencyAmount value);
        partial void OnCurrencyAmountChanged();
        /// <summary>
        /// There are no comments for Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public Customer Customer
        {
            get
            {
                return this._Customer;
            }
            set
            {
                this._Customer = value;
                this.OnPropertyChanged("Customer");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private Customer _Customer;
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<OrderDetail> OrderDetails
        {
            get
            {
                return this._OrderDetails;
            }
            set
            {
                this._OrderDetails = value;
                this.OnPropertyChanged("OrderDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<OrderDetail> _OrderDetails = new global::Microsoft.OData.Client.DataServiceCollection<OrderDetail>(null, Microsoft.OData.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
   
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.Product in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("Products")]
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class Product : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="discontinued">Initial value of Discontinued.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static Product CreateProduct(int ID, bool discontinued)
        {
            Product product = new Product();
            product.ID = ID;
            product.Discontinued = discontinued;
            return product;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property ProductName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string ProductName
        {
            get
            {
                return this._ProductName;
            }
            set
            {
                this.OnProductNameChanging(value);
                this._ProductName = value;
                this.OnProductNameChanged();
                this.OnPropertyChanged("ProductName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _ProductName;
        partial void OnProductNameChanging(string value);
        partial void OnProductNameChanged();
        /// <summary>
        /// There are no comments for Property Discontinued in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public bool Discontinued
        {
            get
            {
                return this._Discontinued;
            }
            set
            {
                this.OnDiscontinuedChanging(value);
                this._Discontinued = value;
                this.OnDiscontinuedChanged();
                this.OnPropertyChanged("Discontinued");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private bool _Discontinued;
        partial void OnDiscontinuedChanging(bool value);
        partial void OnDiscontinuedChanged();
        /// <summary>
        /// There are no comments for OrderDetails in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public global::Microsoft.OData.Client.DataServiceCollection<OrderDetail> OrderDetails
        {
            get
            {
                return this._OrderDetails;
            }
            set
            {
                this._OrderDetails = value;
                this.OnPropertyChanged("OrderDetails");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<OrderDetail> _OrderDetails = new global::Microsoft.OData.Client.DataServiceCollection<OrderDetail>(null, Microsoft.OData.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.OrderDetail in the schema.
    /// </summary>
    /// <KeyProperties>
    /// OrderID
    /// ProductID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("OrderDetails")]
    [global::Microsoft.OData.Client.KeyAttribute("OrderID", "ProductID")]
    public partial class OrderDetail : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new OrderDetail object.
        /// </summary>
        /// <param name="orderID">Initial value of OrderID.</param>
        /// <param name="productID">Initial value of ProductID.</param>
        /// <param name="unitPrice">Initial value of UnitPrice.</param>
        /// <param name="quantity">Initial value of Quantity.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static OrderDetail CreateOrderDetail(int orderID, int productID, double unitPrice, short quantity)
        {
            OrderDetail orderDetail = new OrderDetail();
            orderDetail.OrderID = orderID;
            orderDetail.ProductID = productID;
            orderDetail.UnitPrice = unitPrice;
            orderDetail.Quantity = quantity;
            return orderDetail;
        }
        /// <summary>
        /// There are no comments for Property OrderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int OrderID
        {
            get
            {
                return this._OrderID;
            }
            set
            {
                this.OnOrderIDChanging(value);
                this._OrderID = value;
                this.OnOrderIDChanged();
                this.OnPropertyChanged("OrderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _OrderID;
        partial void OnOrderIDChanging(int value);
        partial void OnOrderIDChanged();
        /// <summary>
        /// There are no comments for Property ProductID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ProductID
        {
            get
            {
                return this._ProductID;
            }
            set
            {
                this.OnProductIDChanging(value);
                this._ProductID = value;
                this.OnProductIDChanged();
                this.OnPropertyChanged("ProductID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ProductID;
        partial void OnProductIDChanging(int value);
        partial void OnProductIDChanged();
        /// <summary>
        /// There are no comments for Property UnitPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public double UnitPrice
        {
            get
            {
                return this._UnitPrice;
            }
            set
            {
                this.OnUnitPriceChanging(value);
                this._UnitPrice = value;
                this.OnUnitPriceChanged();
                this.OnPropertyChanged("UnitPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private double _UnitPrice;
        partial void OnUnitPriceChanging(double value);
        partial void OnUnitPriceChanged();
        /// <summary>
        /// There are no comments for Property Quantity in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public short Quantity
        {
            get
            {
                return this._Quantity;
            }
            set
            {
                this.OnQuantityChanging(value);
                this._Quantity = value;
                this.OnQuantityChanged();
                this.OnPropertyChanged("Quantity");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private short _Quantity;
        partial void OnQuantityChanging(short value);
        partial void OnQuantityChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
// Original file name: CustomDataBinding.cs
// Generation date: 6/11/2010 4:23:54 PM
namespace AstoriaUnitTests.Stubs.CustomDataClient.OtherNs
{
    
    /// <summary>
    /// There are no comments for AstoriaUnitTests.Stubs.CustomDataClient.OtherNs.Region in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::Microsoft.OData.Client.EntitySetAttribute("Regions")]
    [global::Microsoft.OData.Client.KeyAttribute("ID")]
    public partial class Region : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Region object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public static Region CreateRegion(int ID)
        {
            Region region = new Region();
            region.ID = ID;
            return region;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Service.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
