//---------------------------------------------------------------------
// <copyright file="SRResourcesTests.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

using System.Linq;
using System.Text.RegularExpressions;
using Xunit;

namespace Microsoft.OData.Edm.Tests.Resources;

public class SRResourcesTests
{
    [Theory]
    [InlineData("Annotations_TypeMismatch", new object[] { "Value1", "Value2" })]
    [InlineData("Bad_AmbiguousElementBinding", new object[] { "Value1" })]
    [InlineData("Bad_AmbiguousOperation", new object[] { "Value1" })]
    [InlineData("Bad_CyclicComplex", new object[] { "Value1" })]
    [InlineData("Bad_CyclicEntity", new object[] { "Value1" })]
    [InlineData("Bad_CyclicEntityContainer", new object[] { "Value1" })]
    [InlineData("Bad_OperationParametersDontMatch", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedComplexType", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedEntityContainer", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedEntitySet", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedEntityType", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedEnumMember", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedEnumType", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedLabeledElement", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedNavigationPropertyPath", new object[] { "Value1", "Value2" })]
    [InlineData("Bad_UnresolvedOperation", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedParameter", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedPrimitiveType", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedProperty", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedReturn", new object[] { "Value1" })]
    [InlineData("Bad_UnresolvedType", new object[] { "Value1" })]
    [InlineData("Constructable_DependentPropertyCountMustMatchNumberOfPropertiesOnPrincipalType", new object[] { "Value1", "Value2" })]
    [InlineData("Constructable_EntityTypeOrCollectionOfEntityTypeExpected", new object[] { })]
    [InlineData("Constructable_TargetMustBeStock", new object[] { "Value1" })]
    [InlineData("Constructable_VocabularyAnnotationMustHaveTarget", new object[] { })]
    [InlineData("CsdlJsonParser_CannotReadValueAsType", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("CsdlJsonParser_InvalidCsdlVersion", new object[] { "Value1" })]
    [InlineData("CsdlJsonParser_InvalidJsonNumberType", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_MissingKindMember", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_MissingMemberInObject", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_MissingRequiredPropertyInObject", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_SchemaCannotHaveMoreThanOneEntityContainer", new object[] { "Value1" })]
    [InlineData("CsdlJsonParser_UnexpectedJsonMember", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_UnexpectedJsonValueKind", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("CsdlJsonParser_UnknownJsonElementValueKind", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlJsonParser_UnsupportedJsonMember", new object[] { "Value1" })]
    [InlineData("CsdlParser_CannotSpecifyNullableAttributeForNavigationPropertyWithCollectionType", new object[] { })]
    [InlineData("CsdlParser_InvalidAlias", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidCastExpressionIncorrectNumberOfOperands", new object[] { })]
    [InlineData("CsdlParser_InvalidDeleteAction", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidEndRoleInRelationshipConstraint", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlParser_InvalidEntitySetPath", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidEntitySetPathWithUnboundAction", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlParser_InvalidEnumMemberPath", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidIfExpressionIncorrectNumberOfOperands", new object[] { })]
    [InlineData("CsdlParser_InvalidIsOfExpressionIncorrectNumberOfOperands", new object[] { })]
    [InlineData("CsdlParser_InvalidLabeledElementExpressionIncorrectNumberOfOperands", new object[] { })]
    [InlineData("CsdlParser_InvalidMultiplicity", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidQualifiedName", new object[] { "Value1" })]
    [InlineData("CsdlParser_InvalidTypeName", new object[] { "Value1" })]
    [InlineData("CsdlParser_MetadataDocumentCannotHaveMoreThanOneEntityContainer", new object[] { })]
    [InlineData("CsdlParser_MissingTypeAttributeOrElement", new object[] { })]
    [InlineData("CsdlParser_NoReadersProvided", new object[] { })]
    [InlineData("CsdlParser_NullXmlReader", new object[] { })]
    [InlineData("CsdlParser_ReferentialConstraintRequiresOneDependent", new object[] { })]
    [InlineData("CsdlParser_ReferentialConstraintRequiresOnePrincipal", new object[] { })]
    [InlineData("CsdlSemantics_DuplicateAlias", new object[] { "Value1", "Value2" })]
    [InlineData("CsdlSemantics_EnumMemberMustHaveValue", new object[] { })]
    [InlineData("CsdlSemantics_ImpossibleAnnotationsTarget", new object[] { "Value1" })]
    [InlineData("CsdlSemantics_ReferentialConstraintMismatch", new object[] { })]
    [InlineData("Date_InvalidAddedOrSubtractedResults", new object[] { })]
    [InlineData("Date_InvalidCompareToTarget", new object[] { "Value1" })]
    [InlineData("Date_InvalidDateParameters", new object[] { "Value1", "Value2", "Value3" })]
    [InlineData("Date_InvalidParsingString", new object[] { "Value1" })]
    [InlineData("Edm_Evaluator_FailedTypeAssertion", new object[] { "Value1" })]
    [InlineData("Edm_Evaluator_NoContextPath", new object[] { })]
    [InlineData("Edm_Evaluator_NoTermTypeAnnotationOnType", new object[] { "Value1", "Value2" })]
    [InlineData("Edm_Evaluator_NoValueAnnotationOnElement", new object[] { "Value1" })]
    [InlineData("Edm_Evaluator_NoValueAnnotationOnType", new object[] { "Value1", "Value2" })]
    [InlineData("Edm_Evaluator_TypeCastNeedsEdmModel", new object[] { })]
    [InlineData("Edm_Evaluator_UnboundFunction", new object[] { "Value1" })]
    [InlineData("Edm_Evaluator_UnboundPath", new object[] { "Value1" })]
    [InlineData("Edm_Evaluator_UnrecognizedExpressionKind", new object[] { "Value1" })]
    [InlineData("EdmEntityContainer_CannotUseElementWithTypeNone", new object[] { })]
    [InlineData("EdmModel_CannotAddMoreThanOneEntityContainerToOneEdmModel", new object[] { })]
    [InlineData("EdmModel_CannotUseElementWithTypeNone", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_AmbiguousType", new object[] { "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_BadNavigationPropertyCouldNotDetermineType", new object[] { "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_BadNavigationPropertyRolesCannotBeTheSame", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_BaseTypeMustHaveSameTypeKind", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_BaseTypeOfOpenTypeMustBeOpen", new object[] { "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_BinaryConstantLengthOutOfRange", new object[] { "Length", "MaxLength" })]
    [InlineData("EdmModel_Validator_Semantic_BoundFunctionOverloadsMustHaveSameReturnType", new object[] { "FunctionName", "ExpectedType" })]
    [InlineData("EdmModel_Validator_Semantic_BoundOperationMustHaveParameters", new object[] { "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_CannotAssertNullableTypeAsNonNullableType", new object[] { "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_CannotInferEntitySetWithMultipleSetsPerType", new object[] { "AssociationSetName", "RoleType", "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_CollectionExpressionNotValidForNonCollectionType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_ComplexTypeMustHaveProperties", new object[] { "ComplexTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_DeclaringTypeMustBeCorrect", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_DeclaringTypeOfNavigationSourceCannotHavePathProperty", new object[] { "DeclaringType", "Name", "NavigationSourceName" })]
    [InlineData("EdmModel_Validator_Semantic_DependentPropertiesMustBelongToDependentEntity", new object[] { "PropertyName", "DependentEntityName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateAnnotation", new object[] { "ElementName", "TermName", "Qualifier" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateDependentProperty", new object[] { "PropertyName", "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateEndName", new object[] { "EndName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateEntityContainerMemberName", new object[] { "MemberName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateEntityContainerName", new object[] { "ContainerName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicateNavigationPropertyMapping", new object[] { "EntitySetName", "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_DuplicatePropertyNameSpecifiedInEntityKey", new object[] { "EntityTypeName", "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_EdmEntityTypeCannotBeTypeOfEntitySet", new object[] { "EntitySetName" })]
    [InlineData("EdmModel_Validator_Semantic_EdmEntityTypeCannotBeTypeOfSingleton", new object[] { "SingletonName" })]
    [InlineData("EdmModel_Validator_Semantic_EdmPrimitiveTypeCannotBeUsedAsTypeOfKey", new object[] { "KeyPropertyName", "EntityTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_EdmPrimitiveTypeCannotBeUsedAsUnderlyingType", new object[] { "UnderlyingTypeName", "EnumTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_ElementDirectValueAnnotationFullNameMustBeUnique", new object[] { "Namespace", "Name" })]
    [InlineData("EdmModel_Validator_Semantic_EndNameAlreadyDefinedDuplicate", new object[] { "EndName" })]
    [InlineData("EdmModel_Validator_Semantic_EndWithManyMultiplicityCannotHaveOperationsSpecified", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_EntityComposableBoundEscapeFunctionMustBeLessOne", new object[] { "EntityTypeName", "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_EntityContainerElementMustNotHaveKindOfNone", new object[] { "ElementName" })]
    [InlineData("EdmModel_Validator_Semantic_EntityKeyMustBeScalar", new object[] { "PropertyName", "EntityTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_EntityNoncomposableBoundEscapeFunctionMustBeLessOne", new object[] { "EntityTypeName", "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_EntitySetCanOnlyBeContainedByASingleNavigationProperty", new object[] { "EntitySetName" })]
    [InlineData("EdmModel_Validator_Semantic_EntitySetRecursiveNavigationPropertyMappingsMustPointBackToSourceEntitySet", new object[] { "NavigationPropertyName", "EntitySetName" })]
    [InlineData("EdmModel_Validator_Semantic_EntitySetTypeMustBeCollectionOfEntityType", new object[] { "EntitySetName", "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_EnumMemberNameAlreadyDefined", new object[] { "EnumMemberName" })]
    [InlineData("EdmModel_Validator_Semantic_EnumMemberValueOutOfRange", new object[] { "EnumMemberName" })]
    [InlineData("EdmModel_Validator_Semantic_EnumMustHaveIntegralUnderlyingType", new object[] { "EnumTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_ExpressionEnumKindNotValidForAssertedType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_ExpressionNotValidForTheAssertedType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_ExpressionPrimitiveKindCannotPromoteToAssertedType", new object[] { "PrimitiveType", "AssertedType" })]
    [InlineData("EdmModel_Validator_Semantic_ExpressionPrimitiveKindNotValidForAssertedType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_FunctionImportWithParameterShouldNotBeIncludedInServiceDocument", new object[] { "FunctionImportName" })]
    [InlineData("EdmModel_Validator_Semantic_FunctionMustHaveReturnType", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_InaccessibleTarget", new object[] { "TargetName" })]
    [InlineData("EdmModel_Validator_Semantic_InaccessibleTerm", new object[] { "TermName" })]
    [InlineData("EdmModel_Validator_Semantic_InaccessibleType", new object[] { "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_IncorrectNumberOfArguments", new object[] { "ProvidedArguments", "FunctionName", "ExpectedArguments" })]
    [InlineData("EdmModel_Validator_Semantic_IntegerConstantValueOutOfRange", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidComplexTypeAbstract", new object[] { "ComplexTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidComplexTypePolymorphic", new object[] { "ComplexTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidElementAnnotationMismatchedTerm", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidElementAnnotationNotIEdmStringValue", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidElementAnnotationNullNamespaceOrName", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidElementAnnotationValueInvalidXml", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathInvalidTypeCastSegment", new object[] { "AttributeName", "Path", "EntityType", "TypeSegment" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathMissingBindingParameterName", new object[] { "AttributeName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathTypeCastSegmentMustBeEntityType", new object[] { "AttributeName", "Path", "TypeSegment" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathUnknownNavigationProperty", new object[] { "AttributeName", "Path", "NavigationProperty" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathUnknownTypeCastSegment", new object[] { "AttributeName", "Path", "TypeSegment" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathWithFirstPathParameterNotMatchingFirstParameterName", new object[] { "AttributeName", "Path", "FirstPathParameter", "ParameterName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidEntitySetPathWithNonEntityBindingParameter", new object[] { "AttributeName", "Path", "BindingParameterType" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidKeyKeyDefinedInBaseClass", new object[] { "EntityTypeName", "BaseClassName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidKeyNullablePart", new object[] { "KeyPart", "EntityTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidMemberNameMatchesTypeName", new object[] { "MemberName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidMultiplicityOfDependentEndMustBeMany", new object[] { "DependentEndName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidMultiplicityOfDependentEndMustBeZeroOneOrOne", new object[] { "DependentEndName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidMultiplicityOfPrincipalEndDependentPropertiesAllNonnullable", new object[] { "NavigationName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidMultiplicityOfPrincipalEndDependentPropertiesAllNullable", new object[] { "NavigationName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidNavigationPropertyType", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidOperationMultipleEndsInAssociation", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_InvalidPropertyInRelationshipConstraintDependentEnd", new object[] { "PropertyName", "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidPropertyInRelationshipConstraintPrimaryEnd", new object[] { "AssociationName", "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_InvalidPropertyType", new object[] { "PropertyType" })]
    [InlineData("EdmModel_Validator_Semantic_IsUnboundedCannotBeTrueWhileMaxLengthIsNotNull", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_KeyMissingOnEntityType", new object[] { "EntityTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_KeyPropertyMustBelongToEntity", new object[] { "KeyPropertyName", "EntityName" })]
    [InlineData("EdmModel_Validator_Semantic_MaxLengthOutOfRange", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_MismatchNumberOfPropertiesinRelationshipConstraint", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateBoundActions", new object[] { "ActionName" })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateBoundFunctionParameterNames", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateBoundFunctionParameterTypes", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateUnBoundActions", new object[] { "ActionName" })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateUnBoundFunctionsParameterNames", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_ModelDuplicateUnBoundFunctionsParameterTypes", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationMappingMustBeBidirectional", new object[] { "EntitySetName", "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyEntityMustNotIndirectlyContainItself", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyMappingMustPointToValidTargetForProperty", new object[] { "NavigationPropertyName", "EntitySetName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyOfCollectionTypeMustNotTargetToSingleton", new object[] { "NavigationPropertyName", "SingletonName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyPrincipalEndMultiplicityUpperBoundMustBeOne", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyWithNonRecursiveContainmentSourceMustBeFromOne", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyWithRecursiveContainmentSourceMustBeFromZeroOrOne", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationPropertyWithRecursiveContainmentTargetMustBeOptional", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_NavigationSourceTypeHasNoKeys", new object[] { "EntitySetName", "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_NoEntitySetsFoundForType", new object[] { "AssociationSetName", "RoleType", "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_NullCannotBeAssertedToBeANonNullableType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_OpenTypesSupportedForEntityTypesOnly", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_OperationCannotHaveEntitySetPathWithUnBoundOperation", new object[] { "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportCannotImportBoundOperation", new object[] { "OperationImportName", "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportEntitySetExpressionIsInvalid", new object[] { "OperationImportName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportEntitySetExpressionKindIsInvalid", new object[] { "OperationImportName", "EntitySetKind" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportEntityTypeDoesNotMatchEntitySet", new object[] { "OperationImportName", "EntityTypeName", "EntitySetName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportEntityTypeDoesNotMatchEntitySet2", new object[] { "OperationImportName", "EntityTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationImportSpecifiesEntitySetButNotEntityType", new object[] { "OperationImportName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationReturnTypeCannotBeCollectionOfAbstractType", new object[] { "TypeName", "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationWithEntitySetPathAndReturnTypeTypeNotAssignable", new object[] { "OperationName", "EntityTypeName", "ReturnTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationWithEntitySetPathResolvesToCollectionEntityTypeMismatchesEntityTypeReturnType", new object[] { "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationWithEntitySetPathReturnTypeInvalid", new object[] { "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_OperationWithUnsupportedReturnType", new object[] { "OperationName" })]
    [InlineData("EdmModel_Validator_Semantic_ParameterNameAlreadyDefinedDuplicate", new object[] { "ParameterName" })]
    [InlineData("EdmModel_Validator_Semantic_PathIsNotValidForTheGivenContext", new object[] { "PathSegment" })]
    [InlineData("EdmModel_Validator_Semantic_PrecisionOutOfRange", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_PrimitiveConstantExpressionNotValidForNonPrimitiveType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_PrimitiveTypeMustNotHaveKindOfNone", new object[] { "PrimitiveTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_PropertyMustNotHaveKindOfNone", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_PropertyNameAlreadyDefined", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_PropertyTypeCannotBeCollectionOfAbstractType", new object[] { "PropertyName", "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_RecordExpressionHasExtraProperties", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_RecordExpressionMissingProperty", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_RecordExpressionNotValidForNonStructuredType", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_RecursiveComplexTypedPropertyMustBeOptional", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_RequiredParametersMustPrecedeOptional", new object[] { "ParameterName" })]
    [InlineData("EdmModel_Validator_Semantic_SameRoleReferredInReferentialConstraint", new object[] { "RoleName" })]
    [InlineData("EdmModel_Validator_Semantic_ScaleOutOfRange", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_SchemaElementMustNotHaveKindOfNone", new object[] { "ElementName" })]
    [InlineData("EdmModel_Validator_Semantic_SchemaElementNameAlreadyDefined", new object[] { "ElementName" })]
    [InlineData("EdmModel_Validator_Semantic_SingletonTypeMustBeEntityType", new object[] { "SingletonName", "TypeName" })]
    [InlineData("EdmModel_Validator_Semantic_StringConstantLengthOutOfRange", new object[] { "StringValue", "MaxLength" })]
    [InlineData("EdmModel_Validator_Semantic_StringMaxLengthOutOfRange", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_StructuredTypeBaseTypeCannotBeAbstractType", new object[] { "BaseTypeName", "Arg1", "DerivedTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_SystemNamespaceEncountered", new object[] { "NamespaceName" })]
    [InlineData("EdmModel_Validator_Semantic_TypeAnnotationHasExtraProperties", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_TypeAnnotationMissingRequiredProperty", new object[] { "PropertyName" })]
    [InlineData("EdmModel_Validator_Semantic_TypeMismatchRelationshipConstraint", new object[] { "DependentProperty", "DependentEntity", "PrincipalProperty", "PrincipalEntity" })]
    [InlineData("EdmModel_Validator_Semantic_TypeMustNotHaveKindOfNone", new object[] { })]
    [InlineData("EdmModel_Validator_Semantic_TypeOfNavigationPropertyCannotHavePathProperty", new object[] { "NavigationPropertyType", "NavigationPropertyName", "DeclaringTypeName" })]
    [InlineData("EdmModel_Validator_Semantic_UnboundFunctionOverloadHasIncorrectReturnType", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_UrlEscapeFunctionMustBoundFunction", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_UrlEscapeFunctionMustHaveOneStringParameter", new object[] { "FunctionName" })]
    [InlineData("EdmModel_Validator_Semantic_VocabularyAnnotationApplyToNotAllowedAnnotatable", new object[] { "TargetName", "AppliesTo", "TermName" })]
    [InlineData("EdmModel_Validator_Syntactic_EdmModel_NameIsNotAllowed", new object[] { "Name" })]
    [InlineData("EdmModel_Validator_Syntactic_EdmModel_NameIsTooLong", new object[] { "Name" })]
    [InlineData("EdmModel_Validator_Syntactic_EdmModel_NamespaceNameIsNotAllowed", new object[] { "NamespaceName" })]
    [InlineData("EdmModel_Validator_Syntactic_EdmModel_NamespaceNameIsTooLong", new object[] { "NamespaceName" })]
    [InlineData("EdmModel_Validator_Syntactic_EnumerableMustNotHaveNullElements", new object[] { "PropertyName", "TypeName" })]
    [InlineData("EdmModel_Validator_Syntactic_EnumPropertyValueOutOfRange", new object[] { "Namespace", "PropertyName", "TypeName", "EnumValue" })]
    [InlineData("EdmModel_Validator_Syntactic_InterfaceCriticalCycleInTypeHierarchy", new object[] { "TypeName" })]
    [InlineData("EdmModel_Validator_Syntactic_InterfaceKindValueMismatch", new object[] { "Value1", "PropertyName", "TypeName", "InterfaceName" })]
    [InlineData("EdmModel_Validator_Syntactic_InterfaceKindValueUnexpected", new object[] { "PropertyName", "TypeName", "KindValue" })]
    [InlineData("EdmModel_Validator_Syntactic_MissingName", new object[] { })]
    [InlineData("EdmModel_Validator_Syntactic_MissingNamespaceName", new object[] { })]
    [InlineData("EdmModel_Validator_Syntactic_NavigationPartnerInvalid", new object[] { "NavigationPropertyName" })]
    [InlineData("EdmModel_Validator_Syntactic_PropertyMustNotBeNull", new object[] { "PropertyName", "TypeName" })]
    [InlineData("EdmModel_Validator_Syntactic_TypeRefInterfaceTypeKindValueMismatch", new object[] { "InterfaceName", "TypeKind" })]
    [InlineData("EdmParseException_ErrorsEncounteredInEdmx", new object[] { "ErrorDetails" })]
    [InlineData("EdmPath_UnexpectedKind", new object[] { })]
    [InlineData("EdmPrimitive_UnexpectedKind", new object[] { })]
    [InlineData("EdmToClr_CannotConvertEdmCollectionValueToClrType", new object[] { "ClrTypeName" })]
    [InlineData("EdmToClr_CannotConvertEdmValueToClrType", new object[] { "EdmTypeName", "ClrTypeName" })]
    [InlineData("EdmToClr_IEnumerableOfTPropertyAlreadyHasValue", new object[] { "PropertyName", "ObjectTypeName" })]
    [InlineData("EdmToClr_StructuredPropertyDuplicateValue", new object[] { "PropertyName" })]
    [InlineData("EdmToClr_StructuredValueMappedToNonClass", new object[] { })]
    [InlineData("EdmToClr_TryCreateObjectInstanceReturnedWrongObject", new object[] { "ReturnedTypeName", "ExpectedTypeName" })]
    [InlineData("EdmToClr_UnsupportedType", new object[] { "ClrTypeName" })]
    [InlineData("EdmType_UnexpectedEdmType", new object[] { })]
    [InlineData("EdmUtil_InvalidAnnotationValue", new object[] { "AnnotationName", "AnnotationType" })]
    [InlineData("EdmUtil_NullValueForMimeTypeAnnotation", new object[] { })]
    [InlineData("EdmVocabularyAnnotations_DidNotFindDefaultValue", new object[] { "AnnotationTerm" })]
    [InlineData("EdmVocabularyAnnotations_InvalidLocationForTargetPathAnnotation", new object[] { "TargetPath" })]
    [InlineData("EdmVocabularyAnnotations_TermTypeNotSupported", new object[] { "TermTypeName" })]
    [InlineData("EdmxParser_BodyElement", new object[] { "ElementName" })]
    [InlineData("EdmxParser_EdmxVersionMismatch", new object[] { })]
    [InlineData("EdmxParser_InvalidReferenceIncorrectNumberOfIncludes", new object[] { })]
    [InlineData("EdmxParser_UnresolvedReferenceUriInEdmxReference", new object[] { })]
    [InlineData("MultipleMatchingPropertiesFound", new object[] { "PropertyName", "TypeName" })]
    [InlineData("NavigationPropertyBinding_PathIsNotValid", new object[] { })]
    [InlineData("PathSegmentMustNotContainSlash", new object[] { })]
    [InlineData("PlatformHelper_DateTimeOffsetMustContainTimeZone", new object[] { "DateTimeOffsetValue" })]
    [InlineData("RuleSet_DuplicateRulesExistInRuleSet", new object[] { })]
    [InlineData("Serializer_NonInlineOperationImportReturnType", new object[] { "OperationImportName" })]
    [InlineData("Serializer_NoSchemasProduced", new object[] { })]
    [InlineData("Serializer_OutOfLineAnnotationTargetMustHaveValidName", new object[] { "TargetName" })]
    [InlineData("Serializer_ReferencedTypeMustHaveValidName", new object[] { "TypeName" })]
    [InlineData("Serializer_SingleFileExpected", new object[] { })]
    [InlineData("Serializer_UnknownEdmVersion", new object[] { "EdmVersion" })]
    [InlineData("Serializer_UnknownEdmxVersion", new object[] { "EdmxVersion" })]
    [InlineData("TargetPath_FirstSegmentMustBeIEdmEntityContainer", new object[] { })]
    [InlineData("TargetPath_SecondSegmentMustBeIEdmEntityContainerElement", new object[] { })]
    [InlineData("TargetPath_SegmentsMustNotContainNullSegment", new object[] { })]
    [InlineData("TimeOfDay_ConvertErrorFromTimeSpan", new object[] { "TimeSpanValue" })]
    [InlineData("TimeOfDay_InvalidCompareToTarget", new object[] { "TargetObject" })]
    [InlineData("TimeOfDay_InvalidParsingString", new object[] { "StringValue" })]
    [InlineData("TimeOfDay_InvalidTimeOfDayParameters", new object[] { "Hour", "Minute", "Second", "Millisecond" })]
    [InlineData("TimeOfDay_TicksOutOfRange", new object[] { "TicksValue" })]
    [InlineData("TypeCast_HierarchyNotFollowed", new object[] { "SourceType", "TargetType" })]
    [InlineData("TypeSemantics_CouldNotConvertTypeReference", new object[] { "SourceType", "TargetType" })]
    [InlineData("UnknownEnumVal_ContainerElementKind", new object[] { "ContainerElementKind" })]
    [InlineData("UnknownEnumVal_CsdlTarget", new object[] { "CsdlTarget" })]
    [InlineData("UnknownEnumVal_ExpressionKind", new object[] { "ExpressionKind" })]
    [InlineData("UnknownEnumVal_Multiplicity", new object[] { "Multiplicity" })]
    [InlineData("UnknownEnumVal_PrimitiveKind", new object[] { "PrimitiveKind" })]
    [InlineData("UnknownEnumVal_PropertyKind", new object[] { "PropertyKind" })]
    [InlineData("UnknownEnumVal_SchemaElementKind", new object[] { "SchemaElementKind" })]
    [InlineData("UnknownEnumVal_TypeKind", new object[] { "TypeKind" })]
    [InlineData("ValueHasAlreadyBeenSet", new object[] { })]
    [InlineData("ValueParser_InvalidBinary", new object[] { "BinaryValue" })]
    [InlineData("ValueParser_InvalidBoolean", new object[] { "BooleanValue" })]
    [InlineData("ValueParser_InvalidDate", new object[] { "DateValue" })]
    [InlineData("ValueParser_InvalidDateTime", new object[] { "DateTimeValue" })]
    [InlineData("ValueParser_InvalidDateTimeOffset", new object[] { "DateTimeOffsetValue" })]
    [InlineData("ValueParser_InvalidDecimal", new object[] { "DecimalValue" })]
    [InlineData("ValueParser_InvalidDuration", new object[] { "DurationValue" })]
    [InlineData("ValueParser_InvalidFloatingPoint", new object[] { "FloatingPointValue" })]
    [InlineData("ValueParser_InvalidGuid", new object[] { "GuidValue" })]
    [InlineData("ValueParser_InvalidInteger", new object[] { "IntegerValue" })]
    [InlineData("ValueParser_InvalidLong", new object[] { "LongValue" })]
    [InlineData("ValueParser_InvalidMaxLength", new object[] { "MaxLengthValue" })]
    [InlineData("ValueParser_InvalidScale", new object[] { "ScaleValue" })]
    [InlineData("ValueParser_InvalidSrid", new object[] { "SridValue" })]
    [InlineData("ValueParser_InvalidTimeOfDay", new object[] { "TimeOfDayValue" })]
    [InlineData("ValueWriter_NonSerializableValue", new object[] { "ValueKind" })]
    [InlineData("XmlParser_EmptyFile", new object[] { "FileName" })]
    [InlineData("XmlParser_EmptySchemaTextReader", new object[] { })]
    [InlineData("XmlParser_MissingAttribute", new object[] { "AttributeName", "ElementName" })]
    [InlineData("XmlParser_TextNotAllowed", new object[] { "TextValue" })]
    [InlineData("XmlParser_UnexpectedAttribute", new object[] { "AttributeName" })]
    [InlineData("XmlParser_UnexpectedElement", new object[] { "ElementName" })]
    [InlineData("XmlParser_UnexpectedNodeType", new object[] { "NodeType" })]
    [InlineData("XmlParser_UnexpectedRootElement", new object[] { "ElementName", "ExpectedRootElement" })]
    [InlineData("XmlParser_UnexpectedRootElementNoNamespace", new object[] { "ExpectedNamespaces" })]
    [InlineData("XmlParser_UnexpectedRootElementWrongNamespace", new object[] { "Namespace", "ExpectedNamespaces" })]
    [InlineData("XmlParser_UnusedElement", new object[] { "ElementName" })]

    public void ResourceKey_ShouldFormatWithoutException(string resourceKey, object[] formatArgs)
    {
        // Arrange
        var resourceValue = SRResources.ResourceManager.GetString(resourceKey, SRResources.Culture);
        Assert.NotNull(resourceValue); // Ensure the resource exists

        // Act & Assert
        var exception = Record.Exception(() => Error.Format(resourceValue, formatArgs));
        Assert.Null(exception); // Ensure no Exception is thrown

        var matches = Regex.Matches(resourceValue, @"\{\d+\}").Select(m => m.Value).Distinct();
        Assert.Equal(matches.Count(), formatArgs.Length);

        var formattedValue = Error.Format(resourceValue, formatArgs);
        Assert.NotNull(formattedValue);
    }
}
