//---------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="Microsoft">
//      Copyright (C) Microsoft Corporation. All rights reserved. See License.txt in the project root for license information.
// </copyright>
//---------------------------------------------------------------------

// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project. Project-level
// suppressions either have no target or are given a specific target
// and scoped to a namespace, type, member, etc.
//
// To add a suppression to this file, right-click the message in the
// Error List, point to "Suppress Message(s)", and click "In Project
// Suppression File". You do not need to add suppressions to this
// file manually.
using System.Diagnostics.CodeAnalysis;

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1014:MarkAssembliesWithClsCompliant")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "entity", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext.#TryGetEntity`1(System.Type,Microsoft.Test.Taupo.Contracts.Wrappers.WrappedObject,!!0)", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "identity", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext.#TryGetUri(Microsoft.Test.Taupo.Contracts.Wrappers.WrappedObject,Microsoft.Test.Taupo.Contracts.Wrappers.WrappedObject)", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery`1.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQueryContinuation.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceRequest.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceRequest`1.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceResponse.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceStreamResponse.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedEntityDescriptor.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedLinkInfo.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedLinkDescriptor.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711:IdentifiersShouldNotHaveIncorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceCollection`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceCollection`1.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedQueryOperationResponse.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedQueryOperationResponse`1.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Php.PhpCodeGenerator", Justification = "PhpCodeGenerator calls dispose on the StringWriter")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Php.PhpQueryExpressionVisitor.#Visit(Microsoft.Test.Taupo.Query.Contracts.CommonExpressions.QueryRootExpression)", Justification = "Casting is done only once, one usages is to check type")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDescriptor.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedStreamDescriptor.#.cctor()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.EnumerableProxy", Justification = "Name is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.EnumerableProxy`1", Justification = "Name is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1038:EnumeratorsShouldBeStronglyTyped", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.EnumeratorProxy", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.QueryableProxy", Justification = "Name is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.QueryableProxy`1", Justification = "Name is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.StreamProxy", Justification = "Name is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.QueryableProxy`1.#System.Collections.Generic.IEnumerable`1<!0>.GetEnumerator()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.QueryableProxy`1.#System.Collections.IEnumerable.GetEnumerator()", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker.#RaiseAfterAddObject(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker+AddObjectEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker.#RaiseAfterDetachLink(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker+AfterDetachLinkEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker.#RaiseBeforeAddObject(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker+AddObjectEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker.#RaiseBeforeDetachLink(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext+EventsTracker+BeforeDetachLinkEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery+EventsTracker.#RaiseAfterExecute(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery+EventsTracker+AfterExecuteEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1030:UseEventsWhereAppropriate", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery+EventsTracker.#RaiseBeforeExecute(Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceQuery+EventsTracker+BeforeExecuteEventArgs)", Justification = "Needs to be a method, is only public so it can be called via reflection")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "etag", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceContext.#AttachTo(System.String,Microsoft.Test.Taupo.Contracts.Wrappers.WrappedObject,System.String)", Justification = "Code is generated")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedDataServiceStreamLink.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedOperationParameter.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1810:InitializeReferenceTypeStaticFieldsInline", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.WrappedOperationDescriptor.#.cctor()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.OrderedQueryableProxy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710:IdentifiersShouldHaveCorrectSuffix", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.OrderedQueryableProxy`1")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.OrderedQueryableProxy`1.#System.Collections.Generic.IEnumerable`1<!0>.GetEnumerator()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.Wrappers.OrderedQueryableProxy`1.#System.Collections.IEnumerable.GetEnumerator()")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.EntityModel.ActionsModelGenerator.#RemoveHigherVersionModelFeaturesExceptActionWithMultiValue")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Multi", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.EntityFrameworkDataProviderSettings.#RemoveMultiValueFixup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2202:Do not dispose objects multiple times", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.OData.XmlPayloadErrorDeserializer.#TryDeserializeErrorPayload(System.Byte[],System.String,Microsoft.Test.Taupo.Astoria.Contracts.OData.ODataPayloadElement&)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "namespace", Target = "Microsoft.Test.Taupo.Astoria.Contracts.DataServices.WebServerLocator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.AstoriaWorkspaceBuilder.#BuildDataService(Microsoft.Test.Taupo.Common.IAsyncContinuation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Client.ClientQueryResultComparer.#VerifyDescriptorAfterExecute(Microsoft.Test.Taupo.Common.IAsyncContinuation,Microsoft.OData.Client.DataServiceContext,System.Collections.Generic.IEnumerable`1<System.Object>,Microsoft.Test.Taupo.Query.Contracts.QueryValue)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Client.ClientQueryResultComparer.#ExecuteQueryAction(Microsoft.Test.Taupo.Common.IAsyncContinuation,Microsoft.Test.Taupo.Query.Contracts.QueryValue,Microsoft.OData.Client.DataServiceContext,Microsoft.Test.Taupo.Astoria.Contracts.Client.ExpectedClientErrorBaseline,System.Action`2<System.Collections.Generic.List`1<System.Object>,Microsoft.Test.Taupo.Common.IAsyncContinuation>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.ServiceCreation.DataServiceWebServerLocator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "sku", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.ServiceCreation.DataServiceWebServerLocator.#MapLabSkuToString(System.Nullable`1<Microsoft.Test.Taupo.Astoria.Contracts.LabSkuType>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sku", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.ServiceCreation.DataServiceWebServerLocator.#MapLabSkuToString(System.Nullable`1<Microsoft.Test.Taupo.Astoria.Contracts.LabSkuType>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.ServiceCreation.DataServiceWebServerLocatorStrategy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.ServiceCreation.FakeDataServiceWebServerLocatorStrategy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.IDataServiceWebServerLocatorStrategy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServers", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.IDataServiceWebServerLocatorStrategy.#WebServersQueryRoot")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.IWebServerLocator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sku", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.LabSkuType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Sku", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.MachineSearchCriteria.#SkuType")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.LinqToAstoria.ODataUriEvaluator")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.OracleBasedAsyncDataSynchronizer.#SynchronizeEntireEntitySet(Microsoft.Test.Taupo.Common.IAsyncContinuation,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2201:DoNotRaiseReservedExceptionTypes", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.OracleBasedAsyncDataSynchronizer.#SynchronizeEntityInstanceGraph(Microsoft.Test.Taupo.Common.IAsyncContinuation,System.String,System.Collections.Generic.IEnumerable`1<Microsoft.Test.Taupo.Contracts.NamedValue>)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "toRun", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Contracts.OData.PayloadTransformationFluentExtensions.#Run(Microsoft.Test.Taupo.Astoria.Contracts.OData.IPayloadTransformationScope,System.Action)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.ResponseVerification.ResponseVerificationContext.#GetInsertedEntity(Microsoft.Test.Taupo.Astoria.Contracts.OData.ODataRequest,Microsoft.Test.Taupo.Astoria.Contracts.OData.ODataResponse)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704:IdentifiersShouldBeSpelledCorrectly", MessageId = "Api", Scope = "member", Target = "Microsoft.Test.Taupo.Astoria.Client.SaveChangesVerifierBase.#CallProductApi(Microsoft.Test.Taupo.Common.IAsyncContinuation)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1702:CompoundWordsShouldBeCasedCorrectly", MessageId = "WebServer", Scope = "type", Target = "Microsoft.Test.Taupo.Astoria.Contracts.WebServerLocatorCompleteEventArgs")]